// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeAppointment is the FHIR resource type name for Appointment.
const ResourceTypeAppointment = "Appointment"

// AppointmentParticipant represents a FHIR BackboneElement for Appointment.participant.
type AppointmentParticipant struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Role of participant in the appointment
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*,summary"`
	// Person, Location/HealthcareService or Device
	Actor *Reference `json:"actor,omitempty" fhir:"cardinality=0..1,summary"`
	// required | optional | information-only
	Required *string `json:"required,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Required
	RequiredExt *primitives.PrimitiveExtension `json:"_required,omitempty" fhir:"cardinality=0..1"`
	// accepted | declined | tentative | needs-action
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Participation period of the actor
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1"`
}

// Appointment represents a FHIR Appointment.
type Appointment struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External Ids for this item
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// proposed | pending | booked | arrived | fulfilled | cancelled | noshow | entered-in-error | checked-in | waitlist
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// The coded reason for the appointment being cancelled
	CancelationReason *CodeableConcept `json:"cancelationReason,omitempty" fhir:"cardinality=0..1,summary"`
	// A broad categorization of the service that is to be performed during this appointment
	ServiceCategory []CodeableConcept `json:"serviceCategory,omitempty" fhir:"cardinality=0..*,summary"`
	// The specific service that is to be performed during this appointment
	ServiceType []CodeableConcept `json:"serviceType,omitempty" fhir:"cardinality=0..*,summary"`
	// The specialty of a practitioner that would be required to perform the service requested in this appointment
	Specialty []CodeableConcept `json:"specialty,omitempty" fhir:"cardinality=0..*,summary"`
	// The style of appointment or patient that has been booked in the slot (not service type)
	AppointmentType *CodeableConcept `json:"appointmentType,omitempty" fhir:"cardinality=0..1,summary"`
	// Coded reason this appointment is scheduled
	ReasonCode []CodeableConcept `json:"reasonCode,omitempty" fhir:"cardinality=0..*,summary"`
	// Reason the appointment is to take place (resource)
	ReasonReference []Reference `json:"reasonReference,omitempty" fhir:"cardinality=0..*"`
	// Used to make informed decisions if needing to re-prioritize
	Priority *uint `json:"priority,omitempty" fhir:"cardinality=0..1"`
	// Extension for Priority
	PriorityExt *primitives.PrimitiveExtension `json:"_priority,omitempty" fhir:"cardinality=0..1"`
	// Shown on a subject line in a meeting request, or appointment list
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Additional information to support the appointment
	SupportingInformation []Reference `json:"supportingInformation,omitempty" fhir:"cardinality=0..*"`
	// When appointment is to take place
	Start *primitives.Instant `json:"start,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Start
	StartExt *primitives.PrimitiveExtension `json:"_start,omitempty" fhir:"cardinality=0..1"`
	// When appointment is to conclude
	End *primitives.Instant `json:"end,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for End
	EndExt *primitives.PrimitiveExtension `json:"_end,omitempty" fhir:"cardinality=0..1"`
	// Can be less than start/end (e.g. estimate)
	MinutesDuration *int `json:"minutesDuration,omitempty" fhir:"cardinality=0..1"`
	// Extension for MinutesDuration
	MinutesDurationExt *primitives.PrimitiveExtension `json:"_minutesDuration,omitempty" fhir:"cardinality=0..1"`
	// The slots that this appointment is filling
	Slot []Reference `json:"slot,omitempty" fhir:"cardinality=0..*"`
	// The date that this appointment was initially created
	Created *primitives.DateTime `json:"created,omitempty" fhir:"cardinality=0..1"`
	// Extension for Created
	CreatedExt *primitives.PrimitiveExtension `json:"_created,omitempty" fhir:"cardinality=0..1"`
	// Additional comments
	Comment *string `json:"comment,omitempty" fhir:"cardinality=0..1"`
	// Extension for Comment
	CommentExt *primitives.PrimitiveExtension `json:"_comment,omitempty" fhir:"cardinality=0..1"`
	// Detailed information and instructions for the patient
	PatientInstruction *string `json:"patientInstruction,omitempty" fhir:"cardinality=0..1"`
	// Extension for PatientInstruction
	PatientInstructionExt *primitives.PrimitiveExtension `json:"_patientInstruction,omitempty" fhir:"cardinality=0..1"`
	// The service request this appointment is allocated to assess
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*"`
	// Participants involved in appointment
	Participant []AppointmentParticipant `json:"participant,omitempty" fhir:"cardinality=1..*,required"`
	// Potential date/time interval(s) requested to allocate the appointment within
	RequestedPeriod []Period `json:"requestedPeriod,omitempty" fhir:"cardinality=0..*"`
}
