// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeBiologicallyDerivedProduct is the FHIR resource type name for BiologicallyDerivedProduct.
const ResourceTypeBiologicallyDerivedProduct = "BiologicallyDerivedProduct"

// BiologicallyDerivedProductCollection represents a FHIR BackboneElement for BiologicallyDerivedProduct.collection.
type BiologicallyDerivedProductCollection struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Individual performing collection
	Collector *Reference `json:"collector,omitempty" fhir:"cardinality=0..1"`
	// Who is product from
	Source *Reference `json:"source,omitempty" fhir:"cardinality=0..1"`
	// Time of product collection - dateTime option
	CollectedDateTime *primitives.DateTime `json:"collectedDateTime,omitempty" fhir:"cardinality=0..1,choice=collected"`
	// Extension for CollectedDateTime
	CollectedDateTimeExt *primitives.PrimitiveExtension `json:"_collectedDateTime,omitempty" fhir:"cardinality=0..1"`
	// Time of product collection - Period option
	CollectedPeriod *Period `json:"collectedPeriod,omitempty" fhir:"cardinality=0..1,choice=collected"`
}

// BiologicallyDerivedProductProcessing represents a FHIR BackboneElement for BiologicallyDerivedProduct.processing.
type BiologicallyDerivedProductProcessing struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of of processing
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Procesing code
	Procedure *CodeableConcept `json:"procedure,omitempty" fhir:"cardinality=0..1"`
	// Substance added during processing
	Additive *Reference `json:"additive,omitempty" fhir:"cardinality=0..1"`
	// Time of processing - dateTime option
	TimeDateTime *primitives.DateTime `json:"timeDateTime,omitempty" fhir:"cardinality=0..1,choice=time"`
	// Extension for TimeDateTime
	TimeDateTimeExt *primitives.PrimitiveExtension `json:"_timeDateTime,omitempty" fhir:"cardinality=0..1"`
	// Time of processing - Period option
	TimePeriod *Period `json:"timePeriod,omitempty" fhir:"cardinality=0..1,choice=time"`
}

// BiologicallyDerivedProductManipulation represents a FHIR BackboneElement for BiologicallyDerivedProduct.manipulation.
type BiologicallyDerivedProductManipulation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of manipulation
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Time of manipulation - dateTime option
	TimeDateTime *primitives.DateTime `json:"timeDateTime,omitempty" fhir:"cardinality=0..1,choice=time"`
	// Extension for TimeDateTime
	TimeDateTimeExt *primitives.PrimitiveExtension `json:"_timeDateTime,omitempty" fhir:"cardinality=0..1"`
	// Time of manipulation - Period option
	TimePeriod *Period `json:"timePeriod,omitempty" fhir:"cardinality=0..1,choice=time"`
}

// BiologicallyDerivedProductStorage represents a FHIR BackboneElement for BiologicallyDerivedProduct.storage.
type BiologicallyDerivedProductStorage struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of storage
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Storage temperature
	Temperature *float64 `json:"temperature,omitempty" fhir:"cardinality=0..1"`
	// Extension for Temperature
	TemperatureExt *primitives.PrimitiveExtension `json:"_temperature,omitempty" fhir:"cardinality=0..1"`
	// farenheit | celsius | kelvin
	Scale *string `json:"scale,omitempty" fhir:"cardinality=0..1"`
	// Extension for Scale
	ScaleExt *primitives.PrimitiveExtension `json:"_scale,omitempty" fhir:"cardinality=0..1"`
	// Storage timeperiod
	Duration *Period `json:"duration,omitempty" fhir:"cardinality=0..1"`
}

// BiologicallyDerivedProduct represents a FHIR BiologicallyDerivedProduct.
type BiologicallyDerivedProduct struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External ids for this item
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// organ | tissue | fluid | cells | biologicalAgent
	ProductCategory *string `json:"productCategory,omitempty" fhir:"cardinality=0..1"`
	// Extension for ProductCategory
	ProductCategoryExt *primitives.PrimitiveExtension `json:"_productCategory,omitempty" fhir:"cardinality=0..1"`
	// What this biologically derived product is
	ProductCode *CodeableConcept `json:"productCode,omitempty" fhir:"cardinality=0..1"`
	// available | unavailable
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Procedure request
	Request []Reference `json:"request,omitempty" fhir:"cardinality=0..*"`
	// The amount of this biologically derived product
	Quantity *int `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// Extension for Quantity
	QuantityExt *primitives.PrimitiveExtension `json:"_quantity,omitempty" fhir:"cardinality=0..1"`
	// BiologicallyDerivedProduct parent
	Parent []Reference `json:"parent,omitempty" fhir:"cardinality=0..*"`
	// How this product was collected
	Collection *BiologicallyDerivedProductCollection `json:"collection,omitempty" fhir:"cardinality=0..1"`
	// Any processing of the product during collection
	Processing []BiologicallyDerivedProductProcessing `json:"processing,omitempty" fhir:"cardinality=0..*"`
	// Any manipulation of product post-collection
	Manipulation *BiologicallyDerivedProductManipulation `json:"manipulation,omitempty" fhir:"cardinality=0..1"`
	// Product storage
	Storage []BiologicallyDerivedProductStorage `json:"storage,omitempty" fhir:"cardinality=0..*"`
}
