// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeBodyStructure is the FHIR resource type name for BodyStructure.
const ResourceTypeBodyStructure = "BodyStructure"

// BodyStructure represents a FHIR BodyStructure.
type BodyStructure struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Bodystructure identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether this record is in active use
	Active *bool `json:"active,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Active
	ActiveExt *primitives.PrimitiveExtension `json:"_active,omitempty" fhir:"cardinality=0..1"`
	// Kind of Structure
	Morphology *CodeableConcept `json:"morphology,omitempty" fhir:"cardinality=0..1,summary"`
	// Body site
	Location *CodeableConcept `json:"location,omitempty" fhir:"cardinality=0..1,summary"`
	// Body site modifier
	LocationQualifier []CodeableConcept `json:"locationQualifier,omitempty" fhir:"cardinality=0..*"`
	// Text description
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Attached images
	Image []Attachment `json:"image,omitempty" fhir:"cardinality=0..*"`
	// Who this is about
	Patient Reference `json:"patient" fhir:"cardinality=1..1,required,summary"`
}
