// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeCarePlan is the FHIR resource type name for CarePlan.
const ResourceTypeCarePlan = "CarePlan"

// CarePlanActivityDetail represents a FHIR BackboneElement for CarePlan.activity.detail.
type CarePlanActivityDetail struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Appointment | CommunicationRequest | DeviceRequest | MedicationRequest | NutritionOrder | Task | ServiceRequest | VisionPrescription
	Kind *string `json:"kind,omitempty" fhir:"cardinality=0..1"`
	// Extension for Kind
	KindExt *primitives.PrimitiveExtension `json:"_kind,omitempty" fhir:"cardinality=0..1"`
	// Instantiates FHIR protocol or definition
	InstantiatesCanonical []string `json:"instantiatesCanonical,omitempty" fhir:"cardinality=0..*"`
	// Extension for InstantiatesCanonical
	InstantiatesCanonicalExt *primitives.PrimitiveExtension `json:"_instantiatesCanonical,omitempty" fhir:"cardinality=0..1"`
	// Instantiates external protocol or definition
	InstantiatesUri []string `json:"instantiatesUri,omitempty" fhir:"cardinality=0..*"`
	// Extension for InstantiatesUri
	InstantiatesUriExt *primitives.PrimitiveExtension `json:"_instantiatesUri,omitempty" fhir:"cardinality=0..1"`
	// Detail type of activity
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Why activity should be done or why activity was prohibited
	ReasonCode []CodeableConcept `json:"reasonCode,omitempty" fhir:"cardinality=0..*"`
	// Why activity is needed
	ReasonReference []Reference `json:"reasonReference,omitempty" fhir:"cardinality=0..*"`
	// Goals this activity relates to
	Goal []Reference `json:"goal,omitempty" fhir:"cardinality=0..*"`
	// not-started | scheduled | in-progress | on-hold | completed | cancelled | stopped | unknown | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Reason for current status
	StatusReason *CodeableConcept `json:"statusReason,omitempty" fhir:"cardinality=0..1"`
	// If true, activity is prohibiting action
	DoNotPerform *bool `json:"doNotPerform,omitempty" fhir:"cardinality=0..1"`
	// Extension for DoNotPerform
	DoNotPerformExt *primitives.PrimitiveExtension `json:"_doNotPerform,omitempty" fhir:"cardinality=0..1"`
	// When activity is to occur - Timing option
	ScheduledTiming *Timing `json:"scheduledTiming,omitempty" fhir:"cardinality=0..1,choice=scheduled"`
	// When activity is to occur - Period option
	ScheduledPeriod *Period `json:"scheduledPeriod,omitempty" fhir:"cardinality=0..1,choice=scheduled"`
	// When activity is to occur - string option
	ScheduledString *string `json:"scheduledString,omitempty" fhir:"cardinality=0..1,choice=scheduled"`
	// Extension for ScheduledString
	ScheduledStringExt *primitives.PrimitiveExtension `json:"_scheduledString,omitempty" fhir:"cardinality=0..1"`
	// Where it should happen
	Location *Reference `json:"location,omitempty" fhir:"cardinality=0..1"`
	// Who will be responsible?
	Performer []Reference `json:"performer,omitempty" fhir:"cardinality=0..*"`
	// What is to be administered/supplied - CodeableConcept option
	ProductCodeableConcept *CodeableConcept `json:"productCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=product"`
	// What is to be administered/supplied - Reference option
	ProductReference *Reference `json:"productReference,omitempty" fhir:"cardinality=0..1,choice=product"`
	// How to consume/day?
	DailyAmount *Quantity `json:"dailyAmount,omitempty" fhir:"cardinality=0..1"`
	// How much to administer/supply/consume
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// Extra info describing activity to perform
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
}

// CarePlanActivity represents a FHIR BackboneElement for CarePlan.activity.
type CarePlanActivity struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Results of the activity
	OutcomeCodeableConcept []CodeableConcept `json:"outcomeCodeableConcept,omitempty" fhir:"cardinality=0..*"`
	// Appointment, Encounter, Procedure, etc.
	OutcomeReference []Reference `json:"outcomeReference,omitempty" fhir:"cardinality=0..*"`
	// Comments about the activity status/progress
	Progress []Annotation `json:"progress,omitempty" fhir:"cardinality=0..*"`
	// Activity details defined in specific resource
	Reference *Reference `json:"reference,omitempty" fhir:"cardinality=0..1"`
	// In-line definition of activity
	Detail *CarePlanActivityDetail `json:"detail,omitempty" fhir:"cardinality=0..1"`
}

// CarePlan represents a FHIR CarePlan.
type CarePlan struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External Ids for this plan
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Instantiates FHIR protocol or definition
	InstantiatesCanonical []string `json:"instantiatesCanonical,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for InstantiatesCanonical
	InstantiatesCanonicalExt *primitives.PrimitiveExtension `json:"_instantiatesCanonical,omitempty" fhir:"cardinality=0..1"`
	// Instantiates external protocol or definition
	InstantiatesUri []string `json:"instantiatesUri,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for InstantiatesUri
	InstantiatesUriExt *primitives.PrimitiveExtension `json:"_instantiatesUri,omitempty" fhir:"cardinality=0..1"`
	// Fulfills CarePlan
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// CarePlan replaced by this CarePlan
	Replaces []Reference `json:"replaces,omitempty" fhir:"cardinality=0..*,summary"`
	// Part of referenced CarePlan
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*,summary"`
	// draft | active | on-hold | revoked | completed | entered-in-error | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// proposal | plan | order | option
	Intent string `json:"intent" fhir:"cardinality=1..1,required,summary"`
	// Extension for Intent
	IntentExt *primitives.PrimitiveExtension `json:"_intent,omitempty" fhir:"cardinality=0..1"`
	// Type of plan
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Human-friendly name for the care plan
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Summary of nature of plan
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Who the care plan is for
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// Encounter created as part of
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// Time period plan covers
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Date record was first recorded
	Created *primitives.DateTime `json:"created,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Created
	CreatedExt *primitives.PrimitiveExtension `json:"_created,omitempty" fhir:"cardinality=0..1"`
	// Who is the designated responsible party
	Author *Reference `json:"author,omitempty" fhir:"cardinality=0..1,summary"`
	// Who provided the content of the care plan
	Contributor []Reference `json:"contributor,omitempty" fhir:"cardinality=0..*"`
	// Who's involved in plan?
	CareTeam []Reference `json:"careTeam,omitempty" fhir:"cardinality=0..*"`
	// Health issues this plan addresses
	Addresses []Reference `json:"addresses,omitempty" fhir:"cardinality=0..*,summary"`
	// Information considered as part of plan
	SupportingInfo []Reference `json:"supportingInfo,omitempty" fhir:"cardinality=0..*"`
	// Desired outcome of plan
	Goal []Reference `json:"goal,omitempty" fhir:"cardinality=0..*"`
	// Action to occur as part of plan
	Activity []CarePlanActivity `json:"activity,omitempty" fhir:"cardinality=0..*"`
	// Comments about the plan
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
}
