// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeCareTeam is the FHIR resource type name for CareTeam.
const ResourceTypeCareTeam = "CareTeam"

// CareTeamParticipant represents a FHIR BackboneElement for CareTeam.participant.
type CareTeamParticipant struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of involvement
	Role []CodeableConcept `json:"role,omitempty" fhir:"cardinality=0..*,summary"`
	// Who is involved
	Member *Reference `json:"member,omitempty" fhir:"cardinality=0..1,summary"`
	// Organization of the practitioner
	OnBehalfOf *Reference `json:"onBehalfOf,omitempty" fhir:"cardinality=0..1,summary"`
	// Time period of participant
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1"`
}

// CareTeam represents a FHIR CareTeam.
type CareTeam struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External Ids for this team
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// proposed | active | suspended | inactive | entered-in-error
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Type of team
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Name of the team, such as crisis assessment team
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Who care team is for
	Subject *Reference `json:"subject,omitempty" fhir:"cardinality=0..1,summary"`
	// Encounter created as part of
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// Time period team covers
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Members of the team
	Participant []CareTeamParticipant `json:"participant,omitempty" fhir:"cardinality=0..*"`
	// Why the care team exists
	ReasonCode []CodeableConcept `json:"reasonCode,omitempty" fhir:"cardinality=0..*"`
	// Why the care team exists
	ReasonReference []Reference `json:"reasonReference,omitempty" fhir:"cardinality=0..*"`
	// Organization responsible for the care team
	ManagingOrganization []Reference `json:"managingOrganization,omitempty" fhir:"cardinality=0..*,summary"`
	// A contact detail for the care team (that applies to all members)
	Telecom []ContactPoint `json:"telecom,omitempty" fhir:"cardinality=0..*"`
	// Comments made about the CareTeam
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
}
