// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeCatalogEntry is the FHIR resource type name for CatalogEntry.
const ResourceTypeCatalogEntry = "CatalogEntry"

// CatalogEntryRelatedEntry represents a FHIR BackboneElement for CatalogEntry.relatedEntry.
type CatalogEntryRelatedEntry struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// triggers | is-replaced-by
	Relationtype string `json:"relationtype" fhir:"cardinality=1..1,required"`
	// Extension for Relationtype
	RelationtypeExt *primitives.PrimitiveExtension `json:"_relationtype,omitempty" fhir:"cardinality=0..1"`
	// The reference to the related item
	Item Reference `json:"item" fhir:"cardinality=1..1,required"`
}

// CatalogEntry represents a FHIR CatalogEntry.
type CatalogEntry struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Unique identifier of the catalog item
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// The type of item - medication, device, service, protocol or other
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Whether the entry represents an orderable item
	Orderable bool `json:"orderable" fhir:"cardinality=1..1,required,summary"`
	// Extension for Orderable
	OrderableExt *primitives.PrimitiveExtension `json:"_orderable,omitempty" fhir:"cardinality=0..1"`
	// The item that is being defined
	ReferencedItem Reference `json:"referencedItem" fhir:"cardinality=1..1,required,summary"`
	// Any additional identifier(s) for the catalog item, in the same granularity or concept
	AdditionalIdentifier []Identifier `json:"additionalIdentifier,omitempty" fhir:"cardinality=0..*"`
	// Classification (category or class) of the item entry
	Classification []CodeableConcept `json:"classification,omitempty" fhir:"cardinality=0..*"`
	// draft | active | retired | unknown
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// The time period in which this catalog entry is expected to be active
	ValidityPeriod *Period `json:"validityPeriod,omitempty" fhir:"cardinality=0..1"`
	// The date until which this catalog entry is expected to be active
	ValidTo *primitives.DateTime `json:"validTo,omitempty" fhir:"cardinality=0..1"`
	// Extension for ValidTo
	ValidToExt *primitives.PrimitiveExtension `json:"_validTo,omitempty" fhir:"cardinality=0..1"`
	// When was this catalog last updated
	LastUpdated *primitives.DateTime `json:"lastUpdated,omitempty" fhir:"cardinality=0..1"`
	// Extension for LastUpdated
	LastUpdatedExt *primitives.PrimitiveExtension `json:"_lastUpdated,omitempty" fhir:"cardinality=0..1"`
	// Additional characteristics of the catalog entry
	AdditionalCharacteristic []CodeableConcept `json:"additionalCharacteristic,omitempty" fhir:"cardinality=0..*"`
	// Additional classification of the catalog entry
	AdditionalClassification []CodeableConcept `json:"additionalClassification,omitempty" fhir:"cardinality=0..*"`
	// An item that this catalog entry is related to
	RelatedEntry []CatalogEntryRelatedEntry `json:"relatedEntry,omitempty" fhir:"cardinality=0..*"`
}
