// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeClinicalImpression is the FHIR resource type name for ClinicalImpression.
const ResourceTypeClinicalImpression = "ClinicalImpression"

// ClinicalImpressionInvestigation represents a FHIR BackboneElement for ClinicalImpression.investigation.
type ClinicalImpressionInvestigation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// A name/code for the set
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required"`
	// Record of a specific investigation
	Item []Reference `json:"item,omitempty" fhir:"cardinality=0..*"`
}

// ClinicalImpressionFinding represents a FHIR BackboneElement for ClinicalImpression.finding.
type ClinicalImpressionFinding struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// What was found
	ItemCodeableConcept *CodeableConcept `json:"itemCodeableConcept,omitempty" fhir:"cardinality=0..1"`
	// What was found
	ItemReference *Reference `json:"itemReference,omitempty" fhir:"cardinality=0..1"`
	// Which investigations support finding
	Basis *string `json:"basis,omitempty" fhir:"cardinality=0..1"`
	// Extension for Basis
	BasisExt *primitives.PrimitiveExtension `json:"_basis,omitempty" fhir:"cardinality=0..1"`
}

// ClinicalImpression represents a FHIR ClinicalImpression.
type ClinicalImpression struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// in-progress | completed | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Reason for current status
	StatusReason *CodeableConcept `json:"statusReason,omitempty" fhir:"cardinality=0..1"`
	// Kind of assessment performed
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// Why/how the assessment was performed
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Patient or group assessed
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// Encounter created as part of
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// Time of assessment - dateTime option
	EffectiveDateTime *primitives.DateTime `json:"effectiveDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=effective"`
	// Extension for EffectiveDateTime
	EffectiveDateTimeExt *primitives.PrimitiveExtension `json:"_effectiveDateTime,omitempty" fhir:"cardinality=0..1"`
	// Time of assessment - Period option
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary,choice=effective"`
	// When the assessment was documented
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// The clinician performing the assessment
	Assessor *Reference `json:"assessor,omitempty" fhir:"cardinality=0..1,summary"`
	// Reference to last assessment
	Previous *Reference `json:"previous,omitempty" fhir:"cardinality=0..1"`
	// Relevant impressions of patient state
	Problem []Reference `json:"problem,omitempty" fhir:"cardinality=0..*,summary"`
	// One or more sets of investigations (signs, symptoms, etc.)
	Investigation []ClinicalImpressionInvestigation `json:"investigation,omitempty" fhir:"cardinality=0..*"`
	// Clinical Protocol followed
	Protocol []string `json:"protocol,omitempty" fhir:"cardinality=0..*"`
	// Extension for Protocol
	ProtocolExt *primitives.PrimitiveExtension `json:"_protocol,omitempty" fhir:"cardinality=0..1"`
	// Summary of the assessment
	Summary *string `json:"summary,omitempty" fhir:"cardinality=0..1"`
	// Extension for Summary
	SummaryExt *primitives.PrimitiveExtension `json:"_summary,omitempty" fhir:"cardinality=0..1"`
	// Possible or likely findings and diagnoses
	Finding []ClinicalImpressionFinding `json:"finding,omitempty" fhir:"cardinality=0..*"`
	// Estimate of likely outcome
	PrognosisCodeableConcept []CodeableConcept `json:"prognosisCodeableConcept,omitempty" fhir:"cardinality=0..*"`
	// RiskAssessment expressing likely outcome
	PrognosisReference []Reference `json:"prognosisReference,omitempty" fhir:"cardinality=0..*"`
	// Information supporting the clinical impression
	SupportingInfo []Reference `json:"supportingInfo,omitempty" fhir:"cardinality=0..*"`
	// Comments made about the ClinicalImpression
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
}
