// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeCommunication is the FHIR resource type name for Communication.
const ResourceTypeCommunication = "Communication"

// CommunicationPayload represents a FHIR BackboneElement for Communication.payload.
type CommunicationPayload struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Message part content - string option
	ContentString string `json:"contentString" fhir:"cardinality=1..1,required,choice=content"`
	// Extension for ContentString
	ContentStringExt *primitives.PrimitiveExtension `json:"_contentString,omitempty" fhir:"cardinality=0..1"`
	// Message part content - Attachment option
	ContentAttachment Attachment `json:"contentAttachment" fhir:"cardinality=1..1,required,choice=content"`
	// Message part content - Reference option
	ContentReference Reference `json:"contentReference" fhir:"cardinality=1..1,required,choice=content"`
}

// Communication represents a FHIR Communication.
type Communication struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Unique identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Instantiates FHIR protocol or definition
	InstantiatesCanonical []string `json:"instantiatesCanonical,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for InstantiatesCanonical
	InstantiatesCanonicalExt *primitives.PrimitiveExtension `json:"_instantiatesCanonical,omitempty" fhir:"cardinality=0..1"`
	// Instantiates external protocol or definition
	InstantiatesUri []string `json:"instantiatesUri,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for InstantiatesUri
	InstantiatesUriExt *primitives.PrimitiveExtension `json:"_instantiatesUri,omitempty" fhir:"cardinality=0..1"`
	// Request fulfilled by this communication
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// Part of this action
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*,summary"`
	// Reply to
	InResponseTo []Reference `json:"inResponseTo,omitempty" fhir:"cardinality=0..*"`
	// preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Reason for current status
	StatusReason *CodeableConcept `json:"statusReason,omitempty" fhir:"cardinality=0..1,summary"`
	// Message category
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*"`
	// routine | urgent | asap | stat
	Priority *string `json:"priority,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Priority
	PriorityExt *primitives.PrimitiveExtension `json:"_priority,omitempty" fhir:"cardinality=0..1"`
	// A channel of communication
	Medium []CodeableConcept `json:"medium,omitempty" fhir:"cardinality=0..*"`
	// Focus of message
	Subject *Reference `json:"subject,omitempty" fhir:"cardinality=0..1,summary"`
	// Description of the purpose/content
	Topic *CodeableConcept `json:"topic,omitempty" fhir:"cardinality=0..1"`
	// Resources that pertain to this communication
	About []Reference `json:"about,omitempty" fhir:"cardinality=0..*"`
	// Encounter created as part of
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// When sent
	Sent *primitives.DateTime `json:"sent,omitempty" fhir:"cardinality=0..1"`
	// Extension for Sent
	SentExt *primitives.PrimitiveExtension `json:"_sent,omitempty" fhir:"cardinality=0..1"`
	// When received
	Received *primitives.DateTime `json:"received,omitempty" fhir:"cardinality=0..1"`
	// Extension for Received
	ReceivedExt *primitives.PrimitiveExtension `json:"_received,omitempty" fhir:"cardinality=0..1"`
	// Message recipient
	Recipient []Reference `json:"recipient,omitempty" fhir:"cardinality=0..*"`
	// Message sender
	Sender *Reference `json:"sender,omitempty" fhir:"cardinality=0..1"`
	// Indication for message
	ReasonCode []CodeableConcept `json:"reasonCode,omitempty" fhir:"cardinality=0..*,summary"`
	// Why was communication done?
	ReasonReference []Reference `json:"reasonReference,omitempty" fhir:"cardinality=0..*,summary"`
	// Message payload
	Payload []CommunicationPayload `json:"payload,omitempty" fhir:"cardinality=0..*"`
	// Comments made about the communication
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
}
