// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeComposition is the FHIR resource type name for Composition.
const ResourceTypeComposition = "Composition"

// CompositionAttester represents a FHIR BackboneElement for Composition.attester.
type CompositionAttester struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// personal | professional | legal | official
	Mode string `json:"mode" fhir:"cardinality=1..1,required"`
	// Extension for Mode
	ModeExt *primitives.PrimitiveExtension `json:"_mode,omitempty" fhir:"cardinality=0..1"`
	// When the composition was attested
	Time *primitives.DateTime `json:"time,omitempty" fhir:"cardinality=0..1"`
	// Extension for Time
	TimeExt *primitives.PrimitiveExtension `json:"_time,omitempty" fhir:"cardinality=0..1"`
	// Who attested the composition
	Party *Reference `json:"party,omitempty" fhir:"cardinality=0..1"`
}

// CompositionRelatesTo represents a FHIR BackboneElement for Composition.relatesTo.
type CompositionRelatesTo struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// replaces | transforms | signs | appends
	Code string `json:"code" fhir:"cardinality=1..1,required"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// Target of the relationship - Identifier option
	TargetIdentifier Identifier `json:"targetIdentifier" fhir:"cardinality=1..1,required,choice=target"`
	// Target of the relationship - Reference option
	TargetReference Reference `json:"targetReference" fhir:"cardinality=1..1,required,choice=target"`
}

// CompositionEvent represents a FHIR BackboneElement for Composition.event.
type CompositionEvent struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Code(s) that apply to the event being documented
	Code []CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..*,summary"`
	// The period covered by the documentation
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// The event(s) being documented
	Detail []Reference `json:"detail,omitempty" fhir:"cardinality=0..*,summary"`
}

// CompositionSectionSection represents a FHIR BackboneElement for Composition.section.section.
type CompositionSectionSection struct {
}

// CompositionSection represents a FHIR BackboneElement for Composition.section.
type CompositionSection struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Label for section (e.g. for ToC)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Classification of section (recommended)
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Who and/or what authored the section
	Author []Reference `json:"author,omitempty" fhir:"cardinality=0..*"`
	// Who/what the section is about, when it is not about the subject of composition
	Focus *Reference `json:"focus,omitempty" fhir:"cardinality=0..1"`
	// Text summary of the section, for human interpretation
	Text *Narrative `json:"text,omitempty" fhir:"cardinality=0..1"`
	// working | snapshot | changes
	Mode *string `json:"mode,omitempty" fhir:"cardinality=0..1"`
	// Extension for Mode
	ModeExt *primitives.PrimitiveExtension `json:"_mode,omitempty" fhir:"cardinality=0..1"`
	// Order of section entries
	OrderedBy *CodeableConcept `json:"orderedBy,omitempty" fhir:"cardinality=0..1"`
	// A reference to data that supports this section
	Entry []Reference `json:"entry,omitempty" fhir:"cardinality=0..*"`
	// Why the section is empty
	EmptyReason *CodeableConcept `json:"emptyReason,omitempty" fhir:"cardinality=0..1"`
	// Nested Section
	Section []CompositionSectionSection `json:"section,omitempty" fhir:"cardinality=0..*"`
}

// Composition represents a FHIR Composition.
type Composition struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Version-independent identifier for the Composition
	Identifier *Identifier `json:"identifier,omitempty" fhir:"cardinality=0..1,summary"`
	// preliminary | final | amended | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Kind of composition (LOINC if possible)
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required,summary"`
	// Categorization of Composition
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Who and/or what the composition is about
	Subject *Reference `json:"subject,omitempty" fhir:"cardinality=0..1,summary"`
	// Context of the Composition
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// Composition editing time
	Date primitives.DateTime `json:"date" fhir:"cardinality=1..1,required,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Who and/or what authored the composition
	Author []Reference `json:"author,omitempty" fhir:"cardinality=1..*,required,summary"`
	// Human Readable name/title
	Title string `json:"title" fhir:"cardinality=1..1,required,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// As defined by affinity domain
	Confidentiality *string `json:"confidentiality,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Confidentiality
	ConfidentialityExt *primitives.PrimitiveExtension `json:"_confidentiality,omitempty" fhir:"cardinality=0..1"`
	// Attests to accuracy of composition
	Attester []CompositionAttester `json:"attester,omitempty" fhir:"cardinality=0..*"`
	// Organization which maintains the composition
	Custodian *Reference `json:"custodian,omitempty" fhir:"cardinality=0..1,summary"`
	// Relationships to other compositions/documents
	RelatesTo []CompositionRelatesTo `json:"relatesTo,omitempty" fhir:"cardinality=0..*"`
	// The clinical service(s) being documented
	Event []CompositionEvent `json:"event,omitempty" fhir:"cardinality=0..*,summary"`
	// Composition is broken into sections
	Section []CompositionSection `json:"section,omitempty" fhir:"cardinality=0..*"`
}
