// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeConceptMap is the FHIR resource type name for ConceptMap.
const ResourceTypeConceptMap = "ConceptMap"

// ConceptMapGroupElementTargetDependsOn represents a FHIR BackboneElement for ConceptMap.group.element.target.dependsOn.
type ConceptMapGroupElementTargetDependsOn struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Reference to property mapping depends on
	Property string `json:"property" fhir:"cardinality=1..1,required"`
	// Extension for Property
	PropertyExt *primitives.PrimitiveExtension `json:"_property,omitempty" fhir:"cardinality=0..1"`
	// Code System (if necessary)
	System *string `json:"system,omitempty" fhir:"cardinality=0..1"`
	// Extension for System
	SystemExt *primitives.PrimitiveExtension `json:"_system,omitempty" fhir:"cardinality=0..1"`
	// Value of the referenced element
	Value string `json:"value" fhir:"cardinality=1..1,required"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
	// Display for the code (if value is a code)
	Display *string `json:"display,omitempty" fhir:"cardinality=0..1"`
	// Extension for Display
	DisplayExt *primitives.PrimitiveExtension `json:"_display,omitempty" fhir:"cardinality=0..1"`
}

// ConceptMapGroupElementTargetProduct represents a FHIR BackboneElement for ConceptMap.group.element.target.product.
type ConceptMapGroupElementTargetProduct struct {
}

// ConceptMapGroupElementTarget represents a FHIR BackboneElement for ConceptMap.group.element.target.
type ConceptMapGroupElementTarget struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Code that identifies the target element
	Code *string `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// Display for the code
	Display *string `json:"display,omitempty" fhir:"cardinality=0..1"`
	// Extension for Display
	DisplayExt *primitives.PrimitiveExtension `json:"_display,omitempty" fhir:"cardinality=0..1"`
	// relatedto | equivalent | equal | wider | subsumes | narrower | specializes | inexact | unmatched | disjoint
	Equivalence string `json:"equivalence" fhir:"cardinality=1..1,required"`
	// Extension for Equivalence
	EquivalenceExt *primitives.PrimitiveExtension `json:"_equivalence,omitempty" fhir:"cardinality=0..1"`
	// Description of status/issues in mapping
	Comment *string `json:"comment,omitempty" fhir:"cardinality=0..1"`
	// Extension for Comment
	CommentExt *primitives.PrimitiveExtension `json:"_comment,omitempty" fhir:"cardinality=0..1"`
	// Other elements required for this mapping (from context)
	DependsOn []ConceptMapGroupElementTargetDependsOn `json:"dependsOn,omitempty" fhir:"cardinality=0..*"`
	// Other concepts that this mapping also produces
	Product []ConceptMapGroupElementTargetProduct `json:"product,omitempty" fhir:"cardinality=0..*"`
}

// ConceptMapGroupElement represents a FHIR BackboneElement for ConceptMap.group.element.
type ConceptMapGroupElement struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Identifies element being mapped
	Code *string `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// Display for the code
	Display *string `json:"display,omitempty" fhir:"cardinality=0..1"`
	// Extension for Display
	DisplayExt *primitives.PrimitiveExtension `json:"_display,omitempty" fhir:"cardinality=0..1"`
	// Concept in target system for element
	Target []ConceptMapGroupElementTarget `json:"target,omitempty" fhir:"cardinality=0..*"`
}

// ConceptMapGroupUnmapped represents a FHIR BackboneElement for ConceptMap.group.unmapped.
type ConceptMapGroupUnmapped struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// provided | fixed | other-map
	Mode string `json:"mode" fhir:"cardinality=1..1,required"`
	// Extension for Mode
	ModeExt *primitives.PrimitiveExtension `json:"_mode,omitempty" fhir:"cardinality=0..1"`
	// Fixed code when mode = fixed
	Code *string `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// Display for the code
	Display *string `json:"display,omitempty" fhir:"cardinality=0..1"`
	// Extension for Display
	DisplayExt *primitives.PrimitiveExtension `json:"_display,omitempty" fhir:"cardinality=0..1"`
	// canonical reference to an additional ConceptMap to use for mapping if the source concept is unmapped
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
}

// ConceptMapGroup represents a FHIR BackboneElement for ConceptMap.group.
type ConceptMapGroup struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Source system where concepts to be mapped are defined
	Source *string `json:"source,omitempty" fhir:"cardinality=0..1"`
	// Extension for Source
	SourceExt *primitives.PrimitiveExtension `json:"_source,omitempty" fhir:"cardinality=0..1"`
	// Specific version of the  code system
	SourceVersion *string `json:"sourceVersion,omitempty" fhir:"cardinality=0..1"`
	// Extension for SourceVersion
	SourceVersionExt *primitives.PrimitiveExtension `json:"_sourceVersion,omitempty" fhir:"cardinality=0..1"`
	// Target system that the concepts are to be mapped to
	Target *string `json:"target,omitempty" fhir:"cardinality=0..1"`
	// Extension for Target
	TargetExt *primitives.PrimitiveExtension `json:"_target,omitempty" fhir:"cardinality=0..1"`
	// Specific version of the  code system
	TargetVersion *string `json:"targetVersion,omitempty" fhir:"cardinality=0..1"`
	// Extension for TargetVersion
	TargetVersionExt *primitives.PrimitiveExtension `json:"_targetVersion,omitempty" fhir:"cardinality=0..1"`
	// Mappings for a concept from the source set
	Element []ConceptMapGroupElement `json:"element,omitempty" fhir:"cardinality=1..*,required"`
	// What to do when there is no mapping for the source concept
	Unmapped *ConceptMapGroupUnmapped `json:"unmapped,omitempty" fhir:"cardinality=0..1"`
}

// ConceptMap represents a FHIR ConceptMap.
type ConceptMap struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this concept map, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the concept map
	Identifier *Identifier `json:"identifier,omitempty" fhir:"cardinality=0..1,summary"`
	// Business version of the concept map
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Name for this concept map (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this concept map (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the concept map
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for concept map (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this concept map is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// The source value set that contains the concepts that are being mapped - uri option
	SourceURI *string `json:"sourceURI,omitempty" fhir:"cardinality=0..1,summary,choice=source"`
	// Extension for SourceURI
	SourceURIExt *primitives.PrimitiveExtension `json:"_sourceURI,omitempty" fhir:"cardinality=0..1"`
	// The source value set that contains the concepts that are being mapped - canonical option
	SourceCanonical *string `json:"sourceCanonical,omitempty" fhir:"cardinality=0..1,summary,choice=source"`
	// Extension for SourceCanonical
	SourceCanonicalExt *primitives.PrimitiveExtension `json:"_sourceCanonical,omitempty" fhir:"cardinality=0..1"`
	// The target value set which provides context for the mappings - uri option
	TargetURI *string `json:"targetURI,omitempty" fhir:"cardinality=0..1,summary,choice=target"`
	// Extension for TargetURI
	TargetURIExt *primitives.PrimitiveExtension `json:"_targetURI,omitempty" fhir:"cardinality=0..1"`
	// The target value set which provides context for the mappings - canonical option
	TargetCanonical *string `json:"targetCanonical,omitempty" fhir:"cardinality=0..1,summary,choice=target"`
	// Extension for TargetCanonical
	TargetCanonicalExt *primitives.PrimitiveExtension `json:"_targetCanonical,omitempty" fhir:"cardinality=0..1"`
	// Same source and target systems
	Group []ConceptMapGroup `json:"group,omitempty" fhir:"cardinality=0..*"`
}
