// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeConsent is the FHIR resource type name for Consent.
const ResourceTypeConsent = "Consent"

// ConsentPolicy represents a FHIR BackboneElement for Consent.policy.
type ConsentPolicy struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Enforcement source for policy
	Authority *string `json:"authority,omitempty" fhir:"cardinality=0..1"`
	// Extension for Authority
	AuthorityExt *primitives.PrimitiveExtension `json:"_authority,omitempty" fhir:"cardinality=0..1"`
	// Specific policy covered by this consent
	URI *string `json:"uri,omitempty" fhir:"cardinality=0..1"`
	// Extension for URI
	URIExt *primitives.PrimitiveExtension `json:"_uri,omitempty" fhir:"cardinality=0..1"`
}

// ConsentVerification represents a FHIR BackboneElement for Consent.verification.
type ConsentVerification struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Has been verified
	Verified bool `json:"verified" fhir:"cardinality=1..1,required,summary"`
	// Extension for Verified
	VerifiedExt *primitives.PrimitiveExtension `json:"_verified,omitempty" fhir:"cardinality=0..1"`
	// Person who verified
	VerifiedWith *Reference `json:"verifiedWith,omitempty" fhir:"cardinality=0..1"`
	// When consent verified
	VerificationDate *primitives.DateTime `json:"verificationDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for VerificationDate
	VerificationDateExt *primitives.PrimitiveExtension `json:"_verificationDate,omitempty" fhir:"cardinality=0..1"`
}

// ConsentProvisionActor represents a FHIR BackboneElement for Consent.provision.actor.
type ConsentProvisionActor struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// How the actor is involved
	Role CodeableConcept `json:"role" fhir:"cardinality=1..1,required"`
	// Resource for the actor (or group, by role)
	Reference Reference `json:"reference" fhir:"cardinality=1..1,required"`
}

// ConsentProvisionData represents a FHIR BackboneElement for Consent.provision.data.
type ConsentProvisionData struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// instance | related | dependents | authoredby
	Meaning string `json:"meaning" fhir:"cardinality=1..1,required,summary"`
	// Extension for Meaning
	MeaningExt *primitives.PrimitiveExtension `json:"_meaning,omitempty" fhir:"cardinality=0..1"`
	// The actual data reference
	Reference Reference `json:"reference" fhir:"cardinality=1..1,required,summary"`
}

// ConsentProvisionProvision represents a FHIR BackboneElement for Consent.provision.provision.
type ConsentProvisionProvision struct {
}

// ConsentProvision represents a FHIR BackboneElement for Consent.provision.
type ConsentProvision struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// deny | permit
	Type *string `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// Timeframe for this rule
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Who|what controlled by this rule (or group, by role)
	Actor []ConsentProvisionActor `json:"actor,omitempty" fhir:"cardinality=0..*"`
	// Actions controlled by this rule
	Action []CodeableConcept `json:"action,omitempty" fhir:"cardinality=0..*,summary"`
	// Security Labels that define affected resources
	SecurityLabel []Coding `json:"securityLabel,omitempty" fhir:"cardinality=0..*,summary"`
	// Context of activities covered by this rule
	Purpose []Coding `json:"purpose,omitempty" fhir:"cardinality=0..*,summary"`
	// e.g. Resource Type, Profile, CDA, etc.
	Class []Coding `json:"class,omitempty" fhir:"cardinality=0..*,summary"`
	// e.g. LOINC or SNOMED CT code, etc. in the content
	Code []CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..*,summary"`
	// Timeframe for data controlled by this rule
	DataPeriod *Period `json:"dataPeriod,omitempty" fhir:"cardinality=0..1,summary"`
	// Data controlled by this rule
	Data []ConsentProvisionData `json:"data,omitempty" fhir:"cardinality=0..*,summary"`
	// Nested Exception Rules
	Provision []ConsentProvisionProvision `json:"provision,omitempty" fhir:"cardinality=0..*"`
}

// Consent represents a FHIR Consent.
type Consent struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Identifier for this record (external references)
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// draft | proposed | active | rejected | inactive | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Which of the four areas this resource covers (extensible)
	Scope CodeableConcept `json:"scope" fhir:"cardinality=1..1,required,summary"`
	// Classification of the consent statement - for indexing/retrieval
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=1..*,required,summary"`
	// Who the consent applies to
	Patient *Reference `json:"patient,omitempty" fhir:"cardinality=0..1,summary"`
	// When this Consent was created or indexed
	DateTime *primitives.DateTime `json:"dateTime,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DateTime
	DateTimeExt *primitives.PrimitiveExtension `json:"_dateTime,omitempty" fhir:"cardinality=0..1"`
	// Who is agreeing to the policy and rules
	Performer []Reference `json:"performer,omitempty" fhir:"cardinality=0..*,summary"`
	// Custodian of the consent
	Organization []Reference `json:"organization,omitempty" fhir:"cardinality=0..*,summary"`
	// Source from which this consent is taken - Attachment option
	SourceAttachment *Attachment `json:"sourceAttachment,omitempty" fhir:"cardinality=0..1,summary,choice=source"`
	// Source from which this consent is taken - Reference option
	SourceReference *Reference `json:"sourceReference,omitempty" fhir:"cardinality=0..1,summary,choice=source"`
	// Policies covered by this consent
	Policy []ConsentPolicy `json:"policy,omitempty" fhir:"cardinality=0..*"`
	// Regulation that this consents to
	PolicyRule *CodeableConcept `json:"policyRule,omitempty" fhir:"cardinality=0..1,summary"`
	// Consent Verified by patient or family
	Verification []ConsentVerification `json:"verification,omitempty" fhir:"cardinality=0..*,summary"`
	// Constraints to the base Consent.policyRule
	Provision *ConsentProvision `json:"provision,omitempty" fhir:"cardinality=0..1,summary"`
}
