// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeDeviceDefinition is the FHIR resource type name for DeviceDefinition.
const ResourceTypeDeviceDefinition = "DeviceDefinition"

// DeviceDefinitionUdiDeviceIdentifier represents a FHIR BackboneElement for DeviceDefinition.udiDeviceIdentifier.
type DeviceDefinitionUdiDeviceIdentifier struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The identifier that is to be associated with every Device that references this DeviceDefintiion for the issuer and jurisdication porvided in the DeviceDefinition.udiDeviceIdentifier
	DeviceIdentifier string `json:"deviceIdentifier" fhir:"cardinality=1..1,required"`
	// Extension for DeviceIdentifier
	DeviceIdentifierExt *primitives.PrimitiveExtension `json:"_deviceIdentifier,omitempty" fhir:"cardinality=0..1"`
	// The organization that assigns the identifier algorithm
	Issuer string `json:"issuer" fhir:"cardinality=1..1,required"`
	// Extension for Issuer
	IssuerExt *primitives.PrimitiveExtension `json:"_issuer,omitempty" fhir:"cardinality=0..1"`
	// The jurisdiction to which the deviceIdentifier applies
	Jurisdiction string `json:"jurisdiction" fhir:"cardinality=1..1,required"`
	// Extension for Jurisdiction
	JurisdictionExt *primitives.PrimitiveExtension `json:"_jurisdiction,omitempty" fhir:"cardinality=0..1"`
}

// DeviceDefinitionDeviceName represents a FHIR BackboneElement for DeviceDefinition.deviceName.
type DeviceDefinitionDeviceName struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The name of the device
	Name string `json:"name" fhir:"cardinality=1..1,required"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// udi-label-name | user-friendly-name | patient-reported-name | manufacturer-name | model-name | other
	Type string `json:"type" fhir:"cardinality=1..1,required"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
}

// DeviceDefinitionSpecialization represents a FHIR BackboneElement for DeviceDefinition.specialization.
type DeviceDefinitionSpecialization struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The standard that is used to operate and communicate
	SystemType string `json:"systemType" fhir:"cardinality=1..1,required"`
	// Extension for SystemType
	SystemTypeExt *primitives.PrimitiveExtension `json:"_systemType,omitempty" fhir:"cardinality=0..1"`
	// The version of the standard that is used to operate and communicate
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
}

// DeviceDefinitionCapability represents a FHIR BackboneElement for DeviceDefinition.capability.
type DeviceDefinitionCapability struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of capability
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required"`
	// Description of capability
	Description []CodeableConcept `json:"description,omitempty" fhir:"cardinality=0..*"`
}

// DeviceDefinitionProperty represents a FHIR BackboneElement for DeviceDefinition.property.
type DeviceDefinitionProperty struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Code that specifies the property DeviceDefinitionPropetyCode (Extensible)
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required"`
	// Property value as a quantity
	ValueQuantity []Quantity `json:"valueQuantity,omitempty" fhir:"cardinality=0..*"`
	// Property value as a code, e.g., NTP4 (synced to NTP)
	ValueCode []CodeableConcept `json:"valueCode,omitempty" fhir:"cardinality=0..*"`
}

// DeviceDefinitionMaterial represents a FHIR BackboneElement for DeviceDefinition.material.
type DeviceDefinitionMaterial struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The substance
	Substance CodeableConcept `json:"substance" fhir:"cardinality=1..1,required"`
	// Indicates an alternative material of the device
	Alternate *bool `json:"alternate,omitempty" fhir:"cardinality=0..1"`
	// Extension for Alternate
	AlternateExt *primitives.PrimitiveExtension `json:"_alternate,omitempty" fhir:"cardinality=0..1"`
	// Whether the substance is a known or suspected allergen
	AllergenicIndicator *bool `json:"allergenicIndicator,omitempty" fhir:"cardinality=0..1"`
	// Extension for AllergenicIndicator
	AllergenicIndicatorExt *primitives.PrimitiveExtension `json:"_allergenicIndicator,omitempty" fhir:"cardinality=0..1"`
}

// DeviceDefinition represents a FHIR DeviceDefinition.
type DeviceDefinition struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Instance identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// Unique Device Identifier (UDI) Barcode string
	UdiDeviceIdentifier []DeviceDefinitionUdiDeviceIdentifier `json:"udiDeviceIdentifier,omitempty" fhir:"cardinality=0..*"`
	// Name of device manufacturer - string option
	ManufacturerString *string `json:"manufacturerString,omitempty" fhir:"cardinality=0..1,choice=manufacturer"`
	// Extension for ManufacturerString
	ManufacturerStringExt *primitives.PrimitiveExtension `json:"_manufacturerString,omitempty" fhir:"cardinality=0..1"`
	// Name of device manufacturer - Reference option
	ManufacturerReference *Reference `json:"manufacturerReference,omitempty" fhir:"cardinality=0..1,choice=manufacturer"`
	// A name given to the device to identify it
	DeviceName []DeviceDefinitionDeviceName `json:"deviceName,omitempty" fhir:"cardinality=0..*"`
	// The model number for the device
	ModelNumber *string `json:"modelNumber,omitempty" fhir:"cardinality=0..1"`
	// Extension for ModelNumber
	ModelNumberExt *primitives.PrimitiveExtension `json:"_modelNumber,omitempty" fhir:"cardinality=0..1"`
	// What kind of device or device system this is
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// The capabilities supported on a  device, the standards to which the device conforms for a particular purpose, and used for the communication
	Specialization []DeviceDefinitionSpecialization `json:"specialization,omitempty" fhir:"cardinality=0..*"`
	// Available versions
	Version []string `json:"version,omitempty" fhir:"cardinality=0..*"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Safety characteristics of the device
	Safety []CodeableConcept `json:"safety,omitempty" fhir:"cardinality=0..*,summary"`
	// Shelf Life and storage information
	ShelfLifeStorage []ProductShelfLife `json:"shelfLifeStorage,omitempty" fhir:"cardinality=0..*"`
	// Dimensions, color etc.
	PhysicalCharacteristics *ProdCharacteristic `json:"physicalCharacteristics,omitempty" fhir:"cardinality=0..1"`
	// Language code for the human-readable text strings produced by the device (all supported)
	LanguageCode []CodeableConcept `json:"languageCode,omitempty" fhir:"cardinality=0..*"`
	// Device capabilities
	Capability []DeviceDefinitionCapability `json:"capability,omitempty" fhir:"cardinality=0..*"`
	// The actual configuration settings of a device as it actually operates, e.g., regulation status, time properties
	Property []DeviceDefinitionProperty `json:"property,omitempty" fhir:"cardinality=0..*"`
	// Organization responsible for device
	Owner *Reference `json:"owner,omitempty" fhir:"cardinality=0..1"`
	// Details for human/organization for support
	Contact []ContactPoint `json:"contact,omitempty" fhir:"cardinality=0..*"`
	// Network address to contact device
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Access to on-line information
	OnlineInformation *string `json:"onlineInformation,omitempty" fhir:"cardinality=0..1"`
	// Extension for OnlineInformation
	OnlineInformationExt *primitives.PrimitiveExtension `json:"_onlineInformation,omitempty" fhir:"cardinality=0..1"`
	// Device notes and comments
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// The quantity of the device present in the packaging (e.g. the number of devices present in a pack, or the number of devices in the same package of the medicinal product)
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// The parent device it can be part of
	ParentDevice *Reference `json:"parentDevice,omitempty" fhir:"cardinality=0..1,summary"`
	// A substance used to create the material(s) of which the device is made
	Material []DeviceDefinitionMaterial `json:"material,omitempty" fhir:"cardinality=0..*"`
}
