// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeDevice is the FHIR resource type name for Device.
const ResourceTypeDevice = "Device"

// DeviceUdiCarrier represents a FHIR BackboneElement for Device.udiCarrier.
type DeviceUdiCarrier struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Mandatory fixed portion of UDI
	DeviceIdentifier *string `json:"deviceIdentifier,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DeviceIdentifier
	DeviceIdentifierExt *primitives.PrimitiveExtension `json:"_deviceIdentifier,omitempty" fhir:"cardinality=0..1"`
	// UDI Issuing Organization
	Issuer *string `json:"issuer,omitempty" fhir:"cardinality=0..1"`
	// Extension for Issuer
	IssuerExt *primitives.PrimitiveExtension `json:"_issuer,omitempty" fhir:"cardinality=0..1"`
	// Regional UDI authority
	Jurisdiction *string `json:"jurisdiction,omitempty" fhir:"cardinality=0..1"`
	// Extension for Jurisdiction
	JurisdictionExt *primitives.PrimitiveExtension `json:"_jurisdiction,omitempty" fhir:"cardinality=0..1"`
	// UDI Machine Readable Barcode String
	CarrierAIDC *string `json:"carrierAIDC,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for CarrierAIDC
	CarrierAIDCExt *primitives.PrimitiveExtension `json:"_carrierAIDC,omitempty" fhir:"cardinality=0..1"`
	// UDI Human Readable Barcode String
	CarrierHRF *string `json:"carrierHRF,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for CarrierHRF
	CarrierHRFExt *primitives.PrimitiveExtension `json:"_carrierHRF,omitempty" fhir:"cardinality=0..1"`
	// barcode | rfid | manual +
	EntryType *string `json:"entryType,omitempty" fhir:"cardinality=0..1"`
	// Extension for EntryType
	EntryTypeExt *primitives.PrimitiveExtension `json:"_entryType,omitempty" fhir:"cardinality=0..1"`
}

// DeviceDeviceName represents a FHIR BackboneElement for Device.deviceName.
type DeviceDeviceName struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The name of the device
	Name string `json:"name" fhir:"cardinality=1..1,required"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// udi-label-name | user-friendly-name | patient-reported-name | manufacturer-name | model-name | other
	Type string `json:"type" fhir:"cardinality=1..1,required"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
}

// DeviceSpecialization represents a FHIR BackboneElement for Device.specialization.
type DeviceSpecialization struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The standard that is used to operate and communicate
	SystemType CodeableConcept `json:"systemType" fhir:"cardinality=1..1,required"`
	// The version of the standard that is used to operate and communicate
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
}

// DeviceVersion represents a FHIR BackboneElement for Device.version.
type DeviceVersion struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The type of the device version
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// A single component of the device version
	Component *Identifier `json:"component,omitempty" fhir:"cardinality=0..1"`
	// The version text
	Value string `json:"value" fhir:"cardinality=1..1,required"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
}

// DeviceProperty represents a FHIR BackboneElement for Device.property.
type DeviceProperty struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Code that specifies the property DeviceDefinitionPropetyCode (Extensible)
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required"`
	// Property value as a quantity
	ValueQuantity []Quantity `json:"valueQuantity,omitempty" fhir:"cardinality=0..*"`
	// Property value as a code, e.g., NTP4 (synced to NTP)
	ValueCode []CodeableConcept `json:"valueCode,omitempty" fhir:"cardinality=0..*"`
}

// Device represents a FHIR Device.
type Device struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Instance identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// The reference to the definition for the device
	Definition *Reference `json:"definition,omitempty" fhir:"cardinality=0..1"`
	// Unique Device Identifier (UDI) Barcode string
	UdiCarrier []DeviceUdiCarrier `json:"udiCarrier,omitempty" fhir:"cardinality=0..*,summary"`
	// active | inactive | entered-in-error | unknown
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// online | paused | standby | offline | not-ready | transduc-discon | hw-discon | off
	StatusReason []CodeableConcept `json:"statusReason,omitempty" fhir:"cardinality=0..*"`
	// The distinct identification string
	DistinctIdentifier *string `json:"distinctIdentifier,omitempty" fhir:"cardinality=0..1"`
	// Extension for DistinctIdentifier
	DistinctIdentifierExt *primitives.PrimitiveExtension `json:"_distinctIdentifier,omitempty" fhir:"cardinality=0..1"`
	// Name of device manufacturer
	Manufacturer *string `json:"manufacturer,omitempty" fhir:"cardinality=0..1"`
	// Extension for Manufacturer
	ManufacturerExt *primitives.PrimitiveExtension `json:"_manufacturer,omitempty" fhir:"cardinality=0..1"`
	// Date when the device was made
	ManufactureDate *primitives.DateTime `json:"manufactureDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ManufactureDate
	ManufactureDateExt *primitives.PrimitiveExtension `json:"_manufactureDate,omitempty" fhir:"cardinality=0..1"`
	// Date and time of expiry of this device (if applicable)
	ExpirationDate *primitives.DateTime `json:"expirationDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ExpirationDate
	ExpirationDateExt *primitives.PrimitiveExtension `json:"_expirationDate,omitempty" fhir:"cardinality=0..1"`
	// Lot number of manufacture
	LotNumber *string `json:"lotNumber,omitempty" fhir:"cardinality=0..1"`
	// Extension for LotNumber
	LotNumberExt *primitives.PrimitiveExtension `json:"_lotNumber,omitempty" fhir:"cardinality=0..1"`
	// Serial number assigned by the manufacturer
	SerialNumber *string `json:"serialNumber,omitempty" fhir:"cardinality=0..1"`
	// Extension for SerialNumber
	SerialNumberExt *primitives.PrimitiveExtension `json:"_serialNumber,omitempty" fhir:"cardinality=0..1"`
	// The name of the device as given by the manufacturer
	DeviceName []DeviceDeviceName `json:"deviceName,omitempty" fhir:"cardinality=0..*"`
	// The model number for the device
	ModelNumber *string `json:"modelNumber,omitempty" fhir:"cardinality=0..1"`
	// Extension for ModelNumber
	ModelNumberExt *primitives.PrimitiveExtension `json:"_modelNumber,omitempty" fhir:"cardinality=0..1"`
	// The part number of the device
	PartNumber *string `json:"partNumber,omitempty" fhir:"cardinality=0..1"`
	// Extension for PartNumber
	PartNumberExt *primitives.PrimitiveExtension `json:"_partNumber,omitempty" fhir:"cardinality=0..1"`
	// The kind or type of device
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// The capabilities supported on a  device, the standards to which the device conforms for a particular purpose, and used for the communication
	Specialization []DeviceSpecialization `json:"specialization,omitempty" fhir:"cardinality=0..*"`
	// The actual design of the device or software version running on the device
	Version []DeviceVersion `json:"version,omitempty" fhir:"cardinality=0..*"`
	// The actual configuration settings of a device as it actually operates, e.g., regulation status, time properties
	Property []DeviceProperty `json:"property,omitempty" fhir:"cardinality=0..*"`
	// Patient to whom Device is affixed
	Patient *Reference `json:"patient,omitempty" fhir:"cardinality=0..1"`
	// Organization responsible for device
	Owner *Reference `json:"owner,omitempty" fhir:"cardinality=0..1"`
	// Details for human/organization for support
	Contact []ContactPoint `json:"contact,omitempty" fhir:"cardinality=0..*"`
	// Where the device is found
	Location *Reference `json:"location,omitempty" fhir:"cardinality=0..1"`
	// Network address to contact device
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Device notes and comments
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// Safety Characteristics of Device
	Safety []CodeableConcept `json:"safety,omitempty" fhir:"cardinality=0..*,summary"`
	// The parent device
	Parent *Reference `json:"parent,omitempty" fhir:"cardinality=0..1"`
}
