// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeDeviceUseStatement is the FHIR resource type name for DeviceUseStatement.
const ResourceTypeDeviceUseStatement = "DeviceUseStatement"

// DeviceUseStatement represents a FHIR DeviceUseStatement.
type DeviceUseStatement struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External identifier for this record
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Fulfills plan, proposal or order
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// active | completed | entered-in-error +
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Patient using device
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// Supporting information
	DerivedFrom []Reference `json:"derivedFrom,omitempty" fhir:"cardinality=0..*,summary"`
	// How often  the device was used - Timing option
	TimingTiming *Timing `json:"timingTiming,omitempty" fhir:"cardinality=0..1,summary,choice=timing"`
	// How often  the device was used - Period option
	TimingPeriod *Period `json:"timingPeriod,omitempty" fhir:"cardinality=0..1,summary,choice=timing"`
	// How often  the device was used - dateTime option
	TimingDateTime *primitives.DateTime `json:"timingDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=timing"`
	// Extension for TimingDateTime
	TimingDateTimeExt *primitives.PrimitiveExtension `json:"_timingDateTime,omitempty" fhir:"cardinality=0..1"`
	// When statement was recorded
	RecordedOn *primitives.DateTime `json:"recordedOn,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for RecordedOn
	RecordedOnExt *primitives.PrimitiveExtension `json:"_recordedOn,omitempty" fhir:"cardinality=0..1"`
	// Who made the statement
	Source *Reference `json:"source,omitempty" fhir:"cardinality=0..1,summary"`
	// Reference to device used
	Device Reference `json:"device" fhir:"cardinality=1..1,required,summary"`
	// Why device was used
	ReasonCode []CodeableConcept `json:"reasonCode,omitempty" fhir:"cardinality=0..*,summary"`
	// Why was DeviceUseStatement performed?
	ReasonReference []Reference `json:"reasonReference,omitempty" fhir:"cardinality=0..*,summary"`
	// Target body site
	BodySite *CodeableConcept `json:"bodySite,omitempty" fhir:"cardinality=0..1,summary"`
	// Addition details (comments, instructions)
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
}
