// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeDiagnosticReport is the FHIR resource type name for DiagnosticReport.
const ResourceTypeDiagnosticReport = "DiagnosticReport"

// DiagnosticReportMedia represents a FHIR BackboneElement for DiagnosticReport.media.
type DiagnosticReportMedia struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Comment about the image (e.g. explanation)
	Comment *string `json:"comment,omitempty" fhir:"cardinality=0..1"`
	// Extension for Comment
	CommentExt *primitives.PrimitiveExtension `json:"_comment,omitempty" fhir:"cardinality=0..1"`
	// Reference to the image source
	Link Reference `json:"link" fhir:"cardinality=1..1,required,summary"`
}

// DiagnosticReport represents a FHIR DiagnosticReport.
type DiagnosticReport struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier for report
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// What was requested
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*"`
	// registered | partial | preliminary | final +
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Service category
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Name/Code for this diagnostic report
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required,summary"`
	// The subject of the report - usually, but not always, the patient
	Subject *Reference `json:"subject,omitempty" fhir:"cardinality=0..1,summary"`
	// Health care event when test ordered
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// Clinically relevant time/time-period for report - dateTime option
	EffectiveDateTime *primitives.DateTime `json:"effectiveDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=effective"`
	// Extension for EffectiveDateTime
	EffectiveDateTimeExt *primitives.PrimitiveExtension `json:"_effectiveDateTime,omitempty" fhir:"cardinality=0..1"`
	// Clinically relevant time/time-period for report - Period option
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary,choice=effective"`
	// DateTime this version was made
	Issued *primitives.Instant `json:"issued,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Issued
	IssuedExt *primitives.PrimitiveExtension `json:"_issued,omitempty" fhir:"cardinality=0..1"`
	// Responsible Diagnostic Service
	Performer []Reference `json:"performer,omitempty" fhir:"cardinality=0..*,summary"`
	// Primary result interpreter
	ResultsInterpreter []Reference `json:"resultsInterpreter,omitempty" fhir:"cardinality=0..*,summary"`
	// Specimens this report is based on
	Specimen []Reference `json:"specimen,omitempty" fhir:"cardinality=0..*"`
	// Observations
	Result []Reference `json:"result,omitempty" fhir:"cardinality=0..*"`
	// Reference to full details of imaging associated with the diagnostic report
	ImagingStudy []Reference `json:"imagingStudy,omitempty" fhir:"cardinality=0..*"`
	// Key images associated with this report
	Media []DiagnosticReportMedia `json:"media,omitempty" fhir:"cardinality=0..*,summary"`
	// Clinical conclusion (interpretation) of test results
	Conclusion *string `json:"conclusion,omitempty" fhir:"cardinality=0..1"`
	// Extension for Conclusion
	ConclusionExt *primitives.PrimitiveExtension `json:"_conclusion,omitempty" fhir:"cardinality=0..1"`
	// Codes for the clinical conclusion of test results
	ConclusionCode []CodeableConcept `json:"conclusionCode,omitempty" fhir:"cardinality=0..*"`
	// Entire report as issued
	PresentedForm []Attachment `json:"presentedForm,omitempty" fhir:"cardinality=0..*"`
}
