// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeEffectEvidenceSynthesis is the FHIR resource type name for EffectEvidenceSynthesis.
const ResourceTypeEffectEvidenceSynthesis = "EffectEvidenceSynthesis"

// EffectEvidenceSynthesisSampleSize represents a FHIR BackboneElement for EffectEvidenceSynthesis.sampleSize.
type EffectEvidenceSynthesisSampleSize struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of sample size
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// How many studies?
	NumberOfStudies *int `json:"numberOfStudies,omitempty" fhir:"cardinality=0..1"`
	// Extension for NumberOfStudies
	NumberOfStudiesExt *primitives.PrimitiveExtension `json:"_numberOfStudies,omitempty" fhir:"cardinality=0..1"`
	// How many participants?
	NumberOfParticipants *int `json:"numberOfParticipants,omitempty" fhir:"cardinality=0..1"`
	// Extension for NumberOfParticipants
	NumberOfParticipantsExt *primitives.PrimitiveExtension `json:"_numberOfParticipants,omitempty" fhir:"cardinality=0..1"`
}

// EffectEvidenceSynthesisResultsByExposure represents a FHIR BackboneElement for EffectEvidenceSynthesis.resultsByExposure.
type EffectEvidenceSynthesisResultsByExposure struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of results by exposure
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// exposure | exposure-alternative
	ExposureState *string `json:"exposureState,omitempty" fhir:"cardinality=0..1"`
	// Extension for ExposureState
	ExposureStateExt *primitives.PrimitiveExtension `json:"_exposureState,omitempty" fhir:"cardinality=0..1"`
	// Variant exposure states
	VariantState *CodeableConcept `json:"variantState,omitempty" fhir:"cardinality=0..1"`
	// Risk evidence synthesis
	RiskEvidenceSynthesis Reference `json:"riskEvidenceSynthesis" fhir:"cardinality=1..1,required"`
}

// EffectEvidenceSynthesisEffectEstimatePrecisionEstimate represents a FHIR BackboneElement for EffectEvidenceSynthesis.effectEstimate.precisionEstimate.
type EffectEvidenceSynthesisEffectEstimatePrecisionEstimate struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of precision estimate
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Level of confidence interval
	Level *float64 `json:"level,omitempty" fhir:"cardinality=0..1"`
	// Extension for Level
	LevelExt *primitives.PrimitiveExtension `json:"_level,omitempty" fhir:"cardinality=0..1"`
	// Lower bound
	From *float64 `json:"from,omitempty" fhir:"cardinality=0..1"`
	// Extension for From
	FromExt *primitives.PrimitiveExtension `json:"_from,omitempty" fhir:"cardinality=0..1"`
	// Upper bound
	To *float64 `json:"to,omitempty" fhir:"cardinality=0..1"`
	// Extension for To
	ToExt *primitives.PrimitiveExtension `json:"_to,omitempty" fhir:"cardinality=0..1"`
}

// EffectEvidenceSynthesisEffectEstimate represents a FHIR BackboneElement for EffectEvidenceSynthesis.effectEstimate.
type EffectEvidenceSynthesisEffectEstimate struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of effect estimate
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Type of efffect estimate
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Variant exposure states
	VariantState *CodeableConcept `json:"variantState,omitempty" fhir:"cardinality=0..1"`
	// Point estimate
	Value *float64 `json:"value,omitempty" fhir:"cardinality=0..1"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
	// What unit is the outcome described in?
	UnitOfMeasure *CodeableConcept `json:"unitOfMeasure,omitempty" fhir:"cardinality=0..1"`
	// How precise the estimate is
	PrecisionEstimate []EffectEvidenceSynthesisEffectEstimatePrecisionEstimate `json:"precisionEstimate,omitempty" fhir:"cardinality=0..*"`
}

// EffectEvidenceSynthesisCertaintyCertaintySubcomponent represents a FHIR BackboneElement for EffectEvidenceSynthesis.certainty.certaintySubcomponent.
type EffectEvidenceSynthesisCertaintyCertaintySubcomponent struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of subcomponent of certainty rating
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Subcomponent certainty rating
	Rating []CodeableConcept `json:"rating,omitempty" fhir:"cardinality=0..*"`
	// Used for footnotes or explanatory notes
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
}

// EffectEvidenceSynthesisCertainty represents a FHIR BackboneElement for EffectEvidenceSynthesis.certainty.
type EffectEvidenceSynthesisCertainty struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Certainty rating
	Rating []CodeableConcept `json:"rating,omitempty" fhir:"cardinality=0..*"`
	// Used for footnotes or explanatory notes
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// A component that contributes to the overall certainty
	CertaintySubcomponent []EffectEvidenceSynthesisCertaintyCertaintySubcomponent `json:"certaintySubcomponent,omitempty" fhir:"cardinality=0..*"`
}

// EffectEvidenceSynthesis represents a FHIR EffectEvidenceSynthesis.
type EffectEvidenceSynthesis struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this effect evidence synthesis, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the effect evidence synthesis
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the effect evidence synthesis
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Name for this effect evidence synthesis (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this effect evidence synthesis (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the effect evidence synthesis
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Used for footnotes or explanatory notes
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for effect evidence synthesis (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// When the effect evidence synthesis was approved by publisher
	ApprovalDate *primitives.Date `json:"approvalDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ApprovalDate
	ApprovalDateExt *primitives.PrimitiveExtension `json:"_approvalDate,omitempty" fhir:"cardinality=0..1"`
	// When the effect evidence synthesis was last reviewed
	LastReviewDate *primitives.Date `json:"lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for LastReviewDate
	LastReviewDateExt *primitives.PrimitiveExtension `json:"_lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// When the effect evidence synthesis is expected to be used
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary"`
	// The category of the EffectEvidenceSynthesis, such as Education, Treatment, Assessment, etc.
	Topic []CodeableConcept `json:"topic,omitempty" fhir:"cardinality=0..*"`
	// Who authored the content
	Author []ContactDetail `json:"author,omitempty" fhir:"cardinality=0..*"`
	// Who edited the content
	Editor []ContactDetail `json:"editor,omitempty" fhir:"cardinality=0..*"`
	// Who reviewed the content
	Reviewer []ContactDetail `json:"reviewer,omitempty" fhir:"cardinality=0..*"`
	// Who endorsed the content
	Endorser []ContactDetail `json:"endorser,omitempty" fhir:"cardinality=0..*"`
	// Additional documentation, citations, etc.
	RelatedArtifact []RelatedArtifact `json:"relatedArtifact,omitempty" fhir:"cardinality=0..*"`
	// Type of synthesis
	SynthesisType *CodeableConcept `json:"synthesisType,omitempty" fhir:"cardinality=0..1"`
	// Type of study
	StudyType *CodeableConcept `json:"studyType,omitempty" fhir:"cardinality=0..1"`
	// What population?
	Population Reference `json:"population" fhir:"cardinality=1..1,required,summary"`
	// What exposure?
	Exposure Reference `json:"exposure" fhir:"cardinality=1..1,required,summary"`
	// What comparison exposure?
	ExposureAlternative Reference `json:"exposureAlternative" fhir:"cardinality=1..1,required,summary"`
	// What outcome?
	Outcome Reference `json:"outcome" fhir:"cardinality=1..1,required,summary"`
	// What sample size was involved?
	SampleSize *EffectEvidenceSynthesisSampleSize `json:"sampleSize,omitempty" fhir:"cardinality=0..1"`
	// What was the result per exposure?
	ResultsByExposure []EffectEvidenceSynthesisResultsByExposure `json:"resultsByExposure,omitempty" fhir:"cardinality=0..*"`
	// What was the estimated effect
	EffectEstimate []EffectEvidenceSynthesisEffectEstimate `json:"effectEstimate,omitempty" fhir:"cardinality=0..*,summary"`
	// How certain is the effect
	Certainty []EffectEvidenceSynthesisCertainty `json:"certainty,omitempty" fhir:"cardinality=0..*"`
}
