// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeEpisodeOfCare is the FHIR resource type name for EpisodeOfCare.
const ResourceTypeEpisodeOfCare = "EpisodeOfCare"

// EpisodeOfCareStatusHistory represents a FHIR BackboneElement for EpisodeOfCare.statusHistory.
type EpisodeOfCareStatusHistory struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// planned | waitlist | active | onhold | finished | cancelled | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Duration the EpisodeOfCare was in the specified status
	Period Period `json:"period" fhir:"cardinality=1..1,required"`
}

// EpisodeOfCareDiagnosis represents a FHIR BackboneElement for EpisodeOfCare.diagnosis.
type EpisodeOfCareDiagnosis struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Conditions/problems/diagnoses this episode of care is for
	Condition Reference `json:"condition" fhir:"cardinality=1..1,required,summary"`
	// Role that this diagnosis has within the episode of care (e.g. admission, billing, discharge …)
	Role *CodeableConcept `json:"role,omitempty" fhir:"cardinality=0..1,summary"`
	// Ranking of the diagnosis (for each role type)
	Rank *int `json:"rank,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Rank
	RankExt *primitives.PrimitiveExtension `json:"_rank,omitempty" fhir:"cardinality=0..1"`
}

// EpisodeOfCare represents a FHIR EpisodeOfCare.
type EpisodeOfCare struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business Identifier(s) relevant for this EpisodeOfCare
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// planned | waitlist | active | onhold | finished | cancelled | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Past list of status codes (the current status may be included to cover the start date of the status)
	StatusHistory []EpisodeOfCareStatusHistory `json:"statusHistory,omitempty" fhir:"cardinality=0..*"`
	// Type/class  - e.g. specialist referral, disease management
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*,summary"`
	// The list of diagnosis relevant to this episode of care
	Diagnosis []EpisodeOfCareDiagnosis `json:"diagnosis,omitempty" fhir:"cardinality=0..*,summary"`
	// The patient who is the focus of this episode of care
	Patient Reference `json:"patient" fhir:"cardinality=1..1,required,summary"`
	// Organization that assumes care
	ManagingOrganization *Reference `json:"managingOrganization,omitempty" fhir:"cardinality=0..1,summary"`
	// Interval during responsibility is assumed
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Originating Referral Request(s)
	ReferralRequest []Reference `json:"referralRequest,omitempty" fhir:"cardinality=0..*"`
	// Care manager/care coordinator for the patient
	CareManager *Reference `json:"careManager,omitempty" fhir:"cardinality=0..1"`
	// Other practitioners facilitating this episode of care
	Team []Reference `json:"team,omitempty" fhir:"cardinality=0..*"`
	// The set of accounts that may be used for billing for this EpisodeOfCare
	Account []Reference `json:"account,omitempty" fhir:"cardinality=0..*"`
}
