// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeEvidenceVariable is the FHIR resource type name for EvidenceVariable.
const ResourceTypeEvidenceVariable = "EvidenceVariable"

// EvidenceVariableCharacteristic represents a FHIR BackboneElement for EvidenceVariable.characteristic.
type EvidenceVariableCharacteristic struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the characteristic
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// What code or expression defines members? - Reference option
	DefinitionReference Reference `json:"definitionReference" fhir:"cardinality=1..1,required,summary,choice=definition"`
	// What code or expression defines members? - canonical option
	DefinitionCanonical string `json:"definitionCanonical" fhir:"cardinality=1..1,required,summary,choice=definition"`
	// Extension for DefinitionCanonical
	DefinitionCanonicalExt *primitives.PrimitiveExtension `json:"_definitionCanonical,omitempty" fhir:"cardinality=0..1"`
	// What code or expression defines members? - CodeableConcept option
	DefinitionCodeableConcept CodeableConcept `json:"definitionCodeableConcept" fhir:"cardinality=1..1,required,summary,choice=definition"`
	// What code or expression defines members? - Expression option
	DefinitionExpression Expression `json:"definitionExpression" fhir:"cardinality=1..1,required,summary,choice=definition"`
	// What code or expression defines members? - DataRequirement option
	DefinitionDataRequirement DataRequirement `json:"definitionDataRequirement" fhir:"cardinality=1..1,required,summary,choice=definition"`
	// What code or expression defines members? - TriggerDefinition option
	DefinitionTriggerDefinition TriggerDefinition `json:"definitionTriggerDefinition" fhir:"cardinality=1..1,required,summary,choice=definition"`
	// What code/value pairs define members?
	UsageContext []UsageContext `json:"usageContext,omitempty" fhir:"cardinality=0..*"`
	// Whether the characteristic includes or excludes members
	Exclude *bool `json:"exclude,omitempty" fhir:"cardinality=0..1"`
	// Extension for Exclude
	ExcludeExt *primitives.PrimitiveExtension `json:"_exclude,omitempty" fhir:"cardinality=0..1"`
	// What time period do participants cover - dateTime option
	ParticipantEffectiveDateTime *primitives.DateTime `json:"participantEffectiveDateTime,omitempty" fhir:"cardinality=0..1,choice=participantEffective"`
	// Extension for ParticipantEffectiveDateTime
	ParticipantEffectiveDateTimeExt *primitives.PrimitiveExtension `json:"_participantEffectiveDateTime,omitempty" fhir:"cardinality=0..1"`
	// What time period do participants cover - Period option
	ParticipantEffectivePeriod *Period `json:"participantEffectivePeriod,omitempty" fhir:"cardinality=0..1,choice=participantEffective"`
	// What time period do participants cover - Duration option
	ParticipantEffectiveDuration *Duration `json:"participantEffectiveDuration,omitempty" fhir:"cardinality=0..1,choice=participantEffective"`
	// What time period do participants cover - Timing option
	ParticipantEffectiveTiming *Timing `json:"participantEffectiveTiming,omitempty" fhir:"cardinality=0..1,choice=participantEffective"`
	// Observation time from study start
	TimeFromStart *Duration `json:"timeFromStart,omitempty" fhir:"cardinality=0..1"`
	// mean | median | mean-of-mean | mean-of-median | median-of-mean | median-of-median
	GroupMeasure *string `json:"groupMeasure,omitempty" fhir:"cardinality=0..1"`
	// Extension for GroupMeasure
	GroupMeasureExt *primitives.PrimitiveExtension `json:"_groupMeasure,omitempty" fhir:"cardinality=0..1"`
}

// EvidenceVariable represents a FHIR EvidenceVariable.
type EvidenceVariable struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this evidence variable, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the evidence variable
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the evidence variable
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Name for this evidence variable (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this evidence variable (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Title for use in informal contexts
	ShortTitle *string `json:"shortTitle,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ShortTitle
	ShortTitleExt *primitives.PrimitiveExtension `json:"_shortTitle,omitempty" fhir:"cardinality=0..1"`
	// Subordinate title of the EvidenceVariable
	Subtitle *string `json:"subtitle,omitempty" fhir:"cardinality=0..1"`
	// Extension for Subtitle
	SubtitleExt *primitives.PrimitiveExtension `json:"_subtitle,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the evidence variable
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Used for footnotes or explanatory notes
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for evidence variable (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// When the evidence variable was approved by publisher
	ApprovalDate *primitives.Date `json:"approvalDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ApprovalDate
	ApprovalDateExt *primitives.PrimitiveExtension `json:"_approvalDate,omitempty" fhir:"cardinality=0..1"`
	// When the evidence variable was last reviewed
	LastReviewDate *primitives.Date `json:"lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for LastReviewDate
	LastReviewDateExt *primitives.PrimitiveExtension `json:"_lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// When the evidence variable is expected to be used
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary"`
	// The category of the EvidenceVariable, such as Education, Treatment, Assessment, etc.
	Topic []CodeableConcept `json:"topic,omitempty" fhir:"cardinality=0..*"`
	// Who authored the content
	Author []ContactDetail `json:"author,omitempty" fhir:"cardinality=0..*"`
	// Who edited the content
	Editor []ContactDetail `json:"editor,omitempty" fhir:"cardinality=0..*"`
	// Who reviewed the content
	Reviewer []ContactDetail `json:"reviewer,omitempty" fhir:"cardinality=0..*"`
	// Who endorsed the content
	Endorser []ContactDetail `json:"endorser,omitempty" fhir:"cardinality=0..*"`
	// Additional documentation, citations, etc.
	RelatedArtifact []RelatedArtifact `json:"relatedArtifact,omitempty" fhir:"cardinality=0..*"`
	// dichotomous | continuous | descriptive
	Type *string `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// What defines the members of the evidence element
	Characteristic []EvidenceVariableCharacteristic `json:"characteristic,omitempty" fhir:"cardinality=1..*,required,summary"`
}
