// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeExampleScenario is the FHIR resource type name for ExampleScenario.
const ResourceTypeExampleScenario = "ExampleScenario"

// ExampleScenarioActor represents a FHIR BackboneElement for ExampleScenario.actor.
type ExampleScenarioActor struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// ID or acronym of the actor
	ActorId string `json:"actorId" fhir:"cardinality=1..1,required"`
	// Extension for ActorId
	ActorIdExt *primitives.PrimitiveExtension `json:"_actorId,omitempty" fhir:"cardinality=0..1"`
	// person | entity
	Type string `json:"type" fhir:"cardinality=1..1,required"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// The name of the actor as shown in the page
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// The description of the actor
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
}

// ExampleScenarioInstanceVersion represents a FHIR BackboneElement for ExampleScenario.instance.version.
type ExampleScenarioInstanceVersion struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The identifier of a specific version of a resource
	VersionId string `json:"versionId" fhir:"cardinality=1..1,required"`
	// Extension for VersionId
	VersionIdExt *primitives.PrimitiveExtension `json:"_versionId,omitempty" fhir:"cardinality=0..1"`
	// The description of the resource version
	Description string `json:"description" fhir:"cardinality=1..1,required"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
}

// ExampleScenarioInstanceContainedInstance represents a FHIR BackboneElement for ExampleScenario.instance.containedInstance.
type ExampleScenarioInstanceContainedInstance struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Each resource contained in the instance
	ResourceId string `json:"resourceId" fhir:"cardinality=1..1,required"`
	// Extension for ResourceId
	ResourceIdExt *primitives.PrimitiveExtension `json:"_resourceId,omitempty" fhir:"cardinality=0..1"`
	// A specific version of a resource contained in the instance
	VersionId *string `json:"versionId,omitempty" fhir:"cardinality=0..1"`
	// Extension for VersionId
	VersionIdExt *primitives.PrimitiveExtension `json:"_versionId,omitempty" fhir:"cardinality=0..1"`
}

// ExampleScenarioInstance represents a FHIR BackboneElement for ExampleScenario.instance.
type ExampleScenarioInstance struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The id of the resource for referencing
	ResourceId string `json:"resourceId" fhir:"cardinality=1..1,required"`
	// Extension for ResourceId
	ResourceIdExt *primitives.PrimitiveExtension `json:"_resourceId,omitempty" fhir:"cardinality=0..1"`
	// The type of the resource
	ResourceType string `json:"resourceType" fhir:"cardinality=1..1,required"`
	// Extension for ResourceType
	ResourceTypeExt *primitives.PrimitiveExtension `json:"_resourceType,omitempty" fhir:"cardinality=0..1"`
	// A short name for the resource instance
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Human-friendly description of the resource instance
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// A specific version of the resource
	Version []ExampleScenarioInstanceVersion `json:"version,omitempty" fhir:"cardinality=0..*"`
	// Resources contained in the instance
	ContainedInstance []ExampleScenarioInstanceContainedInstance `json:"containedInstance,omitempty" fhir:"cardinality=0..*"`
}

// ExampleScenarioProcessStepProcess represents a FHIR BackboneElement for ExampleScenario.process.step.process.
type ExampleScenarioProcessStepProcess struct {
}

// ExampleScenarioProcessStepOperationRequest represents a FHIR BackboneElement for ExampleScenario.process.step.operation.request.
type ExampleScenarioProcessStepOperationRequest struct {
}

// ExampleScenarioProcessStepOperationResponse represents a FHIR BackboneElement for ExampleScenario.process.step.operation.response.
type ExampleScenarioProcessStepOperationResponse struct {
}

// ExampleScenarioProcessStepOperation represents a FHIR BackboneElement for ExampleScenario.process.step.operation.
type ExampleScenarioProcessStepOperation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The sequential number of the interaction
	Number string `json:"number" fhir:"cardinality=1..1,required"`
	// Extension for Number
	NumberExt *primitives.PrimitiveExtension `json:"_number,omitempty" fhir:"cardinality=0..1"`
	// The type of operation - CRUD
	Type *string `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// The human-friendly name of the interaction
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Who starts the transaction
	Initiator *string `json:"initiator,omitempty" fhir:"cardinality=0..1"`
	// Extension for Initiator
	InitiatorExt *primitives.PrimitiveExtension `json:"_initiator,omitempty" fhir:"cardinality=0..1"`
	// Who receives the transaction
	Receiver *string `json:"receiver,omitempty" fhir:"cardinality=0..1"`
	// Extension for Receiver
	ReceiverExt *primitives.PrimitiveExtension `json:"_receiver,omitempty" fhir:"cardinality=0..1"`
	// A comment to be inserted in the diagram
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Whether the initiator is deactivated right after the transaction
	InitiatorActive *bool `json:"initiatorActive,omitempty" fhir:"cardinality=0..1"`
	// Extension for InitiatorActive
	InitiatorActiveExt *primitives.PrimitiveExtension `json:"_initiatorActive,omitempty" fhir:"cardinality=0..1"`
	// Whether the receiver is deactivated right after the transaction
	ReceiverActive *bool `json:"receiverActive,omitempty" fhir:"cardinality=0..1"`
	// Extension for ReceiverActive
	ReceiverActiveExt *primitives.PrimitiveExtension `json:"_receiverActive,omitempty" fhir:"cardinality=0..1"`
	// Each resource instance used by the initiator
	Request *ExampleScenarioProcessStepOperationRequest `json:"request,omitempty" fhir:"cardinality=0..1"`
	// Each resource instance used by the responder
	Response *ExampleScenarioProcessStepOperationResponse `json:"response,omitempty" fhir:"cardinality=0..1"`
}

// ExampleScenarioProcessStepAlternativeStep represents a FHIR BackboneElement for ExampleScenario.process.step.alternative.step.
type ExampleScenarioProcessStepAlternativeStep struct {
}

// ExampleScenarioProcessStepAlternative represents a FHIR BackboneElement for ExampleScenario.process.step.alternative.
type ExampleScenarioProcessStepAlternative struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Label for alternative
	Title string `json:"title" fhir:"cardinality=1..1,required"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// A human-readable description of each option
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// What happens in each alternative option
	Step []ExampleScenarioProcessStepAlternativeStep `json:"step,omitempty" fhir:"cardinality=0..*"`
}

// ExampleScenarioProcessStep represents a FHIR BackboneElement for ExampleScenario.process.step.
type ExampleScenarioProcessStep struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Nested process
	Process []ExampleScenarioProcessStepProcess `json:"process,omitempty" fhir:"cardinality=0..*"`
	// If there is a pause in the flow
	Pause *bool `json:"pause,omitempty" fhir:"cardinality=0..1"`
	// Extension for Pause
	PauseExt *primitives.PrimitiveExtension `json:"_pause,omitempty" fhir:"cardinality=0..1"`
	// Each interaction or action
	Operation *ExampleScenarioProcessStepOperation `json:"operation,omitempty" fhir:"cardinality=0..1"`
	// Alternate non-typical step action
	Alternative []ExampleScenarioProcessStepAlternative `json:"alternative,omitempty" fhir:"cardinality=0..*"`
}

// ExampleScenarioProcess represents a FHIR BackboneElement for ExampleScenario.process.
type ExampleScenarioProcess struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The diagram title of the group of operations
	Title string `json:"title" fhir:"cardinality=1..1,required,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// A longer description of the group of operations
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Description of initial status before the process starts
	PreConditions *string `json:"preConditions,omitempty" fhir:"cardinality=0..1"`
	// Extension for PreConditions
	PreConditionsExt *primitives.PrimitiveExtension `json:"_preConditions,omitempty" fhir:"cardinality=0..1"`
	// Description of final status after the process ends
	PostConditions *string `json:"postConditions,omitempty" fhir:"cardinality=0..1"`
	// Extension for PostConditions
	PostConditionsExt *primitives.PrimitiveExtension `json:"_postConditions,omitempty" fhir:"cardinality=0..1"`
	// Each step of the process
	Step []ExampleScenarioProcessStep `json:"step,omitempty" fhir:"cardinality=0..*"`
}

// ExampleScenario represents a FHIR ExampleScenario.
type ExampleScenario struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this example scenario, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the example scenario
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the example scenario
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Name for this example scenario (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for example scenario (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// The purpose of the example, e.g. to illustrate a scenario
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Actor participating in the resource
	Actor []ExampleScenarioActor `json:"actor,omitempty" fhir:"cardinality=0..*"`
	// Each resource and each version that is present in the workflow
	Instance []ExampleScenarioInstance `json:"instance,omitempty" fhir:"cardinality=0..*"`
	// Each major process - a group of operations
	Process []ExampleScenarioProcess `json:"process,omitempty" fhir:"cardinality=0..*"`
	// Another nested workflow
	Workflow []string `json:"workflow,omitempty" fhir:"cardinality=0..*"`
	// Extension for Workflow
	WorkflowExt *primitives.PrimitiveExtension `json:"_workflow,omitempty" fhir:"cardinality=0..1"`
}
