// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeHealthcareService is the FHIR resource type name for HealthcareService.
const ResourceTypeHealthcareService = "HealthcareService"

// HealthcareServiceEligibility represents a FHIR BackboneElement for HealthcareService.eligibility.
type HealthcareServiceEligibility struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Coded value for the eligibility
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Describes the eligibility conditions for the service
	Comment *string `json:"comment,omitempty" fhir:"cardinality=0..1"`
	// Extension for Comment
	CommentExt *primitives.PrimitiveExtension `json:"_comment,omitempty" fhir:"cardinality=0..1"`
}

// HealthcareServiceAvailableTime represents a FHIR BackboneElement for HealthcareService.availableTime.
type HealthcareServiceAvailableTime struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// mon | tue | wed | thu | fri | sat | sun
	DaysOfWeek []string `json:"daysOfWeek,omitempty" fhir:"cardinality=0..*"`
	// Extension for DaysOfWeek
	DaysOfWeekExt *primitives.PrimitiveExtension `json:"_daysOfWeek,omitempty" fhir:"cardinality=0..1"`
	// Always available? e.g. 24 hour service
	AllDay *bool `json:"allDay,omitempty" fhir:"cardinality=0..1"`
	// Extension for AllDay
	AllDayExt *primitives.PrimitiveExtension `json:"_allDay,omitempty" fhir:"cardinality=0..1"`
	// Opening time of day (ignored if allDay = true)
	AvailableStartTime *primitives.Time `json:"availableStartTime,omitempty" fhir:"cardinality=0..1"`
	// Extension for AvailableStartTime
	AvailableStartTimeExt *primitives.PrimitiveExtension `json:"_availableStartTime,omitempty" fhir:"cardinality=0..1"`
	// Closing time of day (ignored if allDay = true)
	AvailableEndTime *primitives.Time `json:"availableEndTime,omitempty" fhir:"cardinality=0..1"`
	// Extension for AvailableEndTime
	AvailableEndTimeExt *primitives.PrimitiveExtension `json:"_availableEndTime,omitempty" fhir:"cardinality=0..1"`
}

// HealthcareServiceNotAvailable represents a FHIR BackboneElement for HealthcareService.notAvailable.
type HealthcareServiceNotAvailable struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Reason presented to the user explaining why time not available
	Description string `json:"description" fhir:"cardinality=1..1,required"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Service not available from this date
	During *Period `json:"during,omitempty" fhir:"cardinality=0..1"`
}

// HealthcareService represents a FHIR HealthcareService.
type HealthcareService struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External identifiers for this item
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether this HealthcareService record is in active use
	Active *bool `json:"active,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Active
	ActiveExt *primitives.PrimitiveExtension `json:"_active,omitempty" fhir:"cardinality=0..1"`
	// Organization that provides this service
	ProvidedBy *Reference `json:"providedBy,omitempty" fhir:"cardinality=0..1,summary"`
	// Broad category of service being performed or delivered
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of service that may be delivered or performed
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*,summary"`
	// Specialties handled by the HealthcareService
	Specialty []CodeableConcept `json:"specialty,omitempty" fhir:"cardinality=0..*,summary"`
	// Location(s) where service may be provided
	Location []Reference `json:"location,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of service as presented to a consumer while searching
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Additional description and/or any specific issues not covered elsewhere
	Comment *string `json:"comment,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Comment
	CommentExt *primitives.PrimitiveExtension `json:"_comment,omitempty" fhir:"cardinality=0..1"`
	// Extra details about the service that can't be placed in the other fields
	ExtraDetails *string `json:"extraDetails,omitempty" fhir:"cardinality=0..1"`
	// Extension for ExtraDetails
	ExtraDetailsExt *primitives.PrimitiveExtension `json:"_extraDetails,omitempty" fhir:"cardinality=0..1"`
	// Facilitates quick identification of the service
	Photo *Attachment `json:"photo,omitempty" fhir:"cardinality=0..1,summary"`
	// Contacts related to the healthcare service
	Telecom []ContactPoint `json:"telecom,omitempty" fhir:"cardinality=0..*"`
	// Location(s) service is intended for/available to
	CoverageArea []Reference `json:"coverageArea,omitempty" fhir:"cardinality=0..*"`
	// Conditions under which service is available/offered
	ServiceProvisionCode []CodeableConcept `json:"serviceProvisionCode,omitempty" fhir:"cardinality=0..*"`
	// Specific eligibility requirements required to use the service
	Eligibility []HealthcareServiceEligibility `json:"eligibility,omitempty" fhir:"cardinality=0..*"`
	// Programs that this service is applicable to
	Program []CodeableConcept `json:"program,omitempty" fhir:"cardinality=0..*"`
	// Collection of characteristics (attributes)
	Characteristic []CodeableConcept `json:"characteristic,omitempty" fhir:"cardinality=0..*"`
	// The language that this service is offered in
	Communication []CodeableConcept `json:"communication,omitempty" fhir:"cardinality=0..*"`
	// Ways that the service accepts referrals
	ReferralMethod []CodeableConcept `json:"referralMethod,omitempty" fhir:"cardinality=0..*"`
	// If an appointment is required for access to this service
	AppointmentRequired *bool `json:"appointmentRequired,omitempty" fhir:"cardinality=0..1"`
	// Extension for AppointmentRequired
	AppointmentRequiredExt *primitives.PrimitiveExtension `json:"_appointmentRequired,omitempty" fhir:"cardinality=0..1"`
	// Times the Service Site is available
	AvailableTime []HealthcareServiceAvailableTime `json:"availableTime,omitempty" fhir:"cardinality=0..*"`
	// Not available during this time due to provided reason
	NotAvailable []HealthcareServiceNotAvailable `json:"notAvailable,omitempty" fhir:"cardinality=0..*"`
	// Description of availability exceptions
	AvailabilityExceptions *string `json:"availabilityExceptions,omitempty" fhir:"cardinality=0..1"`
	// Extension for AvailabilityExceptions
	AvailabilityExceptionsExt *primitives.PrimitiveExtension `json:"_availabilityExceptions,omitempty" fhir:"cardinality=0..1"`
	// Technical endpoints providing access to electronic services operated for the healthcare service
	Endpoint []Reference `json:"endpoint,omitempty" fhir:"cardinality=0..*"`
}
