// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeImmunizationEvaluation is the FHIR resource type name for ImmunizationEvaluation.
const ResourceTypeImmunizationEvaluation = "ImmunizationEvaluation"

// ImmunizationEvaluation represents a FHIR ImmunizationEvaluation.
type ImmunizationEvaluation struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// completed | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Who this evaluation is for
	Patient Reference `json:"patient" fhir:"cardinality=1..1,required,summary"`
	// Date evaluation was performed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Who is responsible for publishing the recommendations
	Authority *Reference `json:"authority,omitempty" fhir:"cardinality=0..1"`
	// Evaluation target disease
	TargetDisease CodeableConcept `json:"targetDisease" fhir:"cardinality=1..1,required,summary"`
	// Immunization being evaluated
	ImmunizationEvent Reference `json:"immunizationEvent" fhir:"cardinality=1..1,required,summary"`
	// Status of the dose relative to published recommendations
	DoseStatus CodeableConcept `json:"doseStatus" fhir:"cardinality=1..1,required,summary"`
	// Reason for the dose status
	DoseStatusReason []CodeableConcept `json:"doseStatusReason,omitempty" fhir:"cardinality=0..*"`
	// Evaluation notes
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Name of vaccine series
	Series *string `json:"series,omitempty" fhir:"cardinality=0..1"`
	// Extension for Series
	SeriesExt *primitives.PrimitiveExtension `json:"_series,omitempty" fhir:"cardinality=0..1"`
	// Dose number within series - positiveInt option
	DoseNumberPositiveInt *int `json:"doseNumberPositiveInt,omitempty" fhir:"cardinality=0..1,choice=doseNumber"`
	// Extension for DoseNumberPositiveInt
	DoseNumberPositiveIntExt *primitives.PrimitiveExtension `json:"_doseNumberPositiveInt,omitempty" fhir:"cardinality=0..1"`
	// Dose number within series - string option
	DoseNumberString *string `json:"doseNumberString,omitempty" fhir:"cardinality=0..1,choice=doseNumber"`
	// Extension for DoseNumberString
	DoseNumberStringExt *primitives.PrimitiveExtension `json:"_doseNumberString,omitempty" fhir:"cardinality=0..1"`
	// Recommended number of doses for immunity - positiveInt option
	SeriesDosesPositiveInt *int `json:"seriesDosesPositiveInt,omitempty" fhir:"cardinality=0..1,choice=seriesDoses"`
	// Extension for SeriesDosesPositiveInt
	SeriesDosesPositiveIntExt *primitives.PrimitiveExtension `json:"_seriesDosesPositiveInt,omitempty" fhir:"cardinality=0..1"`
	// Recommended number of doses for immunity - string option
	SeriesDosesString *string `json:"seriesDosesString,omitempty" fhir:"cardinality=0..1,choice=seriesDoses"`
	// Extension for SeriesDosesString
	SeriesDosesStringExt *primitives.PrimitiveExtension `json:"_seriesDosesString,omitempty" fhir:"cardinality=0..1"`
}
