// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeImplementationGuide is the FHIR resource type name for ImplementationGuide.
const ResourceTypeImplementationGuide = "ImplementationGuide"

// ImplementationGuideDependsOn represents a FHIR BackboneElement for ImplementationGuide.dependsOn.
type ImplementationGuideDependsOn struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Identity of the IG that this depends on
	URI string `json:"uri" fhir:"cardinality=1..1,required,summary"`
	// Extension for URI
	URIExt *primitives.PrimitiveExtension `json:"_uri,omitempty" fhir:"cardinality=0..1"`
	// NPM Package name for IG this depends on
	PackageId *string `json:"packageId,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for PackageId
	PackageIdExt *primitives.PrimitiveExtension `json:"_packageId,omitempty" fhir:"cardinality=0..1"`
	// Version of the IG
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
}

// ImplementationGuideGlobal represents a FHIR BackboneElement for ImplementationGuide.global.
type ImplementationGuideGlobal struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Type this profile applies to
	Type string `json:"type" fhir:"cardinality=1..1,required,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// Profile that all resources must conform to
	Profile string `json:"profile" fhir:"cardinality=1..1,required,summary"`
	// Extension for Profile
	ProfileExt *primitives.PrimitiveExtension `json:"_profile,omitempty" fhir:"cardinality=0..1"`
}

// ImplementationGuideDefinitionGrouping represents a FHIR BackboneElement for ImplementationGuide.definition.grouping.
type ImplementationGuideDefinitionGrouping struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Descriptive name for the package
	Name string `json:"name" fhir:"cardinality=1..1,required"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Human readable text describing the package
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
}

// ImplementationGuideDefinitionResource represents a FHIR BackboneElement for ImplementationGuide.definition.resource.
type ImplementationGuideDefinitionResource struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Location of the resource
	Reference Reference `json:"reference" fhir:"cardinality=1..1,required"`
	// Versions this applies to (if different to IG)
	FhirVersion []string `json:"fhirVersion,omitempty" fhir:"cardinality=0..*"`
	// Extension for FhirVersion
	FhirVersionExt *primitives.PrimitiveExtension `json:"_fhirVersion,omitempty" fhir:"cardinality=0..1"`
	// Human Name for the resource
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Reason why included in guide
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Is an example/What is this an example of? - boolean option
	ExampleBoolean *bool `json:"exampleBoolean,omitempty" fhir:"cardinality=0..1,choice=example"`
	// Extension for ExampleBoolean
	ExampleBooleanExt *primitives.PrimitiveExtension `json:"_exampleBoolean,omitempty" fhir:"cardinality=0..1"`
	// Is an example/What is this an example of? - canonical option
	ExampleCanonical *string `json:"exampleCanonical,omitempty" fhir:"cardinality=0..1,choice=example"`
	// Extension for ExampleCanonical
	ExampleCanonicalExt *primitives.PrimitiveExtension `json:"_exampleCanonical,omitempty" fhir:"cardinality=0..1"`
	// Grouping this is part of
	GroupingId *string `json:"groupingId,omitempty" fhir:"cardinality=0..1"`
	// Extension for GroupingId
	GroupingIdExt *primitives.PrimitiveExtension `json:"_groupingId,omitempty" fhir:"cardinality=0..1"`
}

// ImplementationGuideDefinitionPagePage represents a FHIR BackboneElement for ImplementationGuide.definition.page.page.
type ImplementationGuideDefinitionPagePage struct {
}

// ImplementationGuideDefinitionPage represents a FHIR BackboneElement for ImplementationGuide.definition.page.
type ImplementationGuideDefinitionPage struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Where to find that page - url option
	NameURL string `json:"nameURL" fhir:"cardinality=1..1,required,choice=name"`
	// Extension for NameURL
	NameURLExt *primitives.PrimitiveExtension `json:"_nameURL,omitempty" fhir:"cardinality=0..1"`
	// Where to find that page - Reference option
	NameReference Reference `json:"nameReference" fhir:"cardinality=1..1,required,choice=name"`
	// Short title shown for navigational assistance
	Title string `json:"title" fhir:"cardinality=1..1,required"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// html | markdown | xml | generated
	Generation string `json:"generation" fhir:"cardinality=1..1,required"`
	// Extension for Generation
	GenerationExt *primitives.PrimitiveExtension `json:"_generation,omitempty" fhir:"cardinality=0..1"`
	// Nested Pages / Sections
	Page []ImplementationGuideDefinitionPagePage `json:"page,omitempty" fhir:"cardinality=0..*"`
}

// ImplementationGuideDefinitionParameter represents a FHIR BackboneElement for ImplementationGuide.definition.parameter.
type ImplementationGuideDefinitionParameter struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// apply | path-resource | path-pages | path-tx-cache | expansion-parameter | rule-broken-links | generate-xml | generate-json | generate-turtle | html-template
	Code string `json:"code" fhir:"cardinality=1..1,required"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// Value for named type
	Value string `json:"value" fhir:"cardinality=1..1,required"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
}

// ImplementationGuideDefinitionTemplate represents a FHIR BackboneElement for ImplementationGuide.definition.template.
type ImplementationGuideDefinitionTemplate struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of template specified
	Code string `json:"code" fhir:"cardinality=1..1,required"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// The source location for the template
	Source string `json:"source" fhir:"cardinality=1..1,required"`
	// Extension for Source
	SourceExt *primitives.PrimitiveExtension `json:"_source,omitempty" fhir:"cardinality=0..1"`
	// The scope in which the template applies
	Scope *string `json:"scope,omitempty" fhir:"cardinality=0..1"`
	// Extension for Scope
	ScopeExt *primitives.PrimitiveExtension `json:"_scope,omitempty" fhir:"cardinality=0..1"`
}

// ImplementationGuideDefinition represents a FHIR BackboneElement for ImplementationGuide.definition.
type ImplementationGuideDefinition struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Grouping used to present related resources in the IG
	Grouping []ImplementationGuideDefinitionGrouping `json:"grouping,omitempty" fhir:"cardinality=0..*"`
	// Resource in the implementation guide
	Resource []ImplementationGuideDefinitionResource `json:"resource,omitempty" fhir:"cardinality=1..*,required"`
	// Page/Section in the Guide
	Page *ImplementationGuideDefinitionPage `json:"page,omitempty" fhir:"cardinality=0..1"`
	// Defines how IG is built by tools
	Parameter []ImplementationGuideDefinitionParameter `json:"parameter,omitempty" fhir:"cardinality=0..*"`
	// A template for building resources
	Template []ImplementationGuideDefinitionTemplate `json:"template,omitempty" fhir:"cardinality=0..*"`
}

// ImplementationGuideManifestResource represents a FHIR BackboneElement for ImplementationGuide.manifest.resource.
type ImplementationGuideManifestResource struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Location of the resource
	Reference Reference `json:"reference" fhir:"cardinality=1..1,required,summary"`
	// Is an example/What is this an example of? - boolean option
	ExampleBoolean *bool `json:"exampleBoolean,omitempty" fhir:"cardinality=0..1,choice=example"`
	// Extension for ExampleBoolean
	ExampleBooleanExt *primitives.PrimitiveExtension `json:"_exampleBoolean,omitempty" fhir:"cardinality=0..1"`
	// Is an example/What is this an example of? - canonical option
	ExampleCanonical *string `json:"exampleCanonical,omitempty" fhir:"cardinality=0..1,choice=example"`
	// Extension for ExampleCanonical
	ExampleCanonicalExt *primitives.PrimitiveExtension `json:"_exampleCanonical,omitempty" fhir:"cardinality=0..1"`
	// Relative path for page in IG
	RelativePath *string `json:"relativePath,omitempty" fhir:"cardinality=0..1"`
	// Extension for RelativePath
	RelativePathExt *primitives.PrimitiveExtension `json:"_relativePath,omitempty" fhir:"cardinality=0..1"`
}

// ImplementationGuideManifestPage represents a FHIR BackboneElement for ImplementationGuide.manifest.page.
type ImplementationGuideManifestPage struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// HTML page name
	Name string `json:"name" fhir:"cardinality=1..1,required"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Title of the page, for references
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Anchor available on the page
	Anchor []string `json:"anchor,omitempty" fhir:"cardinality=0..*"`
	// Extension for Anchor
	AnchorExt *primitives.PrimitiveExtension `json:"_anchor,omitempty" fhir:"cardinality=0..1"`
}

// ImplementationGuideManifest represents a FHIR BackboneElement for ImplementationGuide.manifest.
type ImplementationGuideManifest struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Location of rendered implementation guide
	Rendering *string `json:"rendering,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Rendering
	RenderingExt *primitives.PrimitiveExtension `json:"_rendering,omitempty" fhir:"cardinality=0..1"`
	// Resource in the implementation guide
	Resource []ImplementationGuideManifestResource `json:"resource,omitempty" fhir:"cardinality=1..*,required,summary"`
	// HTML page within the parent IG
	Page []ImplementationGuideManifestPage `json:"page,omitempty" fhir:"cardinality=0..*"`
	// Image within the IG
	Image []string `json:"image,omitempty" fhir:"cardinality=0..*"`
	// Extension for Image
	ImageExt *primitives.PrimitiveExtension `json:"_image,omitempty" fhir:"cardinality=0..1"`
	// Additional linkable file in IG
	Other []string `json:"other,omitempty" fhir:"cardinality=0..*"`
	// Extension for Other
	OtherExt *primitives.PrimitiveExtension `json:"_other,omitempty" fhir:"cardinality=0..1"`
}

// ImplementationGuide represents a FHIR ImplementationGuide.
type ImplementationGuide struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this implementation guide, represented as a URI (globally unique)
	URL string `json:"url" fhir:"cardinality=1..1,required,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Business version of the implementation guide
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Name for this implementation guide (computer friendly)
	Name string `json:"name" fhir:"cardinality=1..1,required,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this implementation guide (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the implementation guide
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for implementation guide (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// NPM Package name for IG
	PackageId string `json:"packageId" fhir:"cardinality=1..1,required,summary"`
	// Extension for PackageId
	PackageIdExt *primitives.PrimitiveExtension `json:"_packageId,omitempty" fhir:"cardinality=0..1"`
	// SPDX license code for this IG (or not-open-source)
	License *string `json:"license,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for License
	LicenseExt *primitives.PrimitiveExtension `json:"_license,omitempty" fhir:"cardinality=0..1"`
	// FHIR Version(s) this Implementation Guide targets
	FhirVersion []string `json:"fhirVersion,omitempty" fhir:"cardinality=1..*,required,summary"`
	// Extension for FhirVersion
	FhirVersionExt *primitives.PrimitiveExtension `json:"_fhirVersion,omitempty" fhir:"cardinality=0..1"`
	// Another Implementation guide this depends on
	DependsOn []ImplementationGuideDependsOn `json:"dependsOn,omitempty" fhir:"cardinality=0..*,summary"`
	// Profiles that apply globally
	Global []ImplementationGuideGlobal `json:"global,omitempty" fhir:"cardinality=0..*,summary"`
	// Information needed to build the IG
	Definition *ImplementationGuideDefinition `json:"definition,omitempty" fhir:"cardinality=0..1"`
	// Information about an assembled IG
	Manifest *ImplementationGuideManifest `json:"manifest,omitempty" fhir:"cardinality=0..1"`
}
