// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeMeasureReport is the FHIR resource type name for MeasureReport.
const ResourceTypeMeasureReport = "MeasureReport"

// MeasureReportGroupPopulation represents a FHIR BackboneElement for MeasureReport.group.population.
type MeasureReportGroupPopulation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// initial-population | numerator | numerator-exclusion | denominator | denominator-exclusion | denominator-exception | measure-population | measure-population-exclusion | measure-observation
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// Size of the population
	Count *int `json:"count,omitempty" fhir:"cardinality=0..1"`
	// Extension for Count
	CountExt *primitives.PrimitiveExtension `json:"_count,omitempty" fhir:"cardinality=0..1"`
	// For subject-list reports, the subject results in this population
	SubjectResults *Reference `json:"subjectResults,omitempty" fhir:"cardinality=0..1"`
}

// MeasureReportGroupStratifierStratumComponent represents a FHIR BackboneElement for MeasureReport.group.stratifier.stratum.component.
type MeasureReportGroupStratifierStratumComponent struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// What stratifier component of the group
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required"`
	// The stratum component value, e.g. male
	Value CodeableConcept `json:"value" fhir:"cardinality=1..1,required"`
}

// MeasureReportGroupStratifierStratumPopulation represents a FHIR BackboneElement for MeasureReport.group.stratifier.stratum.population.
type MeasureReportGroupStratifierStratumPopulation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// initial-population | numerator | numerator-exclusion | denominator | denominator-exclusion | denominator-exception | measure-population | measure-population-exclusion | measure-observation
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Size of the population
	Count *int `json:"count,omitempty" fhir:"cardinality=0..1"`
	// Extension for Count
	CountExt *primitives.PrimitiveExtension `json:"_count,omitempty" fhir:"cardinality=0..1"`
	// For subject-list reports, the subject results in this population
	SubjectResults *Reference `json:"subjectResults,omitempty" fhir:"cardinality=0..1"`
}

// MeasureReportGroupStratifierStratum represents a FHIR BackboneElement for MeasureReport.group.stratifier.stratum.
type MeasureReportGroupStratifierStratum struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The stratum value, e.g. male
	Value *CodeableConcept `json:"value,omitempty" fhir:"cardinality=0..1"`
	// Stratifier component values
	Component []MeasureReportGroupStratifierStratumComponent `json:"component,omitempty" fhir:"cardinality=0..*"`
	// Population results in this stratum
	Population []MeasureReportGroupStratifierStratumPopulation `json:"population,omitempty" fhir:"cardinality=0..*"`
	// What score this stratum achieved
	MeasureScore *Quantity `json:"measureScore,omitempty" fhir:"cardinality=0..1"`
}

// MeasureReportGroupStratifier represents a FHIR BackboneElement for MeasureReport.group.stratifier.
type MeasureReportGroupStratifier struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// What stratifier of the group
	Code []CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..*"`
	// Stratum results, one for each unique value, or set of values, in the stratifier, or stratifier components
	Stratum []MeasureReportGroupStratifierStratum `json:"stratum,omitempty" fhir:"cardinality=0..*"`
}

// MeasureReportGroup represents a FHIR BackboneElement for MeasureReport.group.
type MeasureReportGroup struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Meaning of the group
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// The populations in the group
	Population []MeasureReportGroupPopulation `json:"population,omitempty" fhir:"cardinality=0..*"`
	// What score this group achieved
	MeasureScore *Quantity `json:"measureScore,omitempty" fhir:"cardinality=0..1,summary"`
	// Stratification results
	Stratifier []MeasureReportGroupStratifier `json:"stratifier,omitempty" fhir:"cardinality=0..*"`
}

// MeasureReport represents a FHIR MeasureReport.
type MeasureReport struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the MeasureReport
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// complete | pending | error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// individual | subject-list | summary | data-collection
	Type string `json:"type" fhir:"cardinality=1..1,required,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// What measure was calculated
	Measure string `json:"measure" fhir:"cardinality=1..1,required,summary"`
	// Extension for Measure
	MeasureExt *primitives.PrimitiveExtension `json:"_measure,omitempty" fhir:"cardinality=0..1"`
	// What individual(s) the report is for
	Subject *Reference `json:"subject,omitempty" fhir:"cardinality=0..1,summary"`
	// When the report was generated
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Who is reporting the data
	Reporter *Reference `json:"reporter,omitempty" fhir:"cardinality=0..1,summary"`
	// What period the report covers
	Period Period `json:"period" fhir:"cardinality=1..1,required,summary"`
	// increase | decrease
	ImprovementNotation *CodeableConcept `json:"improvementNotation,omitempty" fhir:"cardinality=0..1,summary"`
	// Measure results for each group
	Group []MeasureReportGroup `json:"group,omitempty" fhir:"cardinality=0..*"`
	// What data was used to calculate the measure score
	EvaluatedResource []Reference `json:"evaluatedResource,omitempty" fhir:"cardinality=0..*"`
}
