// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeMedicinalProductContraindication is the FHIR resource type name for MedicinalProductContraindication.
const ResourceTypeMedicinalProductContraindication = "MedicinalProductContraindication"

// MedicinalProductContraindicationOtherTherapy represents a FHIR BackboneElement for MedicinalProductContraindication.otherTherapy.
type MedicinalProductContraindicationOtherTherapy struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The type of relationship between the medicinal product indication or contraindication and another therapy
	TherapyRelationshipType CodeableConcept `json:"therapyRelationshipType" fhir:"cardinality=1..1,required,summary"`
	// Reference to a specific medication (active substance, medicinal product or class of products) as part of an indication or contraindication - CodeableConcept option
	MedicationCodeableConcept CodeableConcept `json:"medicationCodeableConcept" fhir:"cardinality=1..1,required,summary,choice=medication"`
	// Reference to a specific medication (active substance, medicinal product or class of products) as part of an indication or contraindication - Reference option
	MedicationReference Reference `json:"medicationReference" fhir:"cardinality=1..1,required,summary,choice=medication"`
}

// MedicinalProductContraindication represents a FHIR MedicinalProductContraindication.
type MedicinalProductContraindication struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// The medication for which this is an indication
	Subject []Reference `json:"subject,omitempty" fhir:"cardinality=0..*,summary"`
	// The disease, symptom or procedure for the contraindication
	Disease *CodeableConcept `json:"disease,omitempty" fhir:"cardinality=0..1,summary"`
	// The status of the disease or symptom for the contraindication
	DiseaseStatus *CodeableConcept `json:"diseaseStatus,omitempty" fhir:"cardinality=0..1,summary"`
	// A comorbidity (concurrent condition) or coinfection
	Comorbidity []CodeableConcept `json:"comorbidity,omitempty" fhir:"cardinality=0..*,summary"`
	// Information about the use of the medicinal product in relation to other therapies as part of the indication
	TherapeuticIndication []Reference `json:"therapeuticIndication,omitempty" fhir:"cardinality=0..*,summary"`
	// Information about the use of the medicinal product in relation to other therapies described as part of the indication
	OtherTherapy []MedicinalProductContraindicationOtherTherapy `json:"otherTherapy,omitempty" fhir:"cardinality=0..*,summary"`
	// The population group to which this applies
	Population []Population `json:"population,omitempty" fhir:"cardinality=0..*,summary"`
}
