// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeMedicinalProductUndesirableEffect is the FHIR resource type name for MedicinalProductUndesirableEffect.
const ResourceTypeMedicinalProductUndesirableEffect = "MedicinalProductUndesirableEffect"

// MedicinalProductUndesirableEffect represents a FHIR MedicinalProductUndesirableEffect.
type MedicinalProductUndesirableEffect struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// The medication for which this is an indication
	Subject []Reference `json:"subject,omitempty" fhir:"cardinality=0..*,summary"`
	// The symptom, condition or undesirable effect
	SymptomConditionEffect *CodeableConcept `json:"symptomConditionEffect,omitempty" fhir:"cardinality=0..1,summary"`
	// Classification of the effect
	Classification *CodeableConcept `json:"classification,omitempty" fhir:"cardinality=0..1,summary"`
	// The frequency of occurrence of the effect
	FrequencyOfOccurrence *CodeableConcept `json:"frequencyOfOccurrence,omitempty" fhir:"cardinality=0..1,summary"`
	// The population group to which this applies
	Population []Population `json:"population,omitempty" fhir:"cardinality=0..*,summary"`
}
