// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeMedicinalProductManufactured is the FHIR resource type name for MedicinalProductManufactured.
const ResourceTypeMedicinalProductManufactured = "MedicinalProductManufactured"

// MedicinalProductManufactured represents a FHIR MedicinalProductManufactured.
type MedicinalProductManufactured struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Dose form as manufactured and before any transformation into the pharmaceutical product
	ManufacturedDoseForm CodeableConcept `json:"manufacturedDoseForm" fhir:"cardinality=1..1,required,summary"`
	// The “real world” units in which the quantity of the manufactured item is described
	UnitOfPresentation *CodeableConcept `json:"unitOfPresentation,omitempty" fhir:"cardinality=0..1,summary"`
	// The quantity or "count number" of the manufactured item
	Quantity Quantity `json:"quantity" fhir:"cardinality=1..1,required,summary"`
	// Manufacturer of the item (Note that this should be named "manufacturer" but it currently causes technical issues)
	Manufacturer []Reference `json:"manufacturer,omitempty" fhir:"cardinality=0..*,summary"`
	// Ingredient
	Ingredient []Reference `json:"ingredient,omitempty" fhir:"cardinality=0..*,summary"`
	// Dimensions, color etc.
	PhysicalCharacteristics *ProdCharacteristic `json:"physicalCharacteristics,omitempty" fhir:"cardinality=0..1,summary"`
	// Other codeable characteristics
	OtherCharacteristics []CodeableConcept `json:"otherCharacteristics,omitempty" fhir:"cardinality=0..*,summary"`
}
