// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeMedicationStatement is the FHIR resource type name for MedicationStatement.
const ResourceTypeMedicationStatement = "MedicationStatement"

// MedicationStatement represents a FHIR MedicationStatement.
type MedicationStatement struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Fulfils plan, proposal or order
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// Part of referenced event
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*,summary"`
	// active | completed | entered-in-error | intended | stopped | on-hold | unknown | not-taken
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Reason for current status
	StatusReason []CodeableConcept `json:"statusReason,omitempty" fhir:"cardinality=0..*"`
	// Type of medication usage
	Category *CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..1,summary"`
	// What medication was taken - CodeableConcept option
	MedicationCodeableConcept CodeableConcept `json:"medicationCodeableConcept" fhir:"cardinality=1..1,required,summary,choice=medication"`
	// What medication was taken - Reference option
	MedicationReference Reference `json:"medicationReference" fhir:"cardinality=1..1,required,summary,choice=medication"`
	// Who is/was taking  the medication
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// Encounter / Episode associated with MedicationStatement
	Context *Reference `json:"context,omitempty" fhir:"cardinality=0..1,summary"`
	// The date/time or interval when the medication is/was/will be taken - dateTime option
	EffectiveDateTime *primitives.DateTime `json:"effectiveDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=effective"`
	// Extension for EffectiveDateTime
	EffectiveDateTimeExt *primitives.PrimitiveExtension `json:"_effectiveDateTime,omitempty" fhir:"cardinality=0..1"`
	// The date/time or interval when the medication is/was/will be taken - Period option
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary,choice=effective"`
	// When the statement was asserted?
	DateAsserted *primitives.DateTime `json:"dateAsserted,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DateAsserted
	DateAssertedExt *primitives.PrimitiveExtension `json:"_dateAsserted,omitempty" fhir:"cardinality=0..1"`
	// Person or organization that provided the information about the taking of this medication
	InformationSource *Reference `json:"informationSource,omitempty" fhir:"cardinality=0..1"`
	// Additional supporting information
	DerivedFrom []Reference `json:"derivedFrom,omitempty" fhir:"cardinality=0..*"`
	// Reason for why the medication is being/was taken
	ReasonCode []CodeableConcept `json:"reasonCode,omitempty" fhir:"cardinality=0..*"`
	// Condition or observation that supports why the medication is being/was taken
	ReasonReference []Reference `json:"reasonReference,omitempty" fhir:"cardinality=0..*"`
	// Further information about the statement
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// Details of how medication is/was taken or should be taken
	Dosage []Dosage `json:"dosage,omitempty" fhir:"cardinality=0..*"`
}
