// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeMedicinalProductIngredient is the FHIR resource type name for MedicinalProductIngredient.
const ResourceTypeMedicinalProductIngredient = "MedicinalProductIngredient"

// MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength represents a FHIR BackboneElement for MedicinalProductIngredient.specifiedSubstance.strength.referenceStrength.
type MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Relevant reference substance
	Substance *CodeableConcept `json:"substance,omitempty" fhir:"cardinality=0..1,summary"`
	// Strength expressed in terms of a reference substance
	Strength Ratio `json:"strength" fhir:"cardinality=1..1,required,summary"`
	// Strength expressed in terms of a reference substance
	StrengthLowLimit *Ratio `json:"strengthLowLimit,omitempty" fhir:"cardinality=0..1,summary"`
	// For when strength is measured at a particular point or distance
	MeasurementPoint *string `json:"measurementPoint,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for MeasurementPoint
	MeasurementPointExt *primitives.PrimitiveExtension `json:"_measurementPoint,omitempty" fhir:"cardinality=0..1"`
	// The country or countries for which the strength range applies
	Country []CodeableConcept `json:"country,omitempty" fhir:"cardinality=0..*,summary"`
}

// MedicinalProductIngredientSpecifiedSubstanceStrength represents a FHIR BackboneElement for MedicinalProductIngredient.specifiedSubstance.strength.
type MedicinalProductIngredientSpecifiedSubstanceStrength struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The quantity of substance in the unit of presentation, or in the volume (or mass) of the single pharmaceutical product or manufactured item
	Presentation Ratio `json:"presentation" fhir:"cardinality=1..1,required,summary"`
	// A lower limit for the quantity of substance in the unit of presentation. For use when there is a range of strengths, this is the lower limit, with the presentation attribute becoming the upper limit
	PresentationLowLimit *Ratio `json:"presentationLowLimit,omitempty" fhir:"cardinality=0..1,summary"`
	// The strength per unitary volume (or mass)
	Concentration *Ratio `json:"concentration,omitempty" fhir:"cardinality=0..1,summary"`
	// A lower limit for the strength per unitary volume (or mass), for when there is a range. The concentration attribute then becomes the upper limit
	ConcentrationLowLimit *Ratio `json:"concentrationLowLimit,omitempty" fhir:"cardinality=0..1,summary"`
	// For when strength is measured at a particular point or distance
	MeasurementPoint *string `json:"measurementPoint,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for MeasurementPoint
	MeasurementPointExt *primitives.PrimitiveExtension `json:"_measurementPoint,omitempty" fhir:"cardinality=0..1"`
	// The country or countries for which the strength range applies
	Country []CodeableConcept `json:"country,omitempty" fhir:"cardinality=0..*,summary"`
	// Strength expressed in terms of a reference substance
	ReferenceStrength []MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength `json:"referenceStrength,omitempty" fhir:"cardinality=0..*,summary"`
}

// MedicinalProductIngredientSpecifiedSubstance represents a FHIR BackboneElement for MedicinalProductIngredient.specifiedSubstance.
type MedicinalProductIngredientSpecifiedSubstance struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The specified substance
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required,summary"`
	// The group of specified substance, e.g. group 1 to 4
	Group CodeableConcept `json:"group" fhir:"cardinality=1..1,required,summary"`
	// Confidentiality level of the specified substance as the ingredient
	Confidentiality *CodeableConcept `json:"confidentiality,omitempty" fhir:"cardinality=0..1,summary"`
	// Quantity of the substance or specified substance present in the manufactured item or pharmaceutical product
	Strength []MedicinalProductIngredientSpecifiedSubstanceStrength `json:"strength,omitempty" fhir:"cardinality=0..*,summary"`
}

// MedicinalProductIngredientSubstanceStrength represents a FHIR BackboneElement for MedicinalProductIngredient.substance.strength.
type MedicinalProductIngredientSubstanceStrength struct {
}

// MedicinalProductIngredientSubstance represents a FHIR BackboneElement for MedicinalProductIngredient.substance.
type MedicinalProductIngredientSubstance struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The ingredient substance
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Quantity of the substance or specified substance present in the manufactured item or pharmaceutical product
	Strength []MedicinalProductIngredientSubstanceStrength `json:"strength,omitempty" fhir:"cardinality=0..*,summary"`
}

// MedicinalProductIngredient represents a FHIR MedicinalProductIngredient.
type MedicinalProductIngredient struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Identifier for the ingredient
	Identifier *Identifier `json:"identifier,omitempty" fhir:"cardinality=0..1,summary"`
	// Ingredient role e.g. Active ingredient, excipient
	Role CodeableConcept `json:"role" fhir:"cardinality=1..1,required,summary"`
	// If the ingredient is a known or suspected allergen
	AllergenicIndicator *bool `json:"allergenicIndicator,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for AllergenicIndicator
	AllergenicIndicatorExt *primitives.PrimitiveExtension `json:"_allergenicIndicator,omitempty" fhir:"cardinality=0..1"`
	// Manufacturer of this Ingredient
	Manufacturer []Reference `json:"manufacturer,omitempty" fhir:"cardinality=0..*,summary"`
	// A specified substance that comprises this ingredient
	SpecifiedSubstance []MedicinalProductIngredientSpecifiedSubstance `json:"specifiedSubstance,omitempty" fhir:"cardinality=0..*,summary"`
	// The ingredient substance
	Substance *MedicinalProductIngredientSubstance `json:"substance,omitempty" fhir:"cardinality=0..1,summary"`
}
