// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeMedicinalProductInteraction is the FHIR resource type name for MedicinalProductInteraction.
const ResourceTypeMedicinalProductInteraction = "MedicinalProductInteraction"

// MedicinalProductInteractionInteractant represents a FHIR BackboneElement for MedicinalProductInteraction.interactant.
type MedicinalProductInteractionInteractant struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The specific medication, food or laboratory test that interacts - Reference option
	ItemReference Reference `json:"itemReference" fhir:"cardinality=1..1,required,summary,choice=item"`
	// The specific medication, food or laboratory test that interacts - CodeableConcept option
	ItemCodeableConcept CodeableConcept `json:"itemCodeableConcept" fhir:"cardinality=1..1,required,summary,choice=item"`
}

// MedicinalProductInteraction represents a FHIR MedicinalProductInteraction.
type MedicinalProductInteraction struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// The medication for which this is a described interaction
	Subject []Reference `json:"subject,omitempty" fhir:"cardinality=0..*,summary"`
	// The interaction described
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The specific medication, food or laboratory test that interacts
	Interactant []MedicinalProductInteractionInteractant `json:"interactant,omitempty" fhir:"cardinality=0..*,summary"`
	// The type of the interaction e.g. drug-drug interaction, drug-food interaction, drug-lab test interaction
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// The effect of the interaction, for example "reduced gastric absorption of primary medication"
	Effect *CodeableConcept `json:"effect,omitempty" fhir:"cardinality=0..1,summary"`
	// The incidence of the interaction, e.g. theoretical, observed
	Incidence *CodeableConcept `json:"incidence,omitempty" fhir:"cardinality=0..1,summary"`
	// Actions for managing the interaction
	Management *CodeableConcept `json:"management,omitempty" fhir:"cardinality=0..1,summary"`
}
