// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeMedicinalProductIndication is the FHIR resource type name for MedicinalProductIndication.
const ResourceTypeMedicinalProductIndication = "MedicinalProductIndication"

// MedicinalProductIndicationOtherTherapy represents a FHIR BackboneElement for MedicinalProductIndication.otherTherapy.
type MedicinalProductIndicationOtherTherapy struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The type of relationship between the medicinal product indication or contraindication and another therapy
	TherapyRelationshipType CodeableConcept `json:"therapyRelationshipType" fhir:"cardinality=1..1,required,summary"`
	// Reference to a specific medication (active substance, medicinal product or class of products) as part of an indication or contraindication - CodeableConcept option
	MedicationCodeableConcept CodeableConcept `json:"medicationCodeableConcept" fhir:"cardinality=1..1,required,summary,choice=medication"`
	// Reference to a specific medication (active substance, medicinal product or class of products) as part of an indication or contraindication - Reference option
	MedicationReference Reference `json:"medicationReference" fhir:"cardinality=1..1,required,summary,choice=medication"`
}

// MedicinalProductIndication represents a FHIR MedicinalProductIndication.
type MedicinalProductIndication struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// The medication for which this is an indication
	Subject []Reference `json:"subject,omitempty" fhir:"cardinality=0..*,summary"`
	// The disease, symptom or procedure that is the indication for treatment
	DiseaseSymptomProcedure *CodeableConcept `json:"diseaseSymptomProcedure,omitempty" fhir:"cardinality=0..1,summary"`
	// The status of the disease or symptom for which the indication applies
	DiseaseStatus *CodeableConcept `json:"diseaseStatus,omitempty" fhir:"cardinality=0..1,summary"`
	// Comorbidity (concurrent condition) or co-infection as part of the indication
	Comorbidity []CodeableConcept `json:"comorbidity,omitempty" fhir:"cardinality=0..*,summary"`
	// The intended effect, aim or strategy to be achieved by the indication
	IntendedEffect *CodeableConcept `json:"intendedEffect,omitempty" fhir:"cardinality=0..1,summary"`
	// Timing or duration information as part of the indication
	Duration *Quantity `json:"duration,omitempty" fhir:"cardinality=0..1,summary"`
	// Information about the use of the medicinal product in relation to other therapies described as part of the indication
	OtherTherapy []MedicinalProductIndicationOtherTherapy `json:"otherTherapy,omitempty" fhir:"cardinality=0..*,summary"`
	// Describe the undesirable effects of the medicinal product
	UndesirableEffect []Reference `json:"undesirableEffect,omitempty" fhir:"cardinality=0..*,summary"`
	// The population group to which this applies
	Population []Population `json:"population,omitempty" fhir:"cardinality=0..*,summary"`
}
