// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeMedication is the FHIR resource type name for Medication.
const ResourceTypeMedication = "Medication"

// MedicationIngredient represents a FHIR BackboneElement for Medication.ingredient.
type MedicationIngredient struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The actual ingredient or content - CodeableConcept option
	ItemCodeableConcept CodeableConcept `json:"itemCodeableConcept" fhir:"cardinality=1..1,required,choice=item"`
	// The actual ingredient or content - Reference option
	ItemReference Reference `json:"itemReference" fhir:"cardinality=1..1,required,choice=item"`
	// Active ingredient indicator
	IsActive *bool `json:"isActive,omitempty" fhir:"cardinality=0..1"`
	// Extension for IsActive
	IsActiveExt *primitives.PrimitiveExtension `json:"_isActive,omitempty" fhir:"cardinality=0..1"`
	// Quantity of ingredient present
	Strength *Ratio `json:"strength,omitempty" fhir:"cardinality=0..1"`
}

// MedicationBatch represents a FHIR BackboneElement for Medication.batch.
type MedicationBatch struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Identifier assigned to batch
	LotNumber *string `json:"lotNumber,omitempty" fhir:"cardinality=0..1"`
	// Extension for LotNumber
	LotNumberExt *primitives.PrimitiveExtension `json:"_lotNumber,omitempty" fhir:"cardinality=0..1"`
	// When batch will expire
	ExpirationDate *primitives.DateTime `json:"expirationDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ExpirationDate
	ExpirationDateExt *primitives.PrimitiveExtension `json:"_expirationDate,omitempty" fhir:"cardinality=0..1"`
}

// Medication represents a FHIR Medication.
type Medication struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier for this medication
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Codes that identify this medication
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// active | inactive | entered-in-error
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Manufacturer of the item
	Manufacturer *Reference `json:"manufacturer,omitempty" fhir:"cardinality=0..1,summary"`
	// powder | tablets | capsule +
	Form *CodeableConcept `json:"form,omitempty" fhir:"cardinality=0..1"`
	// Amount of drug in package
	Amount *Ratio `json:"amount,omitempty" fhir:"cardinality=0..1,summary"`
	// Active or inactive ingredient
	Ingredient []MedicationIngredient `json:"ingredient,omitempty" fhir:"cardinality=0..*"`
	// Details about packaged medications
	Batch *MedicationBatch `json:"batch,omitempty" fhir:"cardinality=0..1"`
}
