// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// Money represents a FHIR Money.
type Money struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Numerical value (with implicit precision)
	Value *float64 `json:"value,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
	// ISO 4217 Currency Code
	Currency *string `json:"currency,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Currency
	CurrencyExt *primitives.PrimitiveExtension `json:"_currency,omitempty" fhir:"cardinality=0..1"`
}
