// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeNamingSystem is the FHIR resource type name for NamingSystem.
const ResourceTypeNamingSystem = "NamingSystem"

// NamingSystemUniqueId represents a FHIR BackboneElement for NamingSystem.uniqueId.
type NamingSystemUniqueId struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// oid | uuid | uri | other
	Type string `json:"type" fhir:"cardinality=1..1,required,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// The unique identifier
	Value string `json:"value" fhir:"cardinality=1..1,required,summary"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
	// Is this the id that should be used for this type
	Preferred *bool `json:"preferred,omitempty" fhir:"cardinality=0..1"`
	// Extension for Preferred
	PreferredExt *primitives.PrimitiveExtension `json:"_preferred,omitempty" fhir:"cardinality=0..1"`
	// Notes about identifier usage
	Comment *string `json:"comment,omitempty" fhir:"cardinality=0..1"`
	// Extension for Comment
	CommentExt *primitives.PrimitiveExtension `json:"_comment,omitempty" fhir:"cardinality=0..1"`
	// When is identifier valid?
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1"`
}

// NamingSystem represents a FHIR NamingSystem.
type NamingSystem struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Name for this naming system (computer friendly)
	Name string `json:"name" fhir:"cardinality=1..1,required,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// codesystem | identifier | root
	Kind string `json:"kind" fhir:"cardinality=1..1,required,summary"`
	// Extension for Kind
	KindExt *primitives.PrimitiveExtension `json:"_kind,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date primitives.DateTime `json:"date" fhir:"cardinality=1..1,required,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Who maintains system namespace?
	Responsible *string `json:"responsible,omitempty" fhir:"cardinality=0..1"`
	// Extension for Responsible
	ResponsibleExt *primitives.PrimitiveExtension `json:"_responsible,omitempty" fhir:"cardinality=0..1"`
	// e.g. driver,  provider,  patient, bank etc.
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Natural language description of the naming system
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for naming system (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// How/where is it used
	Usage *string `json:"usage,omitempty" fhir:"cardinality=0..1"`
	// Extension for Usage
	UsageExt *primitives.PrimitiveExtension `json:"_usage,omitempty" fhir:"cardinality=0..1"`
	// Unique identifiers used for system
	UniqueId []NamingSystemUniqueId `json:"uniqueId,omitempty" fhir:"cardinality=1..*,required,summary"`
}
