// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeObservationDefinition is the FHIR resource type name for ObservationDefinition.
const ResourceTypeObservationDefinition = "ObservationDefinition"

// ObservationDefinitionQuantitativeDetails represents a FHIR BackboneElement for ObservationDefinition.quantitativeDetails.
type ObservationDefinitionQuantitativeDetails struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Customary unit for quantitative results
	CustomaryUnit *CodeableConcept `json:"customaryUnit,omitempty" fhir:"cardinality=0..1"`
	// SI unit for quantitative results
	Unit *CodeableConcept `json:"unit,omitempty" fhir:"cardinality=0..1"`
	// SI to Customary unit conversion factor
	ConversionFactor *float64 `json:"conversionFactor,omitempty" fhir:"cardinality=0..1"`
	// Extension for ConversionFactor
	ConversionFactorExt *primitives.PrimitiveExtension `json:"_conversionFactor,omitempty" fhir:"cardinality=0..1"`
	// Decimal precision of observation quantitative results
	DecimalPrecision *int `json:"decimalPrecision,omitempty" fhir:"cardinality=0..1"`
	// Extension for DecimalPrecision
	DecimalPrecisionExt *primitives.PrimitiveExtension `json:"_decimalPrecision,omitempty" fhir:"cardinality=0..1"`
}

// ObservationDefinitionQualifiedInterval represents a FHIR BackboneElement for ObservationDefinition.qualifiedInterval.
type ObservationDefinitionQualifiedInterval struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// reference | critical | absolute
	Category *string `json:"category,omitempty" fhir:"cardinality=0..1"`
	// Extension for Category
	CategoryExt *primitives.PrimitiveExtension `json:"_category,omitempty" fhir:"cardinality=0..1"`
	// The interval itself, for continuous or ordinal observations
	Range *Range `json:"range,omitempty" fhir:"cardinality=0..1"`
	// Range context qualifier
	Context *CodeableConcept `json:"context,omitempty" fhir:"cardinality=0..1"`
	// Targetted population of the range
	AppliesTo []CodeableConcept `json:"appliesTo,omitempty" fhir:"cardinality=0..*"`
	// male | female | other | unknown
	Gender *string `json:"gender,omitempty" fhir:"cardinality=0..1"`
	// Extension for Gender
	GenderExt *primitives.PrimitiveExtension `json:"_gender,omitempty" fhir:"cardinality=0..1"`
	// Applicable age range, if relevant
	Age *Range `json:"age,omitempty" fhir:"cardinality=0..1"`
	// Applicable gestational age range, if relevant
	GestationalAge *Range `json:"gestationalAge,omitempty" fhir:"cardinality=0..1"`
	// Condition associated with the reference range
	Condition *string `json:"condition,omitempty" fhir:"cardinality=0..1"`
	// Extension for Condition
	ConditionExt *primitives.PrimitiveExtension `json:"_condition,omitempty" fhir:"cardinality=0..1"`
}

// ObservationDefinition represents a FHIR ObservationDefinition.
type ObservationDefinition struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Category of observation
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of observation (code / type)
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Business identifier for this ObservationDefinition instance
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Quantity | CodeableConcept | string | boolean | integer | Range | Ratio | SampledData | time | dateTime | Period
	PermittedDataType []string `json:"permittedDataType,omitempty" fhir:"cardinality=0..*"`
	// Extension for PermittedDataType
	PermittedDataTypeExt *primitives.PrimitiveExtension `json:"_permittedDataType,omitempty" fhir:"cardinality=0..1"`
	// Multiple results allowed
	MultipleResultsAllowed *bool `json:"multipleResultsAllowed,omitempty" fhir:"cardinality=0..1"`
	// Extension for MultipleResultsAllowed
	MultipleResultsAllowedExt *primitives.PrimitiveExtension `json:"_multipleResultsAllowed,omitempty" fhir:"cardinality=0..1"`
	// Method used to produce the observation
	Method *CodeableConcept `json:"method,omitempty" fhir:"cardinality=0..1"`
	// Preferred report name
	PreferredReportName *string `json:"preferredReportName,omitempty" fhir:"cardinality=0..1"`
	// Extension for PreferredReportName
	PreferredReportNameExt *primitives.PrimitiveExtension `json:"_preferredReportName,omitempty" fhir:"cardinality=0..1"`
	// Characteristics of quantitative results
	QuantitativeDetails *ObservationDefinitionQuantitativeDetails `json:"quantitativeDetails,omitempty" fhir:"cardinality=0..1"`
	// Qualified range for continuous and ordinal observation results
	QualifiedInterval []ObservationDefinitionQualifiedInterval `json:"qualifiedInterval,omitempty" fhir:"cardinality=0..*"`
	// Value set of valid coded values for the observations conforming to this ObservationDefinition
	ValidCodedValueSet *Reference `json:"validCodedValueSet,omitempty" fhir:"cardinality=0..1"`
	// Value set of normal coded values for the observations conforming to this ObservationDefinition
	NormalCodedValueSet *Reference `json:"normalCodedValueSet,omitempty" fhir:"cardinality=0..1"`
	// Value set of abnormal coded values for the observations conforming to this ObservationDefinition
	AbnormalCodedValueSet *Reference `json:"abnormalCodedValueSet,omitempty" fhir:"cardinality=0..1"`
	// Value set of critical coded values for the observations conforming to this ObservationDefinition
	CriticalCodedValueSet *Reference `json:"criticalCodedValueSet,omitempty" fhir:"cardinality=0..1"`
}
