// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeOrganization is the FHIR resource type name for Organization.
const ResourceTypeOrganization = "Organization"

// OrganizationContact represents a FHIR BackboneElement for Organization.contact.
type OrganizationContact struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The type of contact
	Purpose *CodeableConcept `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// A name associated with the contact
	Name *HumanName `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Contact details (telephone, email, etc.)  for a contact
	Telecom []ContactPoint `json:"telecom,omitempty" fhir:"cardinality=0..*"`
	// Visiting or postal addresses for the contact
	Address *Address `json:"address,omitempty" fhir:"cardinality=0..1"`
}

// Organization represents a FHIR Organization.
type Organization struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Identifies this organization  across multiple systems
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether the organization's record is still in active use
	Active *bool `json:"active,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Active
	ActiveExt *primitives.PrimitiveExtension `json:"_active,omitempty" fhir:"cardinality=0..1"`
	// Kind of organization
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*,summary"`
	// Name used for the organization
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// A list of alternate names that the organization is known as, or was known as in the past
	Alias []string `json:"alias,omitempty" fhir:"cardinality=0..*"`
	// Extension for Alias
	AliasExt *primitives.PrimitiveExtension `json:"_alias,omitempty" fhir:"cardinality=0..1"`
	// A contact detail for the organization
	Telecom []ContactPoint `json:"telecom,omitempty" fhir:"cardinality=0..*"`
	// An address for the organization
	Address []Address `json:"address,omitempty" fhir:"cardinality=0..*"`
	// The organization of which this organization forms a part
	PartOf *Reference `json:"partOf,omitempty" fhir:"cardinality=0..1,summary"`
	// Contact for the organization for a certain purpose
	Contact []OrganizationContact `json:"contact,omitempty" fhir:"cardinality=0..*"`
	// Technical endpoints providing access to services operated for the organization
	Endpoint []Reference `json:"endpoint,omitempty" fhir:"cardinality=0..*"`
}
