// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypePlanDefinition is the FHIR resource type name for PlanDefinition.
const ResourceTypePlanDefinition = "PlanDefinition"

// PlanDefinitionGoalTarget represents a FHIR BackboneElement for PlanDefinition.goal.target.
type PlanDefinitionGoalTarget struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The parameter whose value is to be tracked
	Measure *CodeableConcept `json:"measure,omitempty" fhir:"cardinality=0..1"`
	// The target value to be achieved - Quantity option
	DetailQuantity *Quantity `json:"detailQuantity,omitempty" fhir:"cardinality=0..1,choice=detail"`
	// The target value to be achieved - Range option
	DetailRange *Range `json:"detailRange,omitempty" fhir:"cardinality=0..1,choice=detail"`
	// The target value to be achieved - CodeableConcept option
	DetailCodeableConcept *CodeableConcept `json:"detailCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=detail"`
	// Reach goal within
	Due *Duration `json:"due,omitempty" fhir:"cardinality=0..1"`
}

// PlanDefinitionGoal represents a FHIR BackboneElement for PlanDefinition.goal.
type PlanDefinitionGoal struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// E.g. Treatment, dietary, behavioral
	Category *CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..1"`
	// Code or text describing the goal
	Description CodeableConcept `json:"description" fhir:"cardinality=1..1,required"`
	// high-priority | medium-priority | low-priority
	Priority *CodeableConcept `json:"priority,omitempty" fhir:"cardinality=0..1"`
	// When goal pursuit begins
	Start *CodeableConcept `json:"start,omitempty" fhir:"cardinality=0..1"`
	// What does the goal address
	Addresses []CodeableConcept `json:"addresses,omitempty" fhir:"cardinality=0..*"`
	// Supporting documentation for the goal
	Documentation []RelatedArtifact `json:"documentation,omitempty" fhir:"cardinality=0..*"`
	// Target outcome for the goal
	Target []PlanDefinitionGoalTarget `json:"target,omitempty" fhir:"cardinality=0..*"`
}

// PlanDefinitionActionCondition represents a FHIR BackboneElement for PlanDefinition.action.condition.
type PlanDefinitionActionCondition struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// applicability | start | stop
	Kind string `json:"kind" fhir:"cardinality=1..1,required"`
	// Extension for Kind
	KindExt *primitives.PrimitiveExtension `json:"_kind,omitempty" fhir:"cardinality=0..1"`
	// Boolean-valued expression
	Expression *Expression `json:"expression,omitempty" fhir:"cardinality=0..1"`
}

// PlanDefinitionActionRelatedAction represents a FHIR BackboneElement for PlanDefinition.action.relatedAction.
type PlanDefinitionActionRelatedAction struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// What action is this related to
	ActionId string `json:"actionId" fhir:"cardinality=1..1,required"`
	// Extension for ActionId
	ActionIdExt *primitives.PrimitiveExtension `json:"_actionId,omitempty" fhir:"cardinality=0..1"`
	// before-start | before | before-end | concurrent-with-start | concurrent | concurrent-with-end | after-start | after | after-end
	Relationship string `json:"relationship" fhir:"cardinality=1..1,required"`
	// Extension for Relationship
	RelationshipExt *primitives.PrimitiveExtension `json:"_relationship,omitempty" fhir:"cardinality=0..1"`
	// Time offset for the relationship - Duration option
	OffsetDuration *Duration `json:"offsetDuration,omitempty" fhir:"cardinality=0..1,choice=offset"`
	// Time offset for the relationship - Range option
	OffsetRange *Range `json:"offsetRange,omitempty" fhir:"cardinality=0..1,choice=offset"`
}

// PlanDefinitionActionParticipant represents a FHIR BackboneElement for PlanDefinition.action.participant.
type PlanDefinitionActionParticipant struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// patient | practitioner | related-person | device
	Type string `json:"type" fhir:"cardinality=1..1,required"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// E.g. Nurse, Surgeon, Parent
	Role *CodeableConcept `json:"role,omitempty" fhir:"cardinality=0..1"`
}

// PlanDefinitionActionDynamicValue represents a FHIR BackboneElement for PlanDefinition.action.dynamicValue.
type PlanDefinitionActionDynamicValue struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The path to the element to be set dynamically
	Path *string `json:"path,omitempty" fhir:"cardinality=0..1"`
	// Extension for Path
	PathExt *primitives.PrimitiveExtension `json:"_path,omitempty" fhir:"cardinality=0..1"`
	// An expression that provides the dynamic value for the customization
	Expression *Expression `json:"expression,omitempty" fhir:"cardinality=0..1"`
}

// PlanDefinitionActionAction represents a FHIR BackboneElement for PlanDefinition.action.action.
type PlanDefinitionActionAction struct {
}

// PlanDefinitionAction represents a FHIR BackboneElement for PlanDefinition.action.
type PlanDefinitionAction struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// User-visible prefix for the action (e.g. 1. or A.)
	Prefix *string `json:"prefix,omitempty" fhir:"cardinality=0..1"`
	// Extension for Prefix
	PrefixExt *primitives.PrimitiveExtension `json:"_prefix,omitempty" fhir:"cardinality=0..1"`
	// User-visible title
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Brief description of the action
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Static text equivalent of the action, used if the dynamic aspects cannot be interpreted by the receiving system
	TextEquivalent *string `json:"textEquivalent,omitempty" fhir:"cardinality=0..1"`
	// Extension for TextEquivalent
	TextEquivalentExt *primitives.PrimitiveExtension `json:"_textEquivalent,omitempty" fhir:"cardinality=0..1"`
	// routine | urgent | asap | stat
	Priority *string `json:"priority,omitempty" fhir:"cardinality=0..1"`
	// Extension for Priority
	PriorityExt *primitives.PrimitiveExtension `json:"_priority,omitempty" fhir:"cardinality=0..1"`
	// Code representing the meaning of the action or sub-actions
	Code []CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..*"`
	// Why the action should be performed
	Reason []CodeableConcept `json:"reason,omitempty" fhir:"cardinality=0..*"`
	// Supporting documentation for the intended performer of the action
	Documentation []RelatedArtifact `json:"documentation,omitempty" fhir:"cardinality=0..*"`
	// What goals this action supports
	GoalId []string `json:"goalId,omitempty" fhir:"cardinality=0..*"`
	// Extension for GoalId
	GoalIdExt *primitives.PrimitiveExtension `json:"_goalId,omitempty" fhir:"cardinality=0..1"`
	// Type of individual the action is focused on - CodeableConcept option
	SubjectCodeableConcept *CodeableConcept `json:"subjectCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=subject"`
	// Type of individual the action is focused on - Reference option
	SubjectReference *Reference `json:"subjectReference,omitempty" fhir:"cardinality=0..1,choice=subject"`
	// When the action should be triggered
	Trigger []TriggerDefinition `json:"trigger,omitempty" fhir:"cardinality=0..*"`
	// Whether or not the action is applicable
	Condition []PlanDefinitionActionCondition `json:"condition,omitempty" fhir:"cardinality=0..*"`
	// Input data requirements
	Input []DataRequirement `json:"input,omitempty" fhir:"cardinality=0..*"`
	// Output data definition
	Output []DataRequirement `json:"output,omitempty" fhir:"cardinality=0..*"`
	// Relationship to another action
	RelatedAction []PlanDefinitionActionRelatedAction `json:"relatedAction,omitempty" fhir:"cardinality=0..*"`
	// When the action should take place - dateTime option
	TimingDateTime *primitives.DateTime `json:"timingDateTime,omitempty" fhir:"cardinality=0..1,choice=timing"`
	// Extension for TimingDateTime
	TimingDateTimeExt *primitives.PrimitiveExtension `json:"_timingDateTime,omitempty" fhir:"cardinality=0..1"`
	// When the action should take place - Age option
	TimingAge *Age `json:"timingAge,omitempty" fhir:"cardinality=0..1,choice=timing"`
	// When the action should take place - Period option
	TimingPeriod *Period `json:"timingPeriod,omitempty" fhir:"cardinality=0..1,choice=timing"`
	// When the action should take place - Duration option
	TimingDuration *Duration `json:"timingDuration,omitempty" fhir:"cardinality=0..1,choice=timing"`
	// When the action should take place - Range option
	TimingRange *Range `json:"timingRange,omitempty" fhir:"cardinality=0..1,choice=timing"`
	// When the action should take place - Timing option
	TimingTiming *Timing `json:"timingTiming,omitempty" fhir:"cardinality=0..1,choice=timing"`
	// Who should participate in the action
	Participant []PlanDefinitionActionParticipant `json:"participant,omitempty" fhir:"cardinality=0..*"`
	// create | update | remove | fire-event
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// visual-group | logical-group | sentence-group
	GroupingBehavior *string `json:"groupingBehavior,omitempty" fhir:"cardinality=0..1"`
	// Extension for GroupingBehavior
	GroupingBehaviorExt *primitives.PrimitiveExtension `json:"_groupingBehavior,omitempty" fhir:"cardinality=0..1"`
	// any | all | all-or-none | exactly-one | at-most-one | one-or-more
	SelectionBehavior *string `json:"selectionBehavior,omitempty" fhir:"cardinality=0..1"`
	// Extension for SelectionBehavior
	SelectionBehaviorExt *primitives.PrimitiveExtension `json:"_selectionBehavior,omitempty" fhir:"cardinality=0..1"`
	// must | could | must-unless-documented
	RequiredBehavior *string `json:"requiredBehavior,omitempty" fhir:"cardinality=0..1"`
	// Extension for RequiredBehavior
	RequiredBehaviorExt *primitives.PrimitiveExtension `json:"_requiredBehavior,omitempty" fhir:"cardinality=0..1"`
	// yes | no
	PrecheckBehavior *string `json:"precheckBehavior,omitempty" fhir:"cardinality=0..1"`
	// Extension for PrecheckBehavior
	PrecheckBehaviorExt *primitives.PrimitiveExtension `json:"_precheckBehavior,omitempty" fhir:"cardinality=0..1"`
	// single | multiple
	CardinalityBehavior *string `json:"cardinalityBehavior,omitempty" fhir:"cardinality=0..1"`
	// Extension for CardinalityBehavior
	CardinalityBehaviorExt *primitives.PrimitiveExtension `json:"_cardinalityBehavior,omitempty" fhir:"cardinality=0..1"`
	// Description of the activity to be performed - canonical option
	DefinitionCanonical *string `json:"definitionCanonical,omitempty" fhir:"cardinality=0..1,choice=definition"`
	// Extension for DefinitionCanonical
	DefinitionCanonicalExt *primitives.PrimitiveExtension `json:"_definitionCanonical,omitempty" fhir:"cardinality=0..1"`
	// Description of the activity to be performed - uri option
	DefinitionURI *string `json:"definitionURI,omitempty" fhir:"cardinality=0..1,choice=definition"`
	// Extension for DefinitionURI
	DefinitionURIExt *primitives.PrimitiveExtension `json:"_definitionURI,omitempty" fhir:"cardinality=0..1"`
	// Transform to apply the template
	Transform *string `json:"transform,omitempty" fhir:"cardinality=0..1"`
	// Extension for Transform
	TransformExt *primitives.PrimitiveExtension `json:"_transform,omitempty" fhir:"cardinality=0..1"`
	// Dynamic aspects of the definition
	DynamicValue []PlanDefinitionActionDynamicValue `json:"dynamicValue,omitempty" fhir:"cardinality=0..*"`
	// A sub-action
	Action []PlanDefinitionActionAction `json:"action,omitempty" fhir:"cardinality=0..*"`
}

// PlanDefinition represents a FHIR PlanDefinition.
type PlanDefinition struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this plan definition, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the plan definition
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the plan definition
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Name for this plan definition (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this plan definition (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Subordinate title of the plan definition
	Subtitle *string `json:"subtitle,omitempty" fhir:"cardinality=0..1"`
	// Extension for Subtitle
	SubtitleExt *primitives.PrimitiveExtension `json:"_subtitle,omitempty" fhir:"cardinality=0..1"`
	// order-set | clinical-protocol | eca-rule | workflow-definition
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Type of individual the plan definition is focused on - CodeableConcept option
	SubjectCodeableConcept *CodeableConcept `json:"subjectCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=subject"`
	// Type of individual the plan definition is focused on - Reference option
	SubjectReference *Reference `json:"subjectReference,omitempty" fhir:"cardinality=0..1,choice=subject"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the plan definition
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for plan definition (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this plan definition is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Describes the clinical usage of the plan
	Usage *string `json:"usage,omitempty" fhir:"cardinality=0..1"`
	// Extension for Usage
	UsageExt *primitives.PrimitiveExtension `json:"_usage,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// When the plan definition was approved by publisher
	ApprovalDate *primitives.Date `json:"approvalDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ApprovalDate
	ApprovalDateExt *primitives.PrimitiveExtension `json:"_approvalDate,omitempty" fhir:"cardinality=0..1"`
	// When the plan definition was last reviewed
	LastReviewDate *primitives.Date `json:"lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for LastReviewDate
	LastReviewDateExt *primitives.PrimitiveExtension `json:"_lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// When the plan definition is expected to be used
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary"`
	// E.g. Education, Treatment, Assessment
	Topic []CodeableConcept `json:"topic,omitempty" fhir:"cardinality=0..*"`
	// Who authored the content
	Author []ContactDetail `json:"author,omitempty" fhir:"cardinality=0..*"`
	// Who edited the content
	Editor []ContactDetail `json:"editor,omitempty" fhir:"cardinality=0..*"`
	// Who reviewed the content
	Reviewer []ContactDetail `json:"reviewer,omitempty" fhir:"cardinality=0..*"`
	// Who endorsed the content
	Endorser []ContactDetail `json:"endorser,omitempty" fhir:"cardinality=0..*"`
	// Additional documentation, citations
	RelatedArtifact []RelatedArtifact `json:"relatedArtifact,omitempty" fhir:"cardinality=0..*"`
	// Logic used by the plan definition
	Library []string `json:"library,omitempty" fhir:"cardinality=0..*"`
	// Extension for Library
	LibraryExt *primitives.PrimitiveExtension `json:"_library,omitempty" fhir:"cardinality=0..1"`
	// What the plan is trying to accomplish
	Goal []PlanDefinitionGoal `json:"goal,omitempty" fhir:"cardinality=0..*"`
	// Action defined by the plan
	Action []PlanDefinitionAction `json:"action,omitempty" fhir:"cardinality=0..*"`
}
