// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypePractitionerRole is the FHIR resource type name for PractitionerRole.
const ResourceTypePractitionerRole = "PractitionerRole"

// PractitionerRoleAvailableTime represents a FHIR BackboneElement for PractitionerRole.availableTime.
type PractitionerRoleAvailableTime struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// mon | tue | wed | thu | fri | sat | sun
	DaysOfWeek []string `json:"daysOfWeek,omitempty" fhir:"cardinality=0..*"`
	// Extension for DaysOfWeek
	DaysOfWeekExt *primitives.PrimitiveExtension `json:"_daysOfWeek,omitempty" fhir:"cardinality=0..1"`
	// Always available? e.g. 24 hour service
	AllDay *bool `json:"allDay,omitempty" fhir:"cardinality=0..1"`
	// Extension for AllDay
	AllDayExt *primitives.PrimitiveExtension `json:"_allDay,omitempty" fhir:"cardinality=0..1"`
	// Opening time of day (ignored if allDay = true)
	AvailableStartTime *primitives.Time `json:"availableStartTime,omitempty" fhir:"cardinality=0..1"`
	// Extension for AvailableStartTime
	AvailableStartTimeExt *primitives.PrimitiveExtension `json:"_availableStartTime,omitempty" fhir:"cardinality=0..1"`
	// Closing time of day (ignored if allDay = true)
	AvailableEndTime *primitives.Time `json:"availableEndTime,omitempty" fhir:"cardinality=0..1"`
	// Extension for AvailableEndTime
	AvailableEndTimeExt *primitives.PrimitiveExtension `json:"_availableEndTime,omitempty" fhir:"cardinality=0..1"`
}

// PractitionerRoleNotAvailable represents a FHIR BackboneElement for PractitionerRole.notAvailable.
type PractitionerRoleNotAvailable struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Reason presented to the user explaining why time not available
	Description string `json:"description" fhir:"cardinality=1..1,required"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Service not available from this date
	During *Period `json:"during,omitempty" fhir:"cardinality=0..1"`
}

// PractitionerRole represents a FHIR PractitionerRole.
type PractitionerRole struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business Identifiers that are specific to a role/location
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether this practitioner role record is in active use
	Active *bool `json:"active,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Active
	ActiveExt *primitives.PrimitiveExtension `json:"_active,omitempty" fhir:"cardinality=0..1"`
	// The period during which the practitioner is authorized to perform in these role(s)
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Practitioner that is able to provide the defined services for the organization
	Practitioner *Reference `json:"practitioner,omitempty" fhir:"cardinality=0..1,summary"`
	// Organization where the roles are available
	Organization *Reference `json:"organization,omitempty" fhir:"cardinality=0..1,summary"`
	// Roles which this practitioner may perform
	Code []CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..*,summary"`
	// Specific specialty of the practitioner
	Specialty []CodeableConcept `json:"specialty,omitempty" fhir:"cardinality=0..*,summary"`
	// The location(s) at which this practitioner provides care
	Location []Reference `json:"location,omitempty" fhir:"cardinality=0..*,summary"`
	// The list of healthcare services that this worker provides for this role's Organization/Location(s)
	HealthcareService []Reference `json:"healthcareService,omitempty" fhir:"cardinality=0..*"`
	// Contact details that are specific to the role/location/service
	Telecom []ContactPoint `json:"telecom,omitempty" fhir:"cardinality=0..*,summary"`
	// Times the Service Site is available
	AvailableTime []PractitionerRoleAvailableTime `json:"availableTime,omitempty" fhir:"cardinality=0..*"`
	// Not available during this time due to provided reason
	NotAvailable []PractitionerRoleNotAvailable `json:"notAvailable,omitempty" fhir:"cardinality=0..*"`
	// Description of availability exceptions
	AvailabilityExceptions *string `json:"availabilityExceptions,omitempty" fhir:"cardinality=0..1"`
	// Extension for AvailabilityExceptions
	AvailabilityExceptionsExt *primitives.PrimitiveExtension `json:"_availabilityExceptions,omitempty" fhir:"cardinality=0..1"`
	// Technical endpoints providing access to services operated for the practitioner with this role
	Endpoint []Reference `json:"endpoint,omitempty" fhir:"cardinality=0..*"`
}
