// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeProcedure is the FHIR resource type name for Procedure.
const ResourceTypeProcedure = "Procedure"

// ProcedurePerformer represents a FHIR BackboneElement for Procedure.performer.
type ProcedurePerformer struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of performance
	Function *CodeableConcept `json:"function,omitempty" fhir:"cardinality=0..1,summary"`
	// The reference to the practitioner
	Actor Reference `json:"actor" fhir:"cardinality=1..1,required,summary"`
	// Organization the device or practitioner was acting for
	OnBehalfOf *Reference `json:"onBehalfOf,omitempty" fhir:"cardinality=0..1"`
}

// ProcedureFocalDevice represents a FHIR BackboneElement for Procedure.focalDevice.
type ProcedureFocalDevice struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Kind of change to device
	Action *CodeableConcept `json:"action,omitempty" fhir:"cardinality=0..1"`
	// Device that was changed
	Manipulated Reference `json:"manipulated" fhir:"cardinality=1..1,required"`
}

// Procedure represents a FHIR Procedure.
type Procedure struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External Identifiers for this procedure
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Instantiates FHIR protocol or definition
	InstantiatesCanonical []string `json:"instantiatesCanonical,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for InstantiatesCanonical
	InstantiatesCanonicalExt *primitives.PrimitiveExtension `json:"_instantiatesCanonical,omitempty" fhir:"cardinality=0..1"`
	// Instantiates external protocol or definition
	InstantiatesUri []string `json:"instantiatesUri,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for InstantiatesUri
	InstantiatesUriExt *primitives.PrimitiveExtension `json:"_instantiatesUri,omitempty" fhir:"cardinality=0..1"`
	// A request for this procedure
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// Part of referenced event
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*,summary"`
	// preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Reason for current status
	StatusReason *CodeableConcept `json:"statusReason,omitempty" fhir:"cardinality=0..1,summary"`
	// Classification of the procedure
	Category *CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..1,summary"`
	// Identification of the procedure
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// Who the procedure was performed on
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// Encounter created as part of
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// When the procedure was performed - dateTime option
	PerformedDateTime *primitives.DateTime `json:"performedDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=performed"`
	// Extension for PerformedDateTime
	PerformedDateTimeExt *primitives.PrimitiveExtension `json:"_performedDateTime,omitempty" fhir:"cardinality=0..1"`
	// When the procedure was performed - Period option
	PerformedPeriod *Period `json:"performedPeriod,omitempty" fhir:"cardinality=0..1,summary,choice=performed"`
	// When the procedure was performed - string option
	PerformedString *string `json:"performedString,omitempty" fhir:"cardinality=0..1,summary,choice=performed"`
	// Extension for PerformedString
	PerformedStringExt *primitives.PrimitiveExtension `json:"_performedString,omitempty" fhir:"cardinality=0..1"`
	// When the procedure was performed - Age option
	PerformedAge *Age `json:"performedAge,omitempty" fhir:"cardinality=0..1,summary,choice=performed"`
	// When the procedure was performed - Range option
	PerformedRange *Range `json:"performedRange,omitempty" fhir:"cardinality=0..1,summary,choice=performed"`
	// Who recorded the procedure
	Recorder *Reference `json:"recorder,omitempty" fhir:"cardinality=0..1,summary"`
	// Person who asserts this procedure
	Asserter *Reference `json:"asserter,omitempty" fhir:"cardinality=0..1,summary"`
	// The people who performed the procedure
	Performer []ProcedurePerformer `json:"performer,omitempty" fhir:"cardinality=0..*,summary"`
	// Where the procedure happened
	Location *Reference `json:"location,omitempty" fhir:"cardinality=0..1,summary"`
	// Coded reason procedure performed
	ReasonCode []CodeableConcept `json:"reasonCode,omitempty" fhir:"cardinality=0..*,summary"`
	// The justification that the procedure was performed
	ReasonReference []Reference `json:"reasonReference,omitempty" fhir:"cardinality=0..*,summary"`
	// Target body sites
	BodySite []CodeableConcept `json:"bodySite,omitempty" fhir:"cardinality=0..*,summary"`
	// The result of procedure
	Outcome *CodeableConcept `json:"outcome,omitempty" fhir:"cardinality=0..1,summary"`
	// Any report resulting from the procedure
	Report []Reference `json:"report,omitempty" fhir:"cardinality=0..*"`
	// Complication following the procedure
	Complication []CodeableConcept `json:"complication,omitempty" fhir:"cardinality=0..*"`
	// A condition that is a result of the procedure
	ComplicationDetail []Reference `json:"complicationDetail,omitempty" fhir:"cardinality=0..*"`
	// Instructions for follow up
	FollowUp []CodeableConcept `json:"followUp,omitempty" fhir:"cardinality=0..*"`
	// Additional information about the procedure
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// Manipulated, implanted, or removed device
	FocalDevice []ProcedureFocalDevice `json:"focalDevice,omitempty" fhir:"cardinality=0..*"`
	// Items used during procedure
	UsedReference []Reference `json:"usedReference,omitempty" fhir:"cardinality=0..*"`
	// Coded items used during the procedure
	UsedCode []CodeableConcept `json:"usedCode,omitempty" fhir:"cardinality=0..*"`
}
