// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ProdCharacteristic represents a FHIR ProdCharacteristic.
type ProdCharacteristic struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Where applicable, the height can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
	Height *Quantity `json:"height,omitempty" fhir:"cardinality=0..1,summary"`
	// Where applicable, the width can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
	Width *Quantity `json:"width,omitempty" fhir:"cardinality=0..1,summary"`
	// Where applicable, the depth can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
	Depth *Quantity `json:"depth,omitempty" fhir:"cardinality=0..1,summary"`
	// Where applicable, the weight can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
	Weight *Quantity `json:"weight,omitempty" fhir:"cardinality=0..1,summary"`
	// Where applicable, the nominal volume can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
	NominalVolume *Quantity `json:"nominalVolume,omitempty" fhir:"cardinality=0..1,summary"`
	// Where applicable, the external diameter can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
	ExternalDiameter *Quantity `json:"externalDiameter,omitempty" fhir:"cardinality=0..1,summary"`
	// Where applicable, the shape can be specified An appropriate controlled vocabulary shall be used The term and the term identifier shall be used
	Shape *string `json:"shape,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Shape
	ShapeExt *primitives.PrimitiveExtension `json:"_shape,omitempty" fhir:"cardinality=0..1"`
	// Where applicable, the color can be specified An appropriate controlled vocabulary shall be used The term and the term identifier shall be used
	Color []string `json:"color,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for Color
	ColorExt *primitives.PrimitiveExtension `json:"_color,omitempty" fhir:"cardinality=0..1"`
	// Where applicable, the imprint can be specified as text
	Imprint []string `json:"imprint,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for Imprint
	ImprintExt *primitives.PrimitiveExtension `json:"_imprint,omitempty" fhir:"cardinality=0..1"`
	// Where applicable, the image can be provided The format of the image attachment shall be specified by regional implementations
	Image []Attachment `json:"image,omitempty" fhir:"cardinality=0..*,summary"`
	// Where applicable, the scoring can be specified An appropriate controlled vocabulary shall be used The term and the term identifier shall be used
	Scoring *CodeableConcept `json:"scoring,omitempty" fhir:"cardinality=0..1,summary"`
}
