// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeQuestionnaireResponse is the FHIR resource type name for QuestionnaireResponse.
const ResourceTypeQuestionnaireResponse = "QuestionnaireResponse"

// QuestionnaireResponseItemAnswerItem represents a FHIR BackboneElement for QuestionnaireResponse.item.answer.item.
type QuestionnaireResponseItemAnswerItem struct {
}

// QuestionnaireResponseItemAnswer represents a FHIR BackboneElement for QuestionnaireResponse.item.answer.
type QuestionnaireResponseItemAnswer struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Single-valued answer to the question - boolean option
	ValueBoolean *bool `json:"valueBoolean,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
	// Single-valued answer to the question - decimal option
	ValueDecimal *float64 `json:"valueDecimal,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueDecimal
	ValueDecimalExt *primitives.PrimitiveExtension `json:"_valueDecimal,omitempty" fhir:"cardinality=0..1"`
	// Single-valued answer to the question - integer option
	ValueInteger *int `json:"valueInteger,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueInteger
	ValueIntegerExt *primitives.PrimitiveExtension `json:"_valueInteger,omitempty" fhir:"cardinality=0..1"`
	// Single-valued answer to the question - date option
	ValueDate *primitives.Date `json:"valueDate,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueDate
	ValueDateExt *primitives.PrimitiveExtension `json:"_valueDate,omitempty" fhir:"cardinality=0..1"`
	// Single-valued answer to the question - dateTime option
	ValueDateTime *primitives.DateTime `json:"valueDateTime,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueDateTime
	ValueDateTimeExt *primitives.PrimitiveExtension `json:"_valueDateTime,omitempty" fhir:"cardinality=0..1"`
	// Single-valued answer to the question - time option
	ValueTime *primitives.Time `json:"valueTime,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueTime
	ValueTimeExt *primitives.PrimitiveExtension `json:"_valueTime,omitempty" fhir:"cardinality=0..1"`
	// Single-valued answer to the question - string option
	ValueString *string `json:"valueString,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueString
	ValueStringExt *primitives.PrimitiveExtension `json:"_valueString,omitempty" fhir:"cardinality=0..1"`
	// Single-valued answer to the question - uri option
	ValueURI *string `json:"valueURI,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueURI
	ValueURIExt *primitives.PrimitiveExtension `json:"_valueURI,omitempty" fhir:"cardinality=0..1"`
	// Single-valued answer to the question - Attachment option
	ValueAttachment *Attachment `json:"valueAttachment,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Single-valued answer to the question - Coding option
	ValueCoding *Coding `json:"valueCoding,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Single-valued answer to the question - Quantity option
	ValueQuantity *Quantity `json:"valueQuantity,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Single-valued answer to the question - Reference option
	ValueReference *Reference `json:"valueReference,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Nested groups and questions
	Item []QuestionnaireResponseItemAnswerItem `json:"item,omitempty" fhir:"cardinality=0..*"`
}

// QuestionnaireResponseItemItem represents a FHIR BackboneElement for QuestionnaireResponse.item.item.
type QuestionnaireResponseItemItem struct {
}

// QuestionnaireResponseItem represents a FHIR BackboneElement for QuestionnaireResponse.item.
type QuestionnaireResponseItem struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Pointer to specific item from Questionnaire
	LinkId string `json:"linkId" fhir:"cardinality=1..1,required"`
	// Extension for LinkId
	LinkIdExt *primitives.PrimitiveExtension `json:"_linkId,omitempty" fhir:"cardinality=0..1"`
	// ElementDefinition - details for the item
	Definition *string `json:"definition,omitempty" fhir:"cardinality=0..1"`
	// Extension for Definition
	DefinitionExt *primitives.PrimitiveExtension `json:"_definition,omitempty" fhir:"cardinality=0..1"`
	// Name for group or question text
	Text *string `json:"text,omitempty" fhir:"cardinality=0..1"`
	// Extension for Text
	TextExt *primitives.PrimitiveExtension `json:"_text,omitempty" fhir:"cardinality=0..1"`
	// The response(s) to the question
	Answer []QuestionnaireResponseItemAnswer `json:"answer,omitempty" fhir:"cardinality=0..*"`
	// Nested questionnaire response items
	Item []QuestionnaireResponseItemItem `json:"item,omitempty" fhir:"cardinality=0..*"`
}

// QuestionnaireResponse represents a FHIR QuestionnaireResponse.
type QuestionnaireResponse struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Unique id for this set of answers
	Identifier *Identifier `json:"identifier,omitempty" fhir:"cardinality=0..1,summary"`
	// Request fulfilled by this QuestionnaireResponse
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// Part of this action
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*,summary"`
	// Form being answered
	Questionnaire *string `json:"questionnaire,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Questionnaire
	QuestionnaireExt *primitives.PrimitiveExtension `json:"_questionnaire,omitempty" fhir:"cardinality=0..1"`
	// in-progress | completed | amended | entered-in-error | stopped
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// The subject of the questions
	Subject *Reference `json:"subject,omitempty" fhir:"cardinality=0..1,summary"`
	// Encounter created as part of
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// Date the answers were gathered
	Authored *primitives.DateTime `json:"authored,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Authored
	AuthoredExt *primitives.PrimitiveExtension `json:"_authored,omitempty" fhir:"cardinality=0..1"`
	// Person who received and recorded the answers
	Author *Reference `json:"author,omitempty" fhir:"cardinality=0..1,summary"`
	// The person who answered the questions
	Source *Reference `json:"source,omitempty" fhir:"cardinality=0..1,summary"`
	// Groups and questions
	Item []QuestionnaireResponseItem `json:"item,omitempty" fhir:"cardinality=0..*"`
}
