// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// Ratio represents a FHIR Ratio.
type Ratio struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Numerator value
	Numerator *Quantity `json:"numerator,omitempty" fhir:"cardinality=0..1,summary"`
	// Denominator value
	Denominator *Quantity `json:"denominator,omitempty" fhir:"cardinality=0..1,summary"`
}
