// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeResearchSubject is the FHIR resource type name for ResearchSubject.
const ResourceTypeResearchSubject = "ResearchSubject"

// ResearchSubject represents a FHIR ResearchSubject.
type ResearchSubject struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business Identifier for research subject in a study
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Start and end of participation
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Study subject is part of
	Study Reference `json:"study" fhir:"cardinality=1..1,required,summary"`
	// Who is part of study
	Individual Reference `json:"individual" fhir:"cardinality=1..1,required,summary"`
	// What path should be followed
	AssignedArm *string `json:"assignedArm,omitempty" fhir:"cardinality=0..1"`
	// Extension for AssignedArm
	AssignedArmExt *primitives.PrimitiveExtension `json:"_assignedArm,omitempty" fhir:"cardinality=0..1"`
	// What path was followed
	ActualArm *string `json:"actualArm,omitempty" fhir:"cardinality=0..1"`
	// Extension for ActualArm
	ActualArmExt *primitives.PrimitiveExtension `json:"_actualArm,omitempty" fhir:"cardinality=0..1"`
	// Agreement to participate in study
	Consent *Reference `json:"consent,omitempty" fhir:"cardinality=0..1"`
}
