// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeResearchDefinition is the FHIR resource type name for ResearchDefinition.
const ResourceTypeResearchDefinition = "ResearchDefinition"

// ResearchDefinition represents a FHIR ResearchDefinition.
type ResearchDefinition struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this research definition, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the research definition
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the research definition
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Name for this research definition (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this research definition (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Title for use in informal contexts
	ShortTitle *string `json:"shortTitle,omitempty" fhir:"cardinality=0..1"`
	// Extension for ShortTitle
	ShortTitleExt *primitives.PrimitiveExtension `json:"_shortTitle,omitempty" fhir:"cardinality=0..1"`
	// Subordinate title of the ResearchDefinition
	Subtitle *string `json:"subtitle,omitempty" fhir:"cardinality=0..1"`
	// Extension for Subtitle
	SubtitleExt *primitives.PrimitiveExtension `json:"_subtitle,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// E.g. Patient, Practitioner, RelatedPerson, Organization, Location, Device - CodeableConcept option
	SubjectCodeableConcept *CodeableConcept `json:"subjectCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=subject"`
	// E.g. Patient, Practitioner, RelatedPerson, Organization, Location, Device - Reference option
	SubjectReference *Reference `json:"subjectReference,omitempty" fhir:"cardinality=0..1,choice=subject"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the research definition
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Used for footnotes or explanatory notes
	Comment []string `json:"comment,omitempty" fhir:"cardinality=0..*"`
	// Extension for Comment
	CommentExt *primitives.PrimitiveExtension `json:"_comment,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for research definition (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this research definition is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Describes the clinical usage of the ResearchDefinition
	Usage *string `json:"usage,omitempty" fhir:"cardinality=0..1"`
	// Extension for Usage
	UsageExt *primitives.PrimitiveExtension `json:"_usage,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// When the research definition was approved by publisher
	ApprovalDate *primitives.Date `json:"approvalDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ApprovalDate
	ApprovalDateExt *primitives.PrimitiveExtension `json:"_approvalDate,omitempty" fhir:"cardinality=0..1"`
	// When the research definition was last reviewed
	LastReviewDate *primitives.Date `json:"lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for LastReviewDate
	LastReviewDateExt *primitives.PrimitiveExtension `json:"_lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// When the research definition is expected to be used
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary"`
	// The category of the ResearchDefinition, such as Education, Treatment, Assessment, etc.
	Topic []CodeableConcept `json:"topic,omitempty" fhir:"cardinality=0..*"`
	// Who authored the content
	Author []ContactDetail `json:"author,omitempty" fhir:"cardinality=0..*"`
	// Who edited the content
	Editor []ContactDetail `json:"editor,omitempty" fhir:"cardinality=0..*"`
	// Who reviewed the content
	Reviewer []ContactDetail `json:"reviewer,omitempty" fhir:"cardinality=0..*"`
	// Who endorsed the content
	Endorser []ContactDetail `json:"endorser,omitempty" fhir:"cardinality=0..*"`
	// Additional documentation, citations, etc.
	RelatedArtifact []RelatedArtifact `json:"relatedArtifact,omitempty" fhir:"cardinality=0..*"`
	// Logic used by the ResearchDefinition
	Library []string `json:"library,omitempty" fhir:"cardinality=0..*"`
	// Extension for Library
	LibraryExt *primitives.PrimitiveExtension `json:"_library,omitempty" fhir:"cardinality=0..1"`
	// What population?
	Population Reference `json:"population" fhir:"cardinality=1..1,required,summary"`
	// What exposure?
	Exposure *Reference `json:"exposure,omitempty" fhir:"cardinality=0..1,summary"`
	// What alternative exposure state?
	ExposureAlternative *Reference `json:"exposureAlternative,omitempty" fhir:"cardinality=0..1,summary"`
	// What outcome?
	Outcome *Reference `json:"outcome,omitempty" fhir:"cardinality=0..1,summary"`
}
