// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// SampledData represents a FHIR SampledData.
type SampledData struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Zero value and units
	Origin Quantity `json:"origin" fhir:"cardinality=1..1,required,summary"`
	// Number of milliseconds between samples
	Period float64 `json:"period" fhir:"cardinality=1..1,required,summary"`
	// Extension for Period
	PeriodExt *primitives.PrimitiveExtension `json:"_period,omitempty" fhir:"cardinality=0..1"`
	// Multiply data by this before adding to origin
	Factor *float64 `json:"factor,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Factor
	FactorExt *primitives.PrimitiveExtension `json:"_factor,omitempty" fhir:"cardinality=0..1"`
	// Lower limit of detection
	LowerLimit *float64 `json:"lowerLimit,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for LowerLimit
	LowerLimitExt *primitives.PrimitiveExtension `json:"_lowerLimit,omitempty" fhir:"cardinality=0..1"`
	// Upper limit of detection
	UpperLimit *float64 `json:"upperLimit,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for UpperLimit
	UpperLimitExt *primitives.PrimitiveExtension `json:"_upperLimit,omitempty" fhir:"cardinality=0..1"`
	// Number of sample points at each time point
	Dimensions int `json:"dimensions" fhir:"cardinality=1..1,required,summary"`
	// Extension for Dimensions
	DimensionsExt *primitives.PrimitiveExtension `json:"_dimensions,omitempty" fhir:"cardinality=0..1"`
	// Decimal values with spaces, or "E" | "U" | "L"
	Data *string `json:"data,omitempty" fhir:"cardinality=0..1"`
	// Extension for Data
	DataExt *primitives.PrimitiveExtension `json:"_data,omitempty" fhir:"cardinality=0..1"`
}
