// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeSearchParameter is the FHIR resource type name for SearchParameter.
const ResourceTypeSearchParameter = "SearchParameter"

// SearchParameterComponent represents a FHIR BackboneElement for SearchParameter.component.
type SearchParameterComponent struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Defines how the part works
	Definition string `json:"definition" fhir:"cardinality=1..1,required"`
	// Extension for Definition
	DefinitionExt *primitives.PrimitiveExtension `json:"_definition,omitempty" fhir:"cardinality=0..1"`
	// Subexpression relative to main expression
	Expression string `json:"expression" fhir:"cardinality=1..1,required"`
	// Extension for Expression
	ExpressionExt *primitives.PrimitiveExtension `json:"_expression,omitempty" fhir:"cardinality=0..1"`
}

// SearchParameter represents a FHIR SearchParameter.
type SearchParameter struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this search parameter, represented as a URI (globally unique)
	URL string `json:"url" fhir:"cardinality=1..1,required,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Business version of the search parameter
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Name for this search parameter (computer friendly)
	Name string `json:"name" fhir:"cardinality=1..1,required,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Original definition for the search parameter
	DerivedFrom *string `json:"derivedFrom,omitempty" fhir:"cardinality=0..1"`
	// Extension for DerivedFrom
	DerivedFromExt *primitives.PrimitiveExtension `json:"_derivedFrom,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the search parameter
	Description string `json:"description" fhir:"cardinality=1..1,required,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for search parameter (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this search parameter is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Code used in URL
	Code string `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// The resource type(s) this search parameter applies to
	Base []string `json:"base,omitempty" fhir:"cardinality=1..*,required,summary"`
	// Extension for Base
	BaseExt *primitives.PrimitiveExtension `json:"_base,omitempty" fhir:"cardinality=0..1"`
	// number | date | string | token | reference | composite | quantity | uri | special
	Type string `json:"type" fhir:"cardinality=1..1,required,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// FHIRPath expression that extracts the values
	Expression *string `json:"expression,omitempty" fhir:"cardinality=0..1"`
	// Extension for Expression
	ExpressionExt *primitives.PrimitiveExtension `json:"_expression,omitempty" fhir:"cardinality=0..1"`
	// XPath that extracts the values
	Xpath *string `json:"xpath,omitempty" fhir:"cardinality=0..1"`
	// Extension for Xpath
	XpathExt *primitives.PrimitiveExtension `json:"_xpath,omitempty" fhir:"cardinality=0..1"`
	// normal | phonetic | nearby | distance | other
	XpathUsage *string `json:"xpathUsage,omitempty" fhir:"cardinality=0..1"`
	// Extension for XpathUsage
	XpathUsageExt *primitives.PrimitiveExtension `json:"_xpathUsage,omitempty" fhir:"cardinality=0..1"`
	// Types of resource (if a resource reference)
	Target []string `json:"target,omitempty" fhir:"cardinality=0..*"`
	// Extension for Target
	TargetExt *primitives.PrimitiveExtension `json:"_target,omitempty" fhir:"cardinality=0..1"`
	// Allow multiple values per parameter (or)
	MultipleOr *bool `json:"multipleOr,omitempty" fhir:"cardinality=0..1"`
	// Extension for MultipleOr
	MultipleOrExt *primitives.PrimitiveExtension `json:"_multipleOr,omitempty" fhir:"cardinality=0..1"`
	// Allow multiple parameters (and)
	MultipleAnd *bool `json:"multipleAnd,omitempty" fhir:"cardinality=0..1"`
	// Extension for MultipleAnd
	MultipleAndExt *primitives.PrimitiveExtension `json:"_multipleAnd,omitempty" fhir:"cardinality=0..1"`
	// eq | ne | gt | lt | ge | le | sa | eb | ap
	Comparator []string `json:"comparator,omitempty" fhir:"cardinality=0..*"`
	// Extension for Comparator
	ComparatorExt *primitives.PrimitiveExtension `json:"_comparator,omitempty" fhir:"cardinality=0..1"`
	// missing | exact | contains | not | text | in | not-in | below | above | type | identifier | ofType
	Modifier []string `json:"modifier,omitempty" fhir:"cardinality=0..*"`
	// Extension for Modifier
	ModifierExt *primitives.PrimitiveExtension `json:"_modifier,omitempty" fhir:"cardinality=0..1"`
	// Chained names supported
	Chain []string `json:"chain,omitempty" fhir:"cardinality=0..*"`
	// Extension for Chain
	ChainExt *primitives.PrimitiveExtension `json:"_chain,omitempty" fhir:"cardinality=0..1"`
	// For Composite resources to define the parts
	Component []SearchParameterComponent `json:"component,omitempty" fhir:"cardinality=0..*"`
}
