// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeSpecimen is the FHIR resource type name for Specimen.
const ResourceTypeSpecimen = "Specimen"

// SpecimenCollection represents a FHIR BackboneElement for Specimen.collection.
type SpecimenCollection struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Who collected the specimen
	Collector *Reference `json:"collector,omitempty" fhir:"cardinality=0..1,summary"`
	// Collection time - dateTime option
	CollectedDateTime *primitives.DateTime `json:"collectedDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=collected"`
	// Extension for CollectedDateTime
	CollectedDateTimeExt *primitives.PrimitiveExtension `json:"_collectedDateTime,omitempty" fhir:"cardinality=0..1"`
	// Collection time - Period option
	CollectedPeriod *Period `json:"collectedPeriod,omitempty" fhir:"cardinality=0..1,summary,choice=collected"`
	// How long it took to collect specimen
	Duration *Duration `json:"duration,omitempty" fhir:"cardinality=0..1,summary"`
	// The quantity of specimen collected
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// Technique used to perform collection
	Method *CodeableConcept `json:"method,omitempty" fhir:"cardinality=0..1"`
	// Anatomical collection site
	BodySite *CodeableConcept `json:"bodySite,omitempty" fhir:"cardinality=0..1"`
	// Whether or how long patient abstained from food and/or drink - CodeableConcept option
	FastingStatusCodeableConcept *CodeableConcept `json:"fastingStatusCodeableConcept,omitempty" fhir:"cardinality=0..1,summary,choice=fastingStatus"`
	// Whether or how long patient abstained from food and/or drink - Duration option
	FastingStatusDuration *Duration `json:"fastingStatusDuration,omitempty" fhir:"cardinality=0..1,summary,choice=fastingStatus"`
}

// SpecimenProcessing represents a FHIR BackboneElement for Specimen.processing.
type SpecimenProcessing struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Textual description of procedure
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Indicates the treatment step  applied to the specimen
	Procedure *CodeableConcept `json:"procedure,omitempty" fhir:"cardinality=0..1"`
	// Material used in the processing step
	Additive []Reference `json:"additive,omitempty" fhir:"cardinality=0..*"`
	// Date and time of specimen processing - dateTime option
	TimeDateTime *primitives.DateTime `json:"timeDateTime,omitempty" fhir:"cardinality=0..1,choice=time"`
	// Extension for TimeDateTime
	TimeDateTimeExt *primitives.PrimitiveExtension `json:"_timeDateTime,omitempty" fhir:"cardinality=0..1"`
	// Date and time of specimen processing - Period option
	TimePeriod *Period `json:"timePeriod,omitempty" fhir:"cardinality=0..1,choice=time"`
}

// SpecimenContainer represents a FHIR BackboneElement for Specimen.container.
type SpecimenContainer struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Id for the container
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Textual description of the container
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Kind of container directly associated with specimen
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Container volume or size
	Capacity *Quantity `json:"capacity,omitempty" fhir:"cardinality=0..1"`
	// Quantity of specimen within container
	SpecimenQuantity *Quantity `json:"specimenQuantity,omitempty" fhir:"cardinality=0..1"`
	// Additive associated with container - CodeableConcept option
	AdditiveCodeableConcept *CodeableConcept `json:"additiveCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=additive"`
	// Additive associated with container - Reference option
	AdditiveReference *Reference `json:"additiveReference,omitempty" fhir:"cardinality=0..1,choice=additive"`
}

// Specimen represents a FHIR Specimen.
type Specimen struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External Identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Identifier assigned by the lab
	AccessionIdentifier *Identifier `json:"accessionIdentifier,omitempty" fhir:"cardinality=0..1,summary"`
	// available | unavailable | unsatisfactory | entered-in-error
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Kind of material that forms the specimen
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Where the specimen came from. This may be from patient(s), from a location (e.g., the source of an environmental sample), or a sampling of a substance or a device
	Subject *Reference `json:"subject,omitempty" fhir:"cardinality=0..1,summary"`
	// The time when specimen was received for processing
	ReceivedTime *primitives.DateTime `json:"receivedTime,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ReceivedTime
	ReceivedTimeExt *primitives.PrimitiveExtension `json:"_receivedTime,omitempty" fhir:"cardinality=0..1"`
	// Specimen from which this specimen originated
	Parent []Reference `json:"parent,omitempty" fhir:"cardinality=0..*"`
	// Why the specimen was collected
	Request []Reference `json:"request,omitempty" fhir:"cardinality=0..*"`
	// Collection details
	Collection *SpecimenCollection `json:"collection,omitempty" fhir:"cardinality=0..1"`
	// Processing and processing step details
	Processing []SpecimenProcessing `json:"processing,omitempty" fhir:"cardinality=0..*"`
	// Direct container of specimen (tube/slide, etc.)
	Container []SpecimenContainer `json:"container,omitempty" fhir:"cardinality=0..*"`
	// State of the specimen
	Condition []CodeableConcept `json:"condition,omitempty" fhir:"cardinality=0..*,summary"`
	// Comments
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
}
