// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeSpecimenDefinition is the FHIR resource type name for SpecimenDefinition.
const ResourceTypeSpecimenDefinition = "SpecimenDefinition"

// SpecimenDefinitionTypeTestedContainerAdditive represents a FHIR BackboneElement for SpecimenDefinition.typeTested.container.additive.
type SpecimenDefinitionTypeTestedContainerAdditive struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Additive associated with container - CodeableConcept option
	AdditiveCodeableConcept CodeableConcept `json:"additiveCodeableConcept" fhir:"cardinality=1..1,required,choice=additive"`
	// Additive associated with container - Reference option
	AdditiveReference Reference `json:"additiveReference" fhir:"cardinality=1..1,required,choice=additive"`
}

// SpecimenDefinitionTypeTestedContainer represents a FHIR BackboneElement for SpecimenDefinition.typeTested.container.
type SpecimenDefinitionTypeTestedContainer struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Container material
	Material *CodeableConcept `json:"material,omitempty" fhir:"cardinality=0..1"`
	// Kind of container associated with the kind of specimen
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Color of container cap
	Cap *CodeableConcept `json:"cap,omitempty" fhir:"cardinality=0..1"`
	// Container description
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Container capacity
	Capacity *Quantity `json:"capacity,omitempty" fhir:"cardinality=0..1"`
	// Minimum volume - Quantity option
	MinimumVolumeQuantity *Quantity `json:"minimumVolumeQuantity,omitempty" fhir:"cardinality=0..1,choice=minimumVolume"`
	// Minimum volume - string option
	MinimumVolumeString *string `json:"minimumVolumeString,omitempty" fhir:"cardinality=0..1,choice=minimumVolume"`
	// Extension for MinimumVolumeString
	MinimumVolumeStringExt *primitives.PrimitiveExtension `json:"_minimumVolumeString,omitempty" fhir:"cardinality=0..1"`
	// Additive associated with container
	Additive []SpecimenDefinitionTypeTestedContainerAdditive `json:"additive,omitempty" fhir:"cardinality=0..*"`
	// Specimen container preparation
	Preparation *string `json:"preparation,omitempty" fhir:"cardinality=0..1"`
	// Extension for Preparation
	PreparationExt *primitives.PrimitiveExtension `json:"_preparation,omitempty" fhir:"cardinality=0..1"`
}

// SpecimenDefinitionTypeTestedHandling represents a FHIR BackboneElement for SpecimenDefinition.typeTested.handling.
type SpecimenDefinitionTypeTestedHandling struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Temperature qualifier
	TemperatureQualifier *CodeableConcept `json:"temperatureQualifier,omitempty" fhir:"cardinality=0..1"`
	// Temperature range
	TemperatureRange *Range `json:"temperatureRange,omitempty" fhir:"cardinality=0..1"`
	// Maximum preservation time
	MaxDuration *Duration `json:"maxDuration,omitempty" fhir:"cardinality=0..1"`
	// Preservation instruction
	Instruction *string `json:"instruction,omitempty" fhir:"cardinality=0..1"`
	// Extension for Instruction
	InstructionExt *primitives.PrimitiveExtension `json:"_instruction,omitempty" fhir:"cardinality=0..1"`
}

// SpecimenDefinitionTypeTested represents a FHIR BackboneElement for SpecimenDefinition.typeTested.
type SpecimenDefinitionTypeTested struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Primary or secondary specimen
	IsDerived *bool `json:"isDerived,omitempty" fhir:"cardinality=0..1"`
	// Extension for IsDerived
	IsDerivedExt *primitives.PrimitiveExtension `json:"_isDerived,omitempty" fhir:"cardinality=0..1"`
	// Type of intended specimen
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// preferred | alternate
	Preference string `json:"preference" fhir:"cardinality=1..1,required"`
	// Extension for Preference
	PreferenceExt *primitives.PrimitiveExtension `json:"_preference,omitempty" fhir:"cardinality=0..1"`
	// The specimen's container
	Container *SpecimenDefinitionTypeTestedContainer `json:"container,omitempty" fhir:"cardinality=0..1"`
	// Specimen requirements
	Requirement *string `json:"requirement,omitempty" fhir:"cardinality=0..1"`
	// Extension for Requirement
	RequirementExt *primitives.PrimitiveExtension `json:"_requirement,omitempty" fhir:"cardinality=0..1"`
	// Specimen retention time
	RetentionTime *Duration `json:"retentionTime,omitempty" fhir:"cardinality=0..1"`
	// Rejection criterion
	RejectionCriterion []CodeableConcept `json:"rejectionCriterion,omitempty" fhir:"cardinality=0..*"`
	// Specimen handling before testing
	Handling []SpecimenDefinitionTypeTestedHandling `json:"handling,omitempty" fhir:"cardinality=0..*"`
}

// SpecimenDefinition represents a FHIR SpecimenDefinition.
type SpecimenDefinition struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier of a kind of specimen
	Identifier *Identifier `json:"identifier,omitempty" fhir:"cardinality=0..1,summary"`
	// Kind of material to collect
	TypeCollected *CodeableConcept `json:"typeCollected,omitempty" fhir:"cardinality=0..1,summary"`
	// Patient preparation for collection
	PatientPreparation []CodeableConcept `json:"patientPreparation,omitempty" fhir:"cardinality=0..*,summary"`
	// Time aspect for collection
	TimeAspect *string `json:"timeAspect,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for TimeAspect
	TimeAspectExt *primitives.PrimitiveExtension `json:"_timeAspect,omitempty" fhir:"cardinality=0..1"`
	// Specimen collection procedure
	Collection []CodeableConcept `json:"collection,omitempty" fhir:"cardinality=0..*,summary"`
	// Specimen in container intended for testing by lab
	TypeTested []SpecimenDefinitionTypeTested `json:"typeTested,omitempty" fhir:"cardinality=0..*"`
}
