// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeSubstance is the FHIR resource type name for Substance.
const ResourceTypeSubstance = "Substance"

// SubstanceInstance represents a FHIR BackboneElement for Substance.instance.
type SubstanceInstance struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Identifier of the package/container
	Identifier *Identifier `json:"identifier,omitempty" fhir:"cardinality=0..1,summary"`
	// When no longer valid to use
	Expiry *primitives.DateTime `json:"expiry,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Expiry
	ExpiryExt *primitives.PrimitiveExtension `json:"_expiry,omitempty" fhir:"cardinality=0..1"`
	// Amount of substance in the package
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1,summary"`
}

// SubstanceIngredient represents a FHIR BackboneElement for Substance.ingredient.
type SubstanceIngredient struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Optional amount (concentration)
	Quantity *Ratio `json:"quantity,omitempty" fhir:"cardinality=0..1,summary"`
	// A component of the substance - CodeableConcept option
	SubstanceCodeableConcept CodeableConcept `json:"substanceCodeableConcept" fhir:"cardinality=1..1,required,summary,choice=substance"`
	// A component of the substance - Reference option
	SubstanceReference Reference `json:"substanceReference" fhir:"cardinality=1..1,required,summary,choice=substance"`
}

// Substance represents a FHIR Substance.
type Substance struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Unique identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// active | inactive | entered-in-error
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// What class/type of substance this is
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// What substance this is
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Textual description of the substance, comments
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// If this describes a specific package/container of the substance
	Instance []SubstanceInstance `json:"instance,omitempty" fhir:"cardinality=0..*,summary"`
	// Composition information about the substance
	Ingredient []SubstanceIngredient `json:"ingredient,omitempty" fhir:"cardinality=0..*,summary"`
}
