// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeSubstancePolymer is the FHIR resource type name for SubstancePolymer.
const ResourceTypeSubstancePolymer = "SubstancePolymer"

// SubstancePolymerMonomerSetStartingMaterial represents a FHIR BackboneElement for SubstancePolymer.monomerSet.startingMaterial.
type SubstancePolymerMonomerSetStartingMaterial struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Todo
	Material *CodeableConcept `json:"material,omitempty" fhir:"cardinality=0..1,summary"`
	// Todo
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Todo
	IsDefining *bool `json:"isDefining,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for IsDefining
	IsDefiningExt *primitives.PrimitiveExtension `json:"_isDefining,omitempty" fhir:"cardinality=0..1"`
	// Todo
	Amount *SubstanceAmount `json:"amount,omitempty" fhir:"cardinality=0..1,summary"`
}

// SubstancePolymerMonomerSet represents a FHIR BackboneElement for SubstancePolymer.monomerSet.
type SubstancePolymerMonomerSet struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Todo
	RatioType *CodeableConcept `json:"ratioType,omitempty" fhir:"cardinality=0..1,summary"`
	// Todo
	StartingMaterial []SubstancePolymerMonomerSetStartingMaterial `json:"startingMaterial,omitempty" fhir:"cardinality=0..*,summary"`
}

// SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation represents a FHIR BackboneElement for SubstancePolymer.repeat.repeatUnit.degreeOfPolymerisation.
type SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Todo
	Degree *CodeableConcept `json:"degree,omitempty" fhir:"cardinality=0..1,summary"`
	// Todo
	Amount *SubstanceAmount `json:"amount,omitempty" fhir:"cardinality=0..1,summary"`
}

// SubstancePolymerRepeatRepeatUnitStructuralRepresentation represents a FHIR BackboneElement for SubstancePolymer.repeat.repeatUnit.structuralRepresentation.
type SubstancePolymerRepeatRepeatUnitStructuralRepresentation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Todo
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Todo
	Representation *string `json:"representation,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Representation
	RepresentationExt *primitives.PrimitiveExtension `json:"_representation,omitempty" fhir:"cardinality=0..1"`
	// Todo
	Attachment *Attachment `json:"attachment,omitempty" fhir:"cardinality=0..1,summary"`
}

// SubstancePolymerRepeatRepeatUnit represents a FHIR BackboneElement for SubstancePolymer.repeat.repeatUnit.
type SubstancePolymerRepeatRepeatUnit struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Todo
	OrientationOfPolymerisation *CodeableConcept `json:"orientationOfPolymerisation,omitempty" fhir:"cardinality=0..1,summary"`
	// Todo
	RepeatUnit *string `json:"repeatUnit,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for RepeatUnit
	RepeatUnitExt *primitives.PrimitiveExtension `json:"_repeatUnit,omitempty" fhir:"cardinality=0..1"`
	// Todo
	Amount *SubstanceAmount `json:"amount,omitempty" fhir:"cardinality=0..1,summary"`
	// Todo
	DegreeOfPolymerisation []SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation `json:"degreeOfPolymerisation,omitempty" fhir:"cardinality=0..*,summary"`
	// Todo
	StructuralRepresentation []SubstancePolymerRepeatRepeatUnitStructuralRepresentation `json:"structuralRepresentation,omitempty" fhir:"cardinality=0..*,summary"`
}

// SubstancePolymerRepeat represents a FHIR BackboneElement for SubstancePolymer.repeat.
type SubstancePolymerRepeat struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Todo
	NumberOfUnits *int `json:"numberOfUnits,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for NumberOfUnits
	NumberOfUnitsExt *primitives.PrimitiveExtension `json:"_numberOfUnits,omitempty" fhir:"cardinality=0..1"`
	// Todo
	AverageMolecularFormula *string `json:"averageMolecularFormula,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for AverageMolecularFormula
	AverageMolecularFormulaExt *primitives.PrimitiveExtension `json:"_averageMolecularFormula,omitempty" fhir:"cardinality=0..1"`
	// Todo
	RepeatUnitAmountType *CodeableConcept `json:"repeatUnitAmountType,omitempty" fhir:"cardinality=0..1,summary"`
	// Todo
	RepeatUnit []SubstancePolymerRepeatRepeatUnit `json:"repeatUnit,omitempty" fhir:"cardinality=0..*,summary"`
}

// SubstancePolymer represents a FHIR SubstancePolymer.
type SubstancePolymer struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Todo
	Class *CodeableConcept `json:"class,omitempty" fhir:"cardinality=0..1,summary"`
	// Todo
	Geometry *CodeableConcept `json:"geometry,omitempty" fhir:"cardinality=0..1,summary"`
	// Todo
	CopolymerConnectivity []CodeableConcept `json:"copolymerConnectivity,omitempty" fhir:"cardinality=0..*,summary"`
	// Todo
	Modification []string `json:"modification,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for Modification
	ModificationExt *primitives.PrimitiveExtension `json:"_modification,omitempty" fhir:"cardinality=0..1"`
	// Todo
	MonomerSet []SubstancePolymerMonomerSet `json:"monomerSet,omitempty" fhir:"cardinality=0..*,summary"`
	// Todo
	Repeat []SubstancePolymerRepeat `json:"repeat,omitempty" fhir:"cardinality=0..*,summary"`
}
