// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeSupplyDelivery is the FHIR resource type name for SupplyDelivery.
const ResourceTypeSupplyDelivery = "SupplyDelivery"

// SupplyDeliverySuppliedItem represents a FHIR BackboneElement for SupplyDelivery.suppliedItem.
type SupplyDeliverySuppliedItem struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Amount dispensed
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// Medication, Substance, or Device supplied - CodeableConcept option
	ItemCodeableConcept *CodeableConcept `json:"itemCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=item"`
	// Medication, Substance, or Device supplied - Reference option
	ItemReference *Reference `json:"itemReference,omitempty" fhir:"cardinality=0..1,choice=item"`
}

// SupplyDelivery represents a FHIR SupplyDelivery.
type SupplyDelivery struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// Fulfills plan, proposal or order
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// Part of referenced event
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*,summary"`
	// in-progress | completed | abandoned | entered-in-error
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Patient for whom the item is supplied
	Patient *Reference `json:"patient,omitempty" fhir:"cardinality=0..1"`
	// Category of dispense event
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// The item that is delivered or supplied
	SuppliedItem *SupplyDeliverySuppliedItem `json:"suppliedItem,omitempty" fhir:"cardinality=0..1"`
	// When event occurred - dateTime option
	OccurrenceDateTime *primitives.DateTime `json:"occurrenceDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// Extension for OccurrenceDateTime
	OccurrenceDateTimeExt *primitives.PrimitiveExtension `json:"_occurrenceDateTime,omitempty" fhir:"cardinality=0..1"`
	// When event occurred - Period option
	OccurrencePeriod *Period `json:"occurrencePeriod,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// When event occurred - Timing option
	OccurrenceTiming *Timing `json:"occurrenceTiming,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// Dispenser
	Supplier *Reference `json:"supplier,omitempty" fhir:"cardinality=0..1"`
	// Where the Supply was sent
	Destination *Reference `json:"destination,omitempty" fhir:"cardinality=0..1"`
	// Who collected the Supply
	Receiver []Reference `json:"receiver,omitempty" fhir:"cardinality=0..*"`
}
