// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T12:54:49Z
// FHIR Version: R4
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R4/

package r4

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeValueSet is the FHIR resource type name for ValueSet.
const ResourceTypeValueSet = "ValueSet"

// ValueSetComposeIncludeConceptDesignation represents a FHIR BackboneElement for ValueSet.compose.include.concept.designation.
type ValueSetComposeIncludeConceptDesignation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Human language of the designation
	Language *string `json:"language,omitempty" fhir:"cardinality=0..1"`
	// Extension for Language
	LanguageExt *primitives.PrimitiveExtension `json:"_language,omitempty" fhir:"cardinality=0..1"`
	// Types of uses of designations
	Use *Coding `json:"use,omitempty" fhir:"cardinality=0..1"`
	// The text value for this designation
	Value string `json:"value" fhir:"cardinality=1..1,required"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
}

// ValueSetComposeIncludeConcept represents a FHIR BackboneElement for ValueSet.compose.include.concept.
type ValueSetComposeIncludeConcept struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Code or expression from system
	Code string `json:"code" fhir:"cardinality=1..1,required"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// Text to display for this code for this value set in this valueset
	Display *string `json:"display,omitempty" fhir:"cardinality=0..1"`
	// Extension for Display
	DisplayExt *primitives.PrimitiveExtension `json:"_display,omitempty" fhir:"cardinality=0..1"`
	// Additional representations for this concept
	Designation []ValueSetComposeIncludeConceptDesignation `json:"designation,omitempty" fhir:"cardinality=0..*"`
}

// ValueSetComposeIncludeFilter represents a FHIR BackboneElement for ValueSet.compose.include.filter.
type ValueSetComposeIncludeFilter struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// A property/filter defined by the code system
	Property string `json:"property" fhir:"cardinality=1..1,required,summary"`
	// Extension for Property
	PropertyExt *primitives.PrimitiveExtension `json:"_property,omitempty" fhir:"cardinality=0..1"`
	// = | is-a | descendent-of | is-not-a | regex | in | not-in | generalizes | exists
	Op string `json:"op" fhir:"cardinality=1..1,required,summary"`
	// Extension for Op
	OpExt *primitives.PrimitiveExtension `json:"_op,omitempty" fhir:"cardinality=0..1"`
	// Code from the system, or regex criteria, or boolean value for exists
	Value string `json:"value" fhir:"cardinality=1..1,required,summary"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
}

// ValueSetComposeInclude represents a FHIR BackboneElement for ValueSet.compose.include.
type ValueSetComposeInclude struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The system the codes come from
	System *string `json:"system,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for System
	SystemExt *primitives.PrimitiveExtension `json:"_system,omitempty" fhir:"cardinality=0..1"`
	// Specific version of the code system referred to
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// A concept defined in the system
	Concept []ValueSetComposeIncludeConcept `json:"concept,omitempty" fhir:"cardinality=0..*"`
	// Select codes/concepts by their properties (including relationships)
	Filter []ValueSetComposeIncludeFilter `json:"filter,omitempty" fhir:"cardinality=0..*,summary"`
	// Select the contents included in this value set
	ValueSet []string `json:"valueSet,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for ValueSet
	ValueSetExt *primitives.PrimitiveExtension `json:"_valueSet,omitempty" fhir:"cardinality=0..1"`
}

// ValueSetComposeExclude represents a FHIR BackboneElement for ValueSet.compose.exclude.
type ValueSetComposeExclude struct {
}

// ValueSetCompose represents a FHIR BackboneElement for ValueSet.compose.
type ValueSetCompose struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Fixed date for references with no specified version (transitive)
	LockedDate *primitives.Date `json:"lockedDate,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for LockedDate
	LockedDateExt *primitives.PrimitiveExtension `json:"_lockedDate,omitempty" fhir:"cardinality=0..1"`
	// Whether inactive codes are in the value set
	Inactive *bool `json:"inactive,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Inactive
	InactiveExt *primitives.PrimitiveExtension `json:"_inactive,omitempty" fhir:"cardinality=0..1"`
	// Include one or more codes from a code system or other value set(s)
	Include []ValueSetComposeInclude `json:"include,omitempty" fhir:"cardinality=1..*,required,summary"`
	// Explicitly exclude codes from a code system or other value sets
	Exclude []ValueSetComposeExclude `json:"exclude,omitempty" fhir:"cardinality=0..*"`
}

// ValueSetExpansionParameter represents a FHIR BackboneElement for ValueSet.expansion.parameter.
type ValueSetExpansionParameter struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Name as assigned by the client or server
	Name string `json:"name" fhir:"cardinality=1..1,required"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Value of the named parameter - string option
	ValueString *string `json:"valueString,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueString
	ValueStringExt *primitives.PrimitiveExtension `json:"_valueString,omitempty" fhir:"cardinality=0..1"`
	// Value of the named parameter - boolean option
	ValueBoolean *bool `json:"valueBoolean,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
	// Value of the named parameter - integer option
	ValueInteger *int `json:"valueInteger,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueInteger
	ValueIntegerExt *primitives.PrimitiveExtension `json:"_valueInteger,omitempty" fhir:"cardinality=0..1"`
	// Value of the named parameter - decimal option
	ValueDecimal *float64 `json:"valueDecimal,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueDecimal
	ValueDecimalExt *primitives.PrimitiveExtension `json:"_valueDecimal,omitempty" fhir:"cardinality=0..1"`
	// Value of the named parameter - uri option
	ValueURI *string `json:"valueURI,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueURI
	ValueURIExt *primitives.PrimitiveExtension `json:"_valueURI,omitempty" fhir:"cardinality=0..1"`
	// Value of the named parameter - code option
	ValueCode *string `json:"valueCode,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueCode
	ValueCodeExt *primitives.PrimitiveExtension `json:"_valueCode,omitempty" fhir:"cardinality=0..1"`
	// Value of the named parameter - dateTime option
	ValueDateTime *primitives.DateTime `json:"valueDateTime,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueDateTime
	ValueDateTimeExt *primitives.PrimitiveExtension `json:"_valueDateTime,omitempty" fhir:"cardinality=0..1"`
}

// ValueSetExpansionContainsDesignation represents a FHIR BackboneElement for ValueSet.expansion.contains.designation.
type ValueSetExpansionContainsDesignation struct {
}

// ValueSetExpansionContainsContains represents a FHIR BackboneElement for ValueSet.expansion.contains.contains.
type ValueSetExpansionContainsContains struct {
}

// ValueSetExpansionContains represents a FHIR BackboneElement for ValueSet.expansion.contains.
type ValueSetExpansionContains struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// System value for the code
	System *string `json:"system,omitempty" fhir:"cardinality=0..1"`
	// Extension for System
	SystemExt *primitives.PrimitiveExtension `json:"_system,omitempty" fhir:"cardinality=0..1"`
	// If user cannot select this entry
	Abstract *bool `json:"abstract,omitempty" fhir:"cardinality=0..1"`
	// Extension for Abstract
	AbstractExt *primitives.PrimitiveExtension `json:"_abstract,omitempty" fhir:"cardinality=0..1"`
	// If concept is inactive in the code system
	Inactive *bool `json:"inactive,omitempty" fhir:"cardinality=0..1"`
	// Extension for Inactive
	InactiveExt *primitives.PrimitiveExtension `json:"_inactive,omitempty" fhir:"cardinality=0..1"`
	// Version in which this code/display is defined
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Code - if blank, this is not a selectable code
	Code *string `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// User display for the concept
	Display *string `json:"display,omitempty" fhir:"cardinality=0..1"`
	// Extension for Display
	DisplayExt *primitives.PrimitiveExtension `json:"_display,omitempty" fhir:"cardinality=0..1"`
	// Additional representations for this item
	Designation []ValueSetExpansionContainsDesignation `json:"designation,omitempty" fhir:"cardinality=0..*"`
	// Codes contained under this entry
	Contains []ValueSetExpansionContainsContains `json:"contains,omitempty" fhir:"cardinality=0..*"`
}

// ValueSetExpansion represents a FHIR BackboneElement for ValueSet.expansion.
type ValueSetExpansion struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Identifies the value set expansion (business identifier)
	Identifier *string `json:"identifier,omitempty" fhir:"cardinality=0..1"`
	// Extension for Identifier
	IdentifierExt *primitives.PrimitiveExtension `json:"_identifier,omitempty" fhir:"cardinality=0..1"`
	// Time ValueSet expansion happened
	Timestamp primitives.DateTime `json:"timestamp" fhir:"cardinality=1..1,required"`
	// Extension for Timestamp
	TimestampExt *primitives.PrimitiveExtension `json:"_timestamp,omitempty" fhir:"cardinality=0..1"`
	// Total number of codes in the expansion
	Total *int `json:"total,omitempty" fhir:"cardinality=0..1"`
	// Extension for Total
	TotalExt *primitives.PrimitiveExtension `json:"_total,omitempty" fhir:"cardinality=0..1"`
	// Offset at which this resource starts
	Offset *int `json:"offset,omitempty" fhir:"cardinality=0..1"`
	// Extension for Offset
	OffsetExt *primitives.PrimitiveExtension `json:"_offset,omitempty" fhir:"cardinality=0..1"`
	// Parameter that controlled the expansion process
	Parameter []ValueSetExpansionParameter `json:"parameter,omitempty" fhir:"cardinality=0..*"`
	// Codes in the value set
	Contains []ValueSetExpansionContains `json:"contains,omitempty" fhir:"cardinality=0..*"`
}

// ValueSet represents a FHIR ValueSet.
type ValueSet struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this value set, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the value set (business identifier)
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the value set
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Name for this value set (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this value set (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the value set
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for value set (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Indicates whether or not any change to the content logical definition may occur
	Immutable *bool `json:"immutable,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Immutable
	ImmutableExt *primitives.PrimitiveExtension `json:"_immutable,omitempty" fhir:"cardinality=0..1"`
	// Why this value set is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// Content logical definition of the value set (CLD)
	Compose *ValueSetCompose `json:"compose,omitempty" fhir:"cardinality=0..1"`
	// Used when the value set is "expanded"
	Expansion *ValueSetExpansion `json:"expansion,omitempty" fhir:"cardinality=0..1"`
}
