// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2025-11-09T14:19:05Z
// FHIR Version: R5
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R5/

package resources

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeBinary is the FHIR resource type name for Binary.
const ResourceTypeBinary = "Binary"

// Binary represents a FHIR Binary.
type Binary struct {
	fhir.Resource
	// MimeType of the binary content
	ContentType string `json:"contentType" fhir:"cardinality=1..1,required,summary"`
	// Extension for ContentType
	ContentTypeExt *primitives.PrimitiveExtension `json:"_contentType,omitempty" fhir:"cardinality=0..1"`
	// Identifies another resource to use as proxy when enforcing access control
	SecurityContext *Reference `json:"securityContext,omitempty" fhir:"cardinality=0..1,summary"`
	// The actual content
	Data *string `json:"data,omitempty" fhir:"cardinality=0..1"`
	// Extension for Data
	DataExt *primitives.PrimitiveExtension `json:"_data,omitempty" fhir:"cardinality=0..1"`
}
