// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2025-11-09T14:19:05Z
// FHIR Version: R5
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R5/

package resources

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeFormularyItem is the FHIR resource type name for FormularyItem.
const ResourceTypeFormularyItem = "FormularyItem"

// FormularyItem represents a FHIR FormularyItem.
type FormularyItem struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier for this formulary item
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Codes that identify this formulary item
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// active | entered-in-error | inactive
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
}
