// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2025-11-09T14:19:05Z
// FHIR Version: R5
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R5/

package resources

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeOperationOutcome is the FHIR resource type name for OperationOutcome.
const ResourceTypeOperationOutcome = "OperationOutcome"

// OperationOutcomeIssue represents a FHIR BackboneElement for OperationOutcome.issue.
type OperationOutcomeIssue struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// fatal | error | warning | information | success
	Severity string `json:"severity" fhir:"cardinality=1..1,required,summary"`
	// Extension for Severity
	SeverityExt *primitives.PrimitiveExtension `json:"_severity,omitempty" fhir:"cardinality=0..1"`
	// Error or warning code
	Code string `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// Additional details about the error
	Details *CodeableConcept `json:"details,omitempty" fhir:"cardinality=0..1,summary"`
	// Additional diagnostic information about the issue
	Diagnostics *string `json:"diagnostics,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Diagnostics
	DiagnosticsExt *primitives.PrimitiveExtension `json:"_diagnostics,omitempty" fhir:"cardinality=0..1"`
	// Deprecated: Path of element(s) related to issue
	Location []string `json:"location,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for Location
	LocationExt *primitives.PrimitiveExtension `json:"_location,omitempty" fhir:"cardinality=0..1"`
	// FHIRPath of element(s) related to issue
	Expression []string `json:"expression,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for Expression
	ExpressionExt *primitives.PrimitiveExtension `json:"_expression,omitempty" fhir:"cardinality=0..1"`
}

// OperationOutcome represents a FHIR OperationOutcome.
type OperationOutcome struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// A single issue associated with the action
	Issue []OperationOutcomeIssue `json:"issue,omitempty" fhir:"cardinality=1..*,required,summary"`
}
