// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2025-11-09T14:19:05Z
// FHIR Version: R5
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R5/

package resources

import (
	"github.com/zs-health/zh-fhir-go/fhir"
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ResourceTypeSchedule is the FHIR resource type name for Schedule.
const ResourceTypeSchedule = "Schedule"

// Schedule represents a FHIR Schedule.
type Schedule struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External Ids for this item
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether this schedule is in active use
	Active *bool `json:"active,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Active
	ActiveExt *primitives.PrimitiveExtension `json:"_active,omitempty" fhir:"cardinality=0..1"`
	// High-level category
	ServiceCategory []CodeableConcept `json:"serviceCategory,omitempty" fhir:"cardinality=0..*,summary"`
	// Specific service
	ServiceType []CodeableReference `json:"serviceType,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of specialty needed
	Specialty []CodeableConcept `json:"specialty,omitempty" fhir:"cardinality=0..*,summary"`
	// Human-readable label
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Resource(s) that availability information is being provided for
	Actor []Reference `json:"actor,omitempty" fhir:"cardinality=1..*,required,summary"`
	// Period of time covered by schedule
	PlanningHorizon *Period `json:"planningHorizon,omitempty" fhir:"cardinality=0..1,summary"`
	// Comments on availability
	Comment *string `json:"comment,omitempty" fhir:"cardinality=0..1"`
	// Extension for Comment
	CommentExt *primitives.PrimitiveExtension `json:"_comment,omitempty" fhir:"cardinality=0..1"`
}
