// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2025-11-09T14:19:50Z
// FHIR Version: R5
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R5/

package resources

import (
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// AvailabilityAvailableTime represents a FHIR BackboneElement for Availability.availableTime.
type AvailabilityAvailableTime struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// mon | tue | wed | thu | fri | sat | sun
	DaysOfWeek []string `json:"daysOfWeek,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for DaysOfWeek
	DaysOfWeekExt *primitives.PrimitiveExtension `json:"_daysOfWeek,omitempty" fhir:"cardinality=0..1"`
	// Always available? i.e. 24 hour service
	AllDay *bool `json:"allDay,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for AllDay
	AllDayExt *primitives.PrimitiveExtension `json:"_allDay,omitempty" fhir:"cardinality=0..1"`
	// Opening time of day (ignored if allDay = true)
	AvailableStartTime *primitives.Time `json:"availableStartTime,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for AvailableStartTime
	AvailableStartTimeExt *primitives.PrimitiveExtension `json:"_availableStartTime,omitempty" fhir:"cardinality=0..1"`
	// Closing time of day (ignored if allDay = true)
	AvailableEndTime *primitives.Time `json:"availableEndTime,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for AvailableEndTime
	AvailableEndTimeExt *primitives.PrimitiveExtension `json:"_availableEndTime,omitempty" fhir:"cardinality=0..1"`
}

// AvailabilityNotAvailableTime represents a FHIR BackboneElement for Availability.notAvailableTime.
type AvailabilityNotAvailableTime struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Reason presented to the user explaining why time not available
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Service not available during this period
	During *Period `json:"during,omitempty" fhir:"cardinality=0..1,summary"`
}

// Availability represents a FHIR Availability.
type Availability struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Times the {item} is available
	AvailableTime []AvailabilityAvailableTime `json:"availableTime,omitempty" fhir:"cardinality=0..*,summary"`
	// Not available during this time due to provided reason
	NotAvailableTime []AvailabilityNotAvailableTime `json:"notAvailableTime,omitempty" fhir:"cardinality=0..*,summary"`
}
