// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2025-11-09T14:19:50Z
// FHIR Version: R5
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R5/

package resources

import (
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// CodeableReference represents a FHIR CodeableReference.
type CodeableReference struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Reference to a concept (by class)
	Concept *CodeableConcept `json:"concept,omitempty" fhir:"cardinality=0..1,summary"`
	// Reference to a resource (by instance)
	Reference *Reference `json:"reference,omitempty" fhir:"cardinality=0..1,summary"`
}
