// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2025-11-09T14:19:50Z
// FHIR Version: R5
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R5/

package resources

import (
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ExtendedContactDetail represents a FHIR ExtendedContactDetail.
type ExtendedContactDetail struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// The type of contact
	Purpose *CodeableConcept `json:"purpose,omitempty" fhir:"cardinality=0..1,summary"`
	// Name of an individual to contact
	Name []HumanName `json:"name,omitempty" fhir:"cardinality=0..*,summary"`
	// Contact details (e.g.phone/fax/url)
	Telecom []ContactPoint `json:"telecom,omitempty" fhir:"cardinality=0..*,summary"`
	// Address for the contact
	Address *Address `json:"address,omitempty" fhir:"cardinality=0..1,summary"`
	// This contact detail is handled/monitored by a specific organization
	Organization *Reference `json:"organization,omitempty" fhir:"cardinality=0..1,summary"`
	// Period that this contact was valid for usage
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
}
