// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2025-11-09T14:19:50Z
// FHIR Version: R5
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/R5/

package resources

import (
	"github.com/zs-health/zh-fhir-go/fhir/primitives"
)

// ParameterDefinition represents a FHIR ParameterDefinition.
type ParameterDefinition struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Name used to access the parameter value
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// in | out
	Use string `json:"use" fhir:"cardinality=1..1,required,summary"`
	// Extension for Use
	UseExt *primitives.PrimitiveExtension `json:"_use,omitempty" fhir:"cardinality=0..1"`
	// Minimum cardinality
	Min *int `json:"min,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Min
	MinExt *primitives.PrimitiveExtension `json:"_min,omitempty" fhir:"cardinality=0..1"`
	// Maximum cardinality (a number of *)
	Max *string `json:"max,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Max
	MaxExt *primitives.PrimitiveExtension `json:"_max,omitempty" fhir:"cardinality=0..1"`
	// A brief description of the parameter
	Documentation *string `json:"documentation,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Documentation
	DocumentationExt *primitives.PrimitiveExtension `json:"_documentation,omitempty" fhir:"cardinality=0..1"`
	// What type of value
	Type string `json:"type" fhir:"cardinality=1..1,required,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// What profile the value is expected to be
	Profile *string `json:"profile,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Profile
	ProfileExt *primitives.PrimitiveExtension `json:"_profile,omitempty" fhir:"cardinality=0..1"`
}
